// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"

	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilGetInstallmentCollectionRequest is returned when the GetInstallmentCollectionRequest is nil.
	ErrNilGetInstallmentCollectionRequest = errors.New("input GetInstallmentCollectionRequest is nil")

	// ErrGetInstallmentCollectionRequestPolicyRequiredValidation is returned when PolicyNumber is not provided.
	ErrGetInstallmentCollectionRequestPolicyRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber is required", Path: "GetInstallmentCollectionRequest.PolicyNumber", Type: "required"}

	// ErrGetInstallmentCollectionRequestInstallmentNumberRequiredValidation is returned when the InstallmentNumber is required but not provided.
	ErrGetInstallmentCollectionRequestInstallmentNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field InstallmentNumber is required", Path: "GetInstallmentCollectionRequest.InstallmentNumber", Type: "required"}

	// ErrGetInstallmentCollectionRequestInstallmentNumberMinValidation is the error returned when the field is less than the minimum.
	ErrGetInstallmentCollectionRequestInstallmentNumberMinValidation = govaliderrors.ValidationError{Reason: "field InstallmentNumber must be at least 1", Path: "GetInstallmentCollectionRequest.InstallmentNumber", Type: "min"}

	// ErrGetInstallmentCollectionRequestInstallmentNumberMaxValidation is the error returned when the field exceeds the maximum.
	ErrGetInstallmentCollectionRequestInstallmentNumberMaxValidation = govaliderrors.ValidationError{Reason: "field InstallmentNumber must be at most 12", Path: "GetInstallmentCollectionRequest.InstallmentNumber", Type: "max"}
)

func ValidateGetInstallmentCollectionRequest(t *GetInstallmentCollectionRequest) error {
	if t == nil {
		return ErrNilGetInstallmentCollectionRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.PolicyNumber == "" {
		err := ErrGetInstallmentCollectionRequestPolicyRequiredValidation
		err.Value = t.PolicyNumber
		errs = append(errs, err)
	}
	if t.NumberOfInstallments != nil && *t.NumberOfInstallments < 0 {
		err := govaliderrors.ValidationError{Reason: "field NumberOfInstallments must be >= 0", Path: "GetInstallmentCollectionRequest.NumberOfInstallments", Type: "min"}
		err.Value = *t.NumberOfInstallments
		errs = append(errs, err)
	}

	if errs != nil {
		return errs
	}

	return nil
}

// Validate implements validator for GetInstallmentCollectionRequest
func (req GetInstallmentCollectionRequest) Validate() error {
	return ValidateGetInstallmentCollectionRequest(&req)
}
