// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"
	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilRevivalMemoRequest is returned when the RevivalMemoRequest is nil.
	ErrNilRevivalMemoRequest = errors.New("input RevivalMemoRequest is nil")

	// ErrRevivalMemoRequestTicketIDRequiredValidation is returned when the TicketID is required but not provided.
	ErrRevivalMemoRequestTicketIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TicketID is required", Path: "RevivalMemoRequest.TicketID", Type: "required"}

	// ErrRevivalMemoRequestPolicyNumberLengthValidation is the error returned when the length of the field is not exactly 13.
	ErrRevivalMemoRequestPolicyNumberLengthValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber length must be exactly 13", Path: "RevivalMemoRequest.PolicyNumber", Type: "length"}

	// ErrRevivalMemoRequestPolicyNumberRequiredValidation is returned when the PolicyNumber is required but not provided.
	ErrRevivalMemoRequestPolicyNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber is required", Path: "RevivalMemoRequest.PolicyNumber", Type: "required"}

	// ErrRevivalMemoRequestOfficeIDRequiredValidation is returned when the OfficeID is required but not provided.
	ErrRevivalMemoRequestOfficeIDRequiredValidation = govaliderrors.ValidationError{Reason: "field OfficeID is required", Path: "RevivalMemoRequest.OfficeID", Type: "required"}
)

func ValidateRevivalMemoRequest(t *RevivalMemoRequest) error {
	if t == nil {
		return ErrNilRevivalMemoRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TicketID == "" {
		err := ErrRevivalMemoRequestTicketIDRequiredValidation
		err.Value = t.TicketID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.PolicyNumber) != 13 {
		err := ErrRevivalMemoRequestPolicyNumberLengthValidation
		err.Value = t.PolicyNumber
		errs = append(errs, err)
	}

	if t.PolicyNumber == "" {
		err := ErrRevivalMemoRequestPolicyNumberRequiredValidation
		err.Value = t.PolicyNumber
		errs = append(errs, err)
	}

	if t.OfficeID == "" {
		err := ErrRevivalMemoRequestOfficeIDRequiredValidation
		err.Value = t.OfficeID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*RevivalMemoRequest)(nil)

func (t *RevivalMemoRequest) Validate() error {
	return ValidateRevivalMemoRequest(t)
}
