// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"
	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilIndexRevivalRequest is returned when the IndexRevivalRequest is nil.
	ErrNilIndexRevivalRequest = errors.New("input IndexRevivalRequest is nil")

	// ErrIndexRevivalRequestPolicyNumberLengthValidation is the error returned when the length of the field is not exactly 13.
	ErrIndexRevivalRequestPolicyNumberLengthValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber length must be exactly 13", Path: "IndexRevivalRequest.PolicyNumber", Type: "length"}

	// ErrIndexRevivalRequestPolicyNumberRequiredValidation is returned when the PolicyNumber is required but not provided.
	ErrIndexRevivalRequestPolicyNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber is required", Path: "IndexRevivalRequest.PolicyNumber", Type: "required"}

	// ErrIndexRevivalRequestCustomerIDRequiredValidation is returned when the CustomerID is required but not provided.
	ErrIndexRevivalRequestCustomerIDRequiredValidation = govaliderrors.ValidationError{Reason: "field CustomerID is required", Path: "IndexRevivalRequest.CustomerID", Type: "required"}

	// ErrIndexRevivalRequestCustomerNameRequiredValidation is returned when the CustomerName is required but not provided.
	ErrIndexRevivalRequestCustomerNameRequiredValidation = govaliderrors.ValidationError{Reason: "field CustomerName is required", Path: "IndexRevivalRequest.CustomerName", Type: "required"}

	// ErrIndexRevivalRequestRequestOwnerRequiredValidation is returned when the RequestOwner is required but not provided.
	ErrIndexRevivalRequestRequestOwnerRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestOwner is required", Path: "IndexRevivalRequest.RequestOwner", Type: "required"}

	// ErrIndexRevivalRequestIndexedByRequiredValidation is returned when the IndexedBy is required but not provided.
	ErrIndexRevivalRequestIndexedByRequiredValidation = govaliderrors.ValidationError{Reason: "field IndexedBy is required", Path: "IndexRevivalRequest.IndexedBy", Type: "required"}

	// ErrIndexRevivalRequestOfficeRequiredValidation is returned when the OfficeID is required but not provided.
	ErrIndexRevivalRequestOfficeRequiredValidation = govaliderrors.ValidationError{Reason: "field OfficeID is required", Path: "IndexRevivalRequest.OfficeID", Type: "required"}
)

func ValidateIndexRevivalRequest(t *IndexRevivalRequest) error {
	if t == nil {
		return ErrNilIndexRevivalRequest
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.PolicyNumber) != 13 {
		err := ErrIndexRevivalRequestPolicyNumberLengthValidation
		err.Value = t.PolicyNumber
		errs = append(errs, err)
	}

	if t.PolicyNumber == "" {
		err := ErrIndexRevivalRequestPolicyNumberRequiredValidation
		err.Value = t.PolicyNumber
		errs = append(errs, err)
	}

	if t.CustomerID == "" {
		err := ErrIndexRevivalRequestCustomerIDRequiredValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if t.CustomerName == "" {
		err := ErrIndexRevivalRequestCustomerNameRequiredValidation
		err.Value = t.CustomerName
		errs = append(errs, err)
	}

	if t.RequestOwner == "" {
		err := ErrIndexRevivalRequestRequestOwnerRequiredValidation
		err.Value = t.RequestOwner
		errs = append(errs, err)
	}

	if t.IndexedBy == "" {
		err := ErrIndexRevivalRequestIndexedByRequiredValidation
		err.Value = t.IndexedBy
		errs = append(errs, err)
	}

	if t.OfficeID == "" {
		err := ErrIndexRevivalRequestOfficeRequiredValidation
		err.Value = t.OfficeID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*IndexRevivalRequest)(nil)

func (t *IndexRevivalRequest) Validate() error {
	return ValidateIndexRevivalRequest(t)
}
