// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"
	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilRevivalAcceptanceLetterRequest is returned when the RevivalAcceptanceLetterRequest is nil.
	ErrNilRevivalAcceptanceLetterRequest = errors.New("input RevivalAcceptanceLetterRequest is nil")

	// ErrRevivalAcceptanceLetterRequestTicketIDRequiredValidation is returned when the TicketID is required but not provided.
	ErrRevivalAcceptanceLetterRequestTicketIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TicketID is required", Path: "RevivalAcceptanceLetterRequest.TicketID", Type: "required"}

	// ErrRevivalAcceptanceLetterRequestPolicyNumberLengthValidation is the error returned when the length of the field is not exactly 13.
	ErrRevivalAcceptanceLetterRequestPolicyNumberLengthValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber length must be exactly 13", Path: "RevivalAcceptanceLetterRequest.PolicyNumber", Type: "length"}

	// ErrRevivalAcceptanceLetterRequestPolicyNumberRequiredValidation is returned when the PolicyNumber is required but not provided.
	ErrRevivalAcceptanceLetterRequestPolicyNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber is required", Path: "RevivalAcceptanceLetterRequest.PolicyNumber", Type: "required"}

	// ErrRevivalAcceptanceLetterRequestPolicyholderNameRequiredValidation is returned when the PolicyholderName is required but not provided.
	ErrRevivalAcceptanceLetterRequestPolicyholderNameRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyholderName is required", Path: "RevivalAcceptanceLetterRequest.PolicyholderName", Type: "required"}

	// ErrRevivalAcceptanceLetterRequestAddressRequiredValidation is returned when the Address is required but not provided.
	ErrRevivalAcceptanceLetterRequestAddressRequiredValidation = govaliderrors.ValidationError{Reason: "field Address is required", Path: "RevivalAcceptanceLetterRequest.Address", Type: "required"}

	// ErrRevivalAcceptanceLetterRequestOfficeIDRequiredValidation is returned when the OfficeID is required but not provided.
	ErrRevivalAcceptanceLetterRequestOfficeIDRequiredValidation = govaliderrors.ValidationError{Reason: "field OfficeID is required", Path: "RevivalAcceptanceLetterRequest.OfficeID", Type: "required"}
)

func ValidateRevivalAcceptanceLetterRequest(t *RevivalAcceptanceLetterRequest) error {
	if t == nil {
		return ErrNilRevivalAcceptanceLetterRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TicketID == "" {
		err := ErrRevivalAcceptanceLetterRequestTicketIDRequiredValidation
		err.Value = t.TicketID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.PolicyNumber) != 13 {
		err := ErrRevivalAcceptanceLetterRequestPolicyNumberLengthValidation
		err.Value = t.PolicyNumber
		errs = append(errs, err)
	}

	if t.PolicyNumber == "" {
		err := ErrRevivalAcceptanceLetterRequestPolicyNumberRequiredValidation
		err.Value = t.PolicyNumber
		errs = append(errs, err)
	}

	if t.PolicyholderName == "" {
		err := ErrRevivalAcceptanceLetterRequestPolicyholderNameRequiredValidation
		err.Value = t.PolicyholderName
		errs = append(errs, err)
	}

	if t.Address == "" {
		err := ErrRevivalAcceptanceLetterRequestAddressRequiredValidation
		err.Value = t.Address
		errs = append(errs, err)
	}

	if t.OfficeID == "" {
		err := ErrRevivalAcceptanceLetterRequestOfficeIDRequiredValidation
		err.Value = t.OfficeID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*RevivalAcceptanceLetterRequest)(nil)

func (t *RevivalAcceptanceLetterRequest) Validate() error {
	return ValidateRevivalAcceptanceLetterRequest(t)
}
