// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"
	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilCreateInstallmentRequest is returned when the CreateInstallmentRequest is nil.
	ErrNilCreateInstallmentRequest = errors.New("input CreateInstallmentRequest is nil")

	// ErrCreateInstallmentRequestTicketIDRequiredValidation is returned when the TicketID is required but not provided.
	ErrCreateInstallmentRequestTicketIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TicketID is required", Path: "CreateInstallmentRequest.TicketID", Type: "required"}

	// ErrCreateInstallmentRequestPolicyNumberLengthValidation is the error returned when the length of the field is not exactly 13.
	ErrCreateInstallmentRequestPolicyNumberLengthValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber length must be exactly 13", Path: "CreateInstallmentRequest.PolicyNumber", Type: "length"}

	// ErrCreateInstallmentRequestPolicyNumberRequiredValidation is returned when the PolicyNumber is required but not provided.
	ErrCreateInstallmentRequestPolicyNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber is required", Path: "CreateInstallmentRequest.PolicyNumber", Type: "required"}

	// ErrCreateInstallmentRequestInstallmentNumberRequiredValidation is returned when the InstallmentNumber is required but not provided.
	ErrCreateInstallmentRequestInstallmentNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field InstallmentNumber is required", Path: "CreateInstallmentRequest.InstallmentNumber", Type: "required"}

	// ErrCreateInstallmentRequestInstallmentAmountRequiredValidation is returned when the InstallmentAmount is required but not provided.
	ErrCreateInstallmentRequestInstallmentAmountRequiredValidation = govaliderrors.ValidationError{Reason: "field InstallmentAmount is required", Path: "CreateInstallmentRequest.InstallmentAmount", Type: "required"}

	// ErrCreateInstallmentRequestPaymentModeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrCreateInstallmentRequestPaymentModeOneofValidation = govaliderrors.ValidationError{Reason: "field PaymentMode must be one of CASH CHEQUE NEFT RTGS UPI CARD", Path: "CreateInstallmentRequest.PaymentMode", Type: "oneof"}

	// ErrCreateInstallmentRequestPaymentModeRequiredValidation is returned when the PaymentMode is required but not provided.
	ErrCreateInstallmentRequestPaymentModeRequiredValidation = govaliderrors.ValidationError{Reason: "field PaymentMode is required", Path: "CreateInstallmentRequest.PaymentMode", Type: "required"}

	// ErrCreateInstallmentRequestStatusOneofValidation is the error returned when the field is not one of the allowed values.
	ErrCreateInstallmentRequestStatusOneofValidation = govaliderrors.ValidationError{Reason: "field Status must be one of PENDING PAID DEFAULTED", Path: "CreateInstallmentRequest.Status", Type: "oneof"}

	// ErrCreateInstallmentRequestStatusRequiredValidation is returned when the Status is required but not provided.
	ErrCreateInstallmentRequestStatusRequiredValidation = govaliderrors.ValidationError{Reason: "field Status is required", Path: "CreateInstallmentRequest.Status", Type: "required"}
)

func ValidateCreateInstallmentRequest(t *CreateInstallmentRequest) error {
	if t == nil {
		return ErrNilCreateInstallmentRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TicketID == "" {
		err := ErrCreateInstallmentRequestTicketIDRequiredValidation
		err.Value = t.TicketID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.PolicyNumber) != 13 {
		err := ErrCreateInstallmentRequestPolicyNumberLengthValidation
		err.Value = t.PolicyNumber
		errs = append(errs, err)
	}

	if t.PolicyNumber == "" {
		err := ErrCreateInstallmentRequestPolicyNumberRequiredValidation
		err.Value = t.PolicyNumber
		errs = append(errs, err)
	}

	if t.InstallmentNumber == 0 {
		err := ErrCreateInstallmentRequestInstallmentNumberRequiredValidation
		err.Value = t.InstallmentNumber
		errs = append(errs, err)
	}

	if t.InstallmentAmount == 0.0 {
		err := ErrCreateInstallmentRequestInstallmentAmountRequiredValidation
		err.Value = t.InstallmentAmount
		errs = append(errs, err)
	}

	if !(t.PaymentMode == "CASH" || t.PaymentMode == "CHEQUE" || t.PaymentMode == "NEFT" || t.PaymentMode == "RTGS" || t.PaymentMode == "UPI" || t.PaymentMode == "CARD") {
		err := govaliderrors.ValidationError{Reason: "field PaymentMode must be one of CASH CHEQUE NEFT RTGS UPI CARD", Path: "CreateInstallmentRequest.PaymentMode", Type: "oneof"}
		err.Value = t.PaymentMode
		errs = append(errs, err)
	}
	if t.Interest == 0.0 {
		err := govaliderrors.ValidationError{Reason: "field Interest is required", Path: "CreateInstallmentRequest.Interest", Type: "required"}
		err.Value = t.Interest
		errs = append(errs, err)
	}
	if t.SGST == 0.0 {
		err := govaliderrors.ValidationError{Reason: "field SGST is required", Path: "CreateInstallmentRequest.SGST", Type: "required"}
		err.Value = t.SGST
		errs = append(errs, err)
	}
	if t.CGST == 0.0 {
		err := govaliderrors.ValidationError{Reason: "field CGST is required", Path: "CreateInstallmentRequest.CGST", Type: "required"}
		err.Value = t.CGST
		errs = append(errs, err)
	}
	if t.Rebate == 0.0 {
		err := govaliderrors.ValidationError{Reason: "field Rebate is required", Path: "CreateInstallmentRequest.Rebate", Type: "required"}
		err.Value = t.Rebate
		errs = append(errs, err)
	}
	if t.OfficeID == "" {
		err := govaliderrors.ValidationError{Reason: "field OfficeID is required", Path: "CreateInstallmentRequest.OfficeID", Type: "required"}
		err.Value = t.OfficeID
		errs = append(errs, err)
	}
	if t.UserID == "" {
		err := govaliderrors.ValidationError{Reason: "field UserID is required", Path: "CreateInstallmentRequest.UserID", Type: "required"}
		err.Value = t.UserID
		errs = append(errs, err)
	}
	if t.PaymentMode == "NEFT" && t.NEFTDetails == nil {
		err := govaliderrors.ValidationError{Reason: "field NEFTDetails is required for NEFT payment mode", Path: "CreateInstallmentRequest.NEFTDetails", Type: "required"}
		errs = append(errs, err)
	}

	if t.PaymentMode == "" {
		err := ErrCreateInstallmentRequestPaymentModeRequiredValidation
		err.Value = t.PaymentMode
		errs = append(errs, err)
	}

	if !(t.Status == "PENDING" || t.Status == "PAID" || t.Status == "DEFAULTED") {
		err := ErrCreateInstallmentRequestStatusOneofValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if t.Status == "" {
		err := ErrCreateInstallmentRequestStatusRequiredValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CreateInstallmentRequest)(nil)

func (t *CreateInstallmentRequest) Validate() error {
	return ValidateCreateInstallmentRequest(t)
}
