// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
)

var (
	// ErrNilDocumentSubmission is returned when the DocumentSubmission is nil.
	ErrNilDocumentSubmission = errors.New("input DocumentSubmission is nil")
)

func ValidateDocumentSubmission(t *DocumentSubmission) error {
	if t == nil {
		return ErrNilDocumentSubmission
	}
	return nil
}

var _ govalid.Validator = (*DocumentSubmission)(nil)

func (t *DocumentSubmission) Validate() error {
	return ValidateDocumentSubmission(t)
}
