// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
)

var (
	// ErrNilRevivalEligibilityInfo is returned when the RevivalEligibilityInfo is nil.
	ErrNilRevivalEligibilityInfo = errors.New("input RevivalEligibilityInfo is nil")
)

func ValidateRevivalEligibilityInfo(t *RevivalEligibilityInfo) error {
	if t == nil {
		return ErrNilRevivalEligibilityInfo
	}
	return nil
}

var _ govalid.Validator = (*RevivalEligibilityInfo)(nil)

func (t *RevivalEligibilityInfo) Validate() error {
	return ValidateRevivalEligibilityInfo(t)
}
