// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"
	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilPolicyNumberUri is returned when the PolicyNumberUri is nil.
	ErrNilPolicyNumberUri = errors.New("input PolicyNumberUri is nil")

	// ErrPolicyNumberUriPolicyNumberLengthValidation is the error returned when the length of the field is not exactly 13.
	ErrPolicyNumberUriPolicyNumberLengthValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber length must be exactly 13", Path: "PolicyNumberUri.PolicyNumber", Type: "length"}

	// ErrPolicyNumberUriPolicyNumberRequiredValidation is returned when the PolicyNumber is required but not provided.
	ErrPolicyNumberUriPolicyNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber is required", Path: "PolicyNumberUri.PolicyNumber", Type: "required"}
)

func ValidatePolicyNumberUri(t *PolicyNumberUri) error {
	if t == nil {
		return ErrNilPolicyNumberUri
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.PolicyNumber) != 13 {
		err := ErrPolicyNumberUriPolicyNumberLengthValidation
		err.Value = t.PolicyNumber
		errs = append(errs, err)
	}

	if t.PolicyNumber == "" {
		err := ErrPolicyNumberUriPolicyNumberRequiredValidation
		err.Value = t.PolicyNumber
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*PolicyNumberUri)(nil)

func (t *PolicyNumberUri) Validate() error {
	return ValidatePolicyNumberUri(t)
}
