// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"
	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilBatchFirstCollectionRequest is returned when the BatchFirstCollectionRequest is nil.
	ErrNilBatchFirstCollectionRequest = errors.New("input BatchFirstCollectionRequest is nil")

	// ErrBatchFirstCollectionRequestCollectionsMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrBatchFirstCollectionRequestCollectionsMinItemsValidation = govaliderrors.ValidationError{Reason: "field Collections must have a minimum of 1 items", Path: "BatchFirstCollectionRequest.Collections", Type: "minitems"}

	// ErrBatchFirstCollectionRequestCollectionsRequiredValidation is returned when the Collections is required but not provided.
	ErrBatchFirstCollectionRequestCollectionsRequiredValidation = govaliderrors.ValidationError{Reason: "field Collections is required", Path: "BatchFirstCollectionRequest.Collections", Type: "required"}

	// Deprecated: Use ErrBatchFirstCollectionRequestCollectionsiTicketIDRequiredValidation
	//
	// ErrBatchFirstCollectionRequestTicketIDRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrBatchFirstCollectionRequestTicketIDRequiredValidation = ErrBatchFirstCollectionRequestCollectionsiTicketIDRequiredValidation

	// ErrBatchFirstCollectionRequestCollectionsiTicketIDRequiredValidation is returned when the TicketID is required but not provided.
	ErrBatchFirstCollectionRequestCollectionsiTicketIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TicketID is required", Path: "BatchFirstCollectionRequest.Collections[i].TicketID", Type: "required"}

	// Deprecated: Use ErrBatchFirstCollectionRequestCollectionsiPolicyNumberLengthValidation
	//
	// ErrBatchFirstCollectionRequestPolicyNumberLengthValidation is deprecated and is kept for compatibility purpose.
	ErrBatchFirstCollectionRequestPolicyNumberLengthValidation = ErrBatchFirstCollectionRequestCollectionsiPolicyNumberLengthValidation

	// ErrBatchFirstCollectionRequestCollectionsiPolicyNumberLengthValidation is the error returned when the length of the field is not exactly 13.
	ErrBatchFirstCollectionRequestCollectionsiPolicyNumberLengthValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber length must be exactly 13", Path: "BatchFirstCollectionRequest.Collections[i].PolicyNumber", Type: "length"}

	// Deprecated: Use ErrBatchFirstCollectionRequestCollectionsiPolicyNumberRequiredValidation
	//
	// ErrBatchFirstCollectionRequestPolicyNumberRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrBatchFirstCollectionRequestPolicyNumberRequiredValidation = ErrBatchFirstCollectionRequestCollectionsiPolicyNumberRequiredValidation

	// ErrBatchFirstCollectionRequestCollectionsiPolicyNumberRequiredValidation is returned when the PolicyNumber is required but not provided.
	ErrBatchFirstCollectionRequestCollectionsiPolicyNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber is required", Path: "BatchFirstCollectionRequest.Collections[i].PolicyNumber", Type: "required"}

	// Deprecated: Use ErrBatchFirstCollectionRequestCollectionsiPaymentModeOneofValidation
	//
	// ErrBatchFirstCollectionRequestPaymentModeOneofValidation is deprecated and is kept for compatibility purpose.
	ErrBatchFirstCollectionRequestPaymentModeOneofValidation = ErrBatchFirstCollectionRequestCollectionsiPaymentModeOneofValidation

	// ErrBatchFirstCollectionRequestCollectionsiPaymentModeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrBatchFirstCollectionRequestCollectionsiPaymentModeOneofValidation = govaliderrors.ValidationError{Reason: "field PaymentMode must be one of CASH CHEQUE NEFT RTGS UPI CARD", Path: "BatchFirstCollectionRequest.Collections[i].PaymentMode", Type: "oneof"}

	// Deprecated: Use ErrBatchFirstCollectionRequestCollectionsiPaymentModeRequiredValidation
	//
	// ErrBatchFirstCollectionRequestPaymentModeRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrBatchFirstCollectionRequestPaymentModeRequiredValidation = ErrBatchFirstCollectionRequestCollectionsiPaymentModeRequiredValidation

	// ErrBatchFirstCollectionRequestCollectionsiPaymentModeRequiredValidation is returned when the PaymentMode is required but not provided.
	ErrBatchFirstCollectionRequestCollectionsiPaymentModeRequiredValidation = govaliderrors.ValidationError{Reason: "field PaymentMode is required", Path: "BatchFirstCollectionRequest.Collections[i].PaymentMode", Type: "required"}

	// Deprecated: Use ErrBatchFirstCollectionRequestCollectionsiPremiumAmountRequiredValidation
	//
	// ErrBatchFirstCollectionRequestPremiumAmountRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrBatchFirstCollectionRequestPremiumAmountRequiredValidation = ErrBatchFirstCollectionRequestCollectionsiPremiumAmountRequiredValidation

	// ErrBatchFirstCollectionRequestCollectionsiPremiumAmountRequiredValidation is returned when the PremiumAmount is required but not provided.
	ErrBatchFirstCollectionRequestCollectionsiPremiumAmountRequiredValidation = govaliderrors.ValidationError{Reason: "field PremiumAmount is required", Path: "BatchFirstCollectionRequest.Collections[i].PremiumAmount", Type: "required"}

	// Deprecated: Use ErrBatchFirstCollectionRequestCollectionsiInstallmentAmountRequiredValidation
	//
	// ErrBatchFirstCollectionRequestInstallmentAmountRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrBatchFirstCollectionRequestInstallmentAmountRequiredValidation = ErrBatchFirstCollectionRequestCollectionsiInstallmentAmountRequiredValidation

	// ErrBatchFirstCollectionRequestCollectionsiInstallmentAmountRequiredValidation is returned when the InstallmentAmount is required but not provided.
	ErrBatchFirstCollectionRequestCollectionsiInstallmentAmountRequiredValidation = govaliderrors.ValidationError{Reason: "field InstallmentAmount is required", Path: "BatchFirstCollectionRequest.Collections[i].InstallmentAmount", Type: "required"}

	// Deprecated: Use ErrBatchFirstCollectionRequestCollectionsiTotalAmountRequiredValidation
	//
	// ErrBatchFirstCollectionRequestTotalAmountRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrBatchFirstCollectionRequestTotalAmountRequiredValidation = ErrBatchFirstCollectionRequestCollectionsiTotalAmountRequiredValidation

	// ErrBatchFirstCollectionRequestCollectionsiTotalAmountRequiredValidation is returned when the TotalAmount is required but not provided.
	ErrBatchFirstCollectionRequestCollectionsiTotalAmountRequiredValidation = govaliderrors.ValidationError{Reason: "field TotalAmount is required", Path: "BatchFirstCollectionRequest.Collections[i].TotalAmount", Type: "required"}
)

func ValidateBatchFirstCollectionRequest(t *BatchFirstCollectionRequest) error {
	if t == nil {
		return ErrNilBatchFirstCollectionRequest
	}

	var errs govaliderrors.ValidationErrors

	if len(t.Collections) < 1 {
		err := ErrBatchFirstCollectionRequestCollectionsMinItemsValidation
		err.Value = t.Collections
		errs = append(errs, err)
	}

	if t.Collections == nil {
		err := ErrBatchFirstCollectionRequestCollectionsRequiredValidation
		err.Value = t.Collections
		errs = append(errs, err)
	}

	for i := range t.Collections {
		{
			t := t.Collections[i]

			if t.TicketID == "" {
				err := ErrBatchFirstCollectionRequestCollectionsiTicketIDRequiredValidation
				err.Value = t.TicketID
				errs = append(errs, err)
			}

			if utf8.RuneCountInString(t.PolicyNumber) != 13 {
				err := ErrBatchFirstCollectionRequestCollectionsiPolicyNumberLengthValidation
				err.Value = t.PolicyNumber
				errs = append(errs, err)
			}

			if t.PolicyNumber == "" {
				err := ErrBatchFirstCollectionRequestCollectionsiPolicyNumberRequiredValidation
				err.Value = t.PolicyNumber
				errs = append(errs, err)
			}

			if !(t.PaymentMode == "CASH" || t.PaymentMode == "CHEQUE" || t.PaymentMode == "NEFT" || t.PaymentMode == "RTGS" || t.PaymentMode == "UPI" || t.PaymentMode == "CARD") {
				err := ErrBatchFirstCollectionRequestCollectionsiPaymentModeOneofValidation
				err.Value = t.PaymentMode
				errs = append(errs, err)
			}

			if t.PaymentMode == "" {
				err := ErrBatchFirstCollectionRequestCollectionsiPaymentModeRequiredValidation
				err.Value = t.PaymentMode
				errs = append(errs, err)
			}

			if t.PremiumAmount == 0.0 {
				err := ErrBatchFirstCollectionRequestCollectionsiPremiumAmountRequiredValidation
				err.Value = t.PremiumAmount
				errs = append(errs, err)
			}

			if t.InstallmentAmount == 0.0 {
				err := ErrBatchFirstCollectionRequestCollectionsiInstallmentAmountRequiredValidation
				err.Value = t.InstallmentAmount
				errs = append(errs, err)
			}

			if t.TotalAmount == 0.0 {
				err := ErrBatchFirstCollectionRequestCollectionsiTotalAmountRequiredValidation
				err.Value = t.TotalAmount
				errs = append(errs, err)
			}

		}
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*BatchFirstCollectionRequest)(nil)

func (t *BatchFirstCollectionRequest) Validate() error {
	return ValidateBatchFirstCollectionRequest(t)
}
