// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilGetRevivalRequestUri is returned when the GetRevivalRequestUri is nil.
	ErrNilGetRevivalRequestUri = errors.New("input GetRevivalRequestUri is nil")

	// ErrGetRevivalRequestUriTicketIDRequiredValidation is returned when the TicketID is required but not provided.
	ErrGetRevivalRequestUriTicketIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TicketID is required", Path: "GetRevivalRequestUri.TicketID", Type: "required"}
)

func ValidateGetRevivalRequestUri(t *GetRevivalRequestUri) error {
	if t == nil {
		return ErrNilGetRevivalRequestUri
	}

	var errs govaliderrors.ValidationErrors

	if t.TicketID == "" {
		err := ErrGetRevivalRequestUriTicketIDRequiredValidation
		err.Value = t.TicketID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*GetRevivalRequestUri)(nil)

func (t *GetRevivalRequestUri) Validate() error {
	return ValidateGetRevivalRequestUri(t)
}
