// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilNEFTDetails is returned when the NEFTDetails is nil.
	ErrNilNEFTDetails = errors.New("input NEFTDetails is nil")

	// ErrNEFTDetailsURTNumberRequiredValidation is returned when the URTNumber is required but not provided.
	ErrNEFTDetailsURTNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field URTNumber is required", Path: "NEFTDetails.URTNumber", Type: "required"}

	// ErrNEFTDetailsBankRequiredValidation is returned when the Bank is required but not provided.
	ErrNEFTDetailsBankRequiredValidation = govaliderrors.ValidationError{Reason: "field Bank is required", Path: "NEFTDetails.Bank", Type: "required"}

	// ErrNEFTDetailsIFSCCodeRequiredValidation is returned when the IFSCCode is required but not provided.
	ErrNEFTDetailsIFSCCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field IFSCCode is required", Path: "NEFTDetails.IFSCCode", Type: "required"}
)

func ValidateNEFTDetails(t *NEFTDetails) error {
	if t == nil {
		return ErrNilNEFTDetails
	}

	var errs govaliderrors.ValidationErrors

	if t.URTNumber == "" {
		err := ErrNEFTDetailsURTNumberRequiredValidation
		err.Value = t.URTNumber
		errs = append(errs, err)
	}

	if t.Bank == "" {
		err := ErrNEFTDetailsBankRequiredValidation
		err.Value = t.Bank
		errs = append(errs, err)
	}

	if t.IFSCCode == "" {
		err := ErrNEFTDetailsIFSCCodeRequiredValidation
		err.Value = t.IFSCCode
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*NEFTDetails)(nil)

func (t *NEFTDetails) Validate() error {
	return ValidateNEFTDetails(t)
}
