// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilQualityCheckRequest is returned when the QualityCheckRequest is nil.
	ErrNilQualityCheckRequest = errors.New("input QualityCheckRequest is nil")

	// ErrQualityCheckRequestTicketIDRequiredValidation is returned when the TicketID is required but not provided.
	ErrQualityCheckRequestTicketIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TicketID is required", Path: "QualityCheckRequest.TicketID", Type: "required"}

	// ErrQualityCheckRequestQCCommentsRequiredValidation is returned when the QCComments is required but not provided.
	ErrQualityCheckRequestQCCommentsRequiredValidation = govaliderrors.ValidationError{Reason: "field QCComments is required", Path: "QualityCheckRequest.QCComments", Type: "required"}

	// ErrQualityCheckRequestQCPerformedByRequiredValidation is returned when the QCPerformedBy is required but not provided.
	ErrQualityCheckRequestQCPerformedByRequiredValidation = govaliderrors.ValidationError{Reason: "field QCPerformedBy is required", Path: "QualityCheckRequest.QCPerformedBy", Type: "required"}

	// ErrQualityCheckRequestOfficeIDRequiredValidation is returned when the OfficeID is required but not provided.
	ErrQualityCheckRequestOfficeIDRequiredValidation = govaliderrors.ValidationError{Reason: "field OfficeID is required", Path: "QualityCheckRequest.OfficeID", Type: "required"}
)

func ValidateQualityCheckRequest(t *QualityCheckRequest) error {
	if t == nil {
		return ErrNilQualityCheckRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TicketID == "" {
		err := ErrQualityCheckRequestTicketIDRequiredValidation
		err.Value = t.TicketID
		errs = append(errs, err)
	}

	if t.QCComments == "" {
		err := ErrQualityCheckRequestQCCommentsRequiredValidation
		err.Value = t.QCComments
		errs = append(errs, err)
	}

	if t.QCPerformedBy == "" {
		err := ErrQualityCheckRequestQCPerformedByRequiredValidation
		err.Value = t.QCPerformedBy
		errs = append(errs, err)
	}

	if t.OfficeID == "" {
		err := ErrQualityCheckRequestOfficeIDRequiredValidation
		err.Value = t.OfficeID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*QualityCheckRequest)(nil)

func (t *QualityCheckRequest) Validate() error {
	return ValidateQualityCheckRequest(t)
}
