// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilReceiveDocumentsRequest is returned when the ReceiveDocumentsRequest is nil.
	ErrNilReceiveDocumentsRequest = errors.New("input ReceiveDocumentsRequest is nil")

	// ErrReceiveDocumentsRequestTicketIDRequiredValidation is returned when the TicketID is required but not provided.
	ErrReceiveDocumentsRequestTicketIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TicketID is required", Path: "ReceiveDocumentsRequest.TicketID", Type: "required"}

	// ErrReceiveDocumentsRequestDocumentsReceivedRequiredValidation is returned when the DocumentsReceived is required but not provided.
	ErrReceiveDocumentsRequestDocumentsReceivedRequiredValidation = govaliderrors.ValidationError{Reason: "field DocumentsReceived is required", Path: "ReceiveDocumentsRequest.DocumentsReceived", Type: "required"}

	// ErrReceiveDocumentsRequestAllDocumentsReceivedRequiredValidation is returned when the AllDocumentsReceived is required but not provided.
	ErrReceiveDocumentsRequestAllDocumentsReceivedRequiredValidation = govaliderrors.ValidationError{Reason: "field AllDocumentsReceived is required", Path: "ReceiveDocumentsRequest.AllDocumentsReceived", Type: "required"}

	// ErrReceiveDocumentsRequestOfficeIDRequiredValidation is returned when the OfficeID is required but not provided.
	ErrReceiveDocumentsRequestOfficeIDRequiredValidation = govaliderrors.ValidationError{Reason: "field OfficeID is required", Path: "ReceiveDocumentsRequest.OfficeID", Type: "required"}
)

func ValidateReceiveDocumentsRequest(t *ReceiveDocumentsRequest) error {
	if t == nil {
		return ErrNilReceiveDocumentsRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TicketID == "" {
		err := ErrReceiveDocumentsRequestTicketIDRequiredValidation
		err.Value = t.TicketID
		errs = append(errs, err)
	}

	if t.DocumentsReceived == nil {
		err := ErrReceiveDocumentsRequestDocumentsReceivedRequiredValidation
		err.Value = t.DocumentsReceived
		errs = append(errs, err)
	}

	// AllDocumentsReceived is a boolean field that can be true or false
	// No validation needed - boolean fields are always initialized

	if t.OfficeID == "" {
		err := ErrReceiveDocumentsRequestOfficeIDRequiredValidation
		err.Value = t.OfficeID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ReceiveDocumentsRequest)(nil)

func (t *ReceiveDocumentsRequest) Validate() error {
	return ValidateReceiveDocumentsRequest(t)
}
