// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilChequeDetails is returned when the ChequeDetails is nil.
	ErrNilChequeDetails = errors.New("input ChequeDetails is nil")

	// ErrChequeDetailsChequeNumberRequiredValidation is returned when the ChequeNumber is required but not provided.
	ErrChequeDetailsChequeNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field ChequeNumber is required", Path: "ChequeDetails.ChequeNumber", Type: "required"}

	// ErrChequeDetailsBankNameRequiredValidation is returned when the BankName is required but not provided.
	ErrChequeDetailsBankNameRequiredValidation = govaliderrors.ValidationError{Reason: "field BankName is required", Path: "ChequeDetails.BankName", Type: "required"}

	// ErrChequeDetailsAmountRequiredValidation is returned when the Amount is required but not provided.
	ErrChequeDetailsAmountRequiredValidation = govaliderrors.ValidationError{Reason: "field Amount is required", Path: "ChequeDetails.Amount", Type: "required"}
)

func ValidateChequeDetails(t *ChequeDetails) error {
	if t == nil {
		return ErrNilChequeDetails
	}

	var errs govaliderrors.ValidationErrors

	if t.ChequeNumber == "" {
		err := ErrChequeDetailsChequeNumberRequiredValidation
		err.Value = t.ChequeNumber
		errs = append(errs, err)
	}

	if t.BankName == "" {
		err := ErrChequeDetailsBankNameRequiredValidation
		err.Value = t.BankName
		errs = append(errs, err)
	}

	if t.Amount == 0.0 {
		err := ErrChequeDetailsAmountRequiredValidation
		err.Value = t.Amount
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ChequeDetails)(nil)

func (t *ChequeDetails) Validate() error {
	return ValidateChequeDetails(t)
}
