// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"
	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilWithdrawalRequest is returned when the WithdrawalRequest is nil.
	ErrNilWithdrawalRequest = errors.New("input WithdrawalRequest is nil")

	// ErrWithdrawalRequestTicketIDRequiredValidation is returned when the TicketID is required but not provided.
	ErrWithdrawalRequestTicketIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TicketID is required", Path: "WithdrawalRequest.TicketID", Type: "required"}

	// ErrWithdrawalRequestPolicyNumberLengthValidation is the error returned when the length of the field is not exactly 13.
	ErrWithdrawalRequestPolicyNumberLengthValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber length must be exactly 13", Path: "WithdrawalRequest.PolicyNumber", Type: "length"}

	// ErrWithdrawalRequestPolicyNumberRequiredValidation is returned when the PolicyNumber is required but not provided.
	ErrWithdrawalRequestPolicyNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber is required", Path: "WithdrawalRequest.PolicyNumber", Type: "required"}

	// ErrWithdrawalRequestWithdrawalReasonRequiredValidation is returned when the WithdrawalReason is required but not provided.
	ErrWithdrawalRequestWithdrawalReasonRequiredValidation = govaliderrors.ValidationError{Reason: "field WithdrawalReason is required", Path: "WithdrawalRequest.WithdrawalReason", Type: "required"}

	// ErrWithdrawalRequestOfficeIDRequiredValidation is returned when the OfficeID is required but not provided.
	ErrWithdrawalRequestOfficeIDRequiredValidation = govaliderrors.ValidationError{Reason: "field OfficeID is required", Path: "WithdrawalRequest.OfficeID", Type: "required"}
)

func ValidateWithdrawalRequest(t *WithdrawalRequest) error {
	if t == nil {
		return ErrNilWithdrawalRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TicketID == "" {
		err := ErrWithdrawalRequestTicketIDRequiredValidation
		err.Value = t.TicketID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.PolicyNumber) != 13 {
		err := ErrWithdrawalRequestPolicyNumberLengthValidation
		err.Value = t.PolicyNumber
		errs = append(errs, err)
	}

	if t.PolicyNumber == "" {
		err := ErrWithdrawalRequestPolicyNumberRequiredValidation
		err.Value = t.PolicyNumber
		errs = append(errs, err)
	}

	if t.WithdrawalReason == "" {
		err := ErrWithdrawalRequestWithdrawalReasonRequiredValidation
		err.Value = t.WithdrawalReason
		errs = append(errs, err)
	}

	if t.OfficeID == "" {
		err := ErrWithdrawalRequestOfficeIDRequiredValidation
		err.Value = t.OfficeID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*WithdrawalRequest)(nil)

func (t *WithdrawalRequest) Validate() error {
	return ValidateWithdrawalRequest(t)
}
