// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilRevivalSummary is returned when the RevivalSummary is nil.
	ErrNilRevivalSummary = errors.New("input RevivalSummary is nil")

	// ErrRevivalSummaryRevivalAmountRequiredValidation is returned when the RevivalAmount is required but not provided.
	ErrRevivalSummaryRevivalAmountRequiredValidation = govaliderrors.ValidationError{Reason: "field RevivalAmount is required", Path: "RevivalSummary.RevivalAmount", Type: "required"}

	// ErrRevivalSummaryTotalInstallmentsRequiredValidation is returned when the TotalInstallments is required but not provided.
	ErrRevivalSummaryTotalInstallmentsRequiredValidation = govaliderrors.ValidationError{Reason: "field TotalInstallments is required", Path: "RevivalSummary.TotalInstallments", Type: "required"}

	// ErrRevivalSummaryInstallmentAmountRequiredValidation is returned when the InstallmentAmount is required but not provided.
	ErrRevivalSummaryInstallmentAmountRequiredValidation = govaliderrors.ValidationError{Reason: "field InstallmentAmount is required", Path: "RevivalSummary.InstallmentAmount", Type: "required"}
)

func ValidateRevivalSummary(t *RevivalSummary) error {
	if t == nil {
		return ErrNilRevivalSummary
	}

	var errs govaliderrors.ValidationErrors

	if t.RevivalAmount == 0.0 {
		err := ErrRevivalSummaryRevivalAmountRequiredValidation
		err.Value = t.RevivalAmount
		errs = append(errs, err)
	}

	if t.TotalInstallments == 0 {
		err := ErrRevivalSummaryTotalInstallmentsRequiredValidation
		err.Value = t.TotalInstallments
		errs = append(errs, err)
	}

	if t.InstallmentAmount == 0.0 {
		err := ErrRevivalSummaryInstallmentAmountRequiredValidation
		err.Value = t.InstallmentAmount
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*RevivalSummary)(nil)

func (t *RevivalSummary) Validate() error {
	return ValidateRevivalSummary(t)
}
