// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilDocumentReceipt is returned when the DocumentReceipt is nil.
	ErrNilDocumentReceipt = errors.New("input DocumentReceipt is nil")

	// ErrDocumentReceiptDocumentTypeRequiredValidation is returned when the DocumentType is required but not provided.
	ErrDocumentReceiptDocumentTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field DocumentType is required", Path: "DocumentReceipt.DocumentType", Type: "required"}

	// ErrDocumentReceiptDocumentNameRequiredValidation is returned when the DocumentName is required but not provided.
	ErrDocumentReceiptDocumentNameRequiredValidation = govaliderrors.ValidationError{Reason: "field DocumentName is required", Path: "DocumentReceipt.DocumentName", Type: "required"}

	// ErrDocumentReceiptReceivedByRequiredValidation is returned when the ReceivedBy is required but not provided.
	ErrDocumentReceiptReceivedByRequiredValidation = govaliderrors.ValidationError{Reason: "field ReceivedBy is required", Path: "DocumentReceipt.ReceivedBy", Type: "required"}
)

func ValidateDocumentReceipt(t *DocumentReceipt) error {
	if t == nil {
		return ErrNilDocumentReceipt
	}

	var errs govaliderrors.ValidationErrors

	if t.DocumentType == "" {
		err := ErrDocumentReceiptDocumentTypeRequiredValidation
		err.Value = t.DocumentType
		errs = append(errs, err)
	}

	if t.DocumentName == "" {
		err := ErrDocumentReceiptDocumentNameRequiredValidation
		err.Value = t.DocumentName
		errs = append(errs, err)
	}

	if t.ReceivedBy == "" {
		err := ErrDocumentReceiptReceivedByRequiredValidation
		err.Value = t.ReceivedBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*DocumentReceipt)(nil)

func (t *DocumentReceipt) Validate() error {
	return ValidateDocumentReceipt(t)
}
