// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilTicketIdUri is returned when the TicketIdUri is nil.
	ErrNilTicketIdUri = errors.New("input TicketIdUri is nil")

	// ErrTicketIdUriTicketIDRequiredValidation is returned when the TicketID is required but not provided.
	ErrTicketIdUriTicketIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TicketID is required", Path: "TicketIdUri.TicketID", Type: "required"}
)

func ValidateTicketIdUri(t *TicketIdUri) error {
	if t == nil {
		return ErrNilTicketIdUri
	}

	var errs govaliderrors.ValidationErrors

	if t.TicketID == "" {
		err := ErrTicketIdUriTicketIDRequiredValidation
		err.Value = t.TicketID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*TicketIdUri)(nil)

func (t *TicketIdUri) Validate() error {
	return ValidateTicketIdUri(t)
}
