// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"
	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilQuotationRequest is returned when the QuotationRequest is nil.
	ErrNilQuotationRequest = errors.New("input QuotationRequest is nil")

	// ErrQuotationRequestPolicyNumberLengthValidation is the error returned when the length of the field is not exactly 13.
	ErrQuotationRequestPolicyNumberLengthValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber length must be exactly 13", Path: "QuotationRequest.PolicyNumber", Type: "length"}

	// ErrQuotationRequestPolicyNumberRequiredValidation is returned when the PolicyNumber is required but not provided.
	ErrQuotationRequestPolicyNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber is required", Path: "QuotationRequest.PolicyNumber", Type: "required"}

	// ErrQuotationRequestInstallmentsRequiredValidation is returned when the Installments is required but not provided.
	ErrQuotationRequestInstallmentsRequiredValidation = govaliderrors.ValidationError{Reason: "field Installments is required", Path: "QuotationRequest.Installments", Type: "required"}
)

func ValidateQuotationRequest(t *QuotationRequest) error {
	if t == nil {
		return ErrNilQuotationRequest
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.PolicyNumber) != 13 {
		err := ErrQuotationRequestPolicyNumberLengthValidation
		err.Value = t.PolicyNumber
		errs = append(errs, err)
	}

	if t.PolicyNumber == "" {
		err := ErrQuotationRequestPolicyNumberRequiredValidation
		err.Value = t.PolicyNumber
		errs = append(errs, err)
	}

	if t.Installments == nil {
		err := ErrQuotationRequestInstallmentsRequiredValidation
		err.Value = t.Installments
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*QuotationRequest)(nil)

func (t *QuotationRequest) Validate() error {
	return ValidateQuotationRequest(t)
}
