// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilRevivalDetails is returned when the RevivalDetails is nil.
	ErrNilRevivalDetails = errors.New("input RevivalDetails is nil")

	// ErrRevivalDetailsInstallmentsRequiredValidation is returned when the Installments is required but not provided.
	ErrRevivalDetailsInstallmentsRequiredValidation = govaliderrors.ValidationError{Reason: "field Installments is required", Path: "RevivalDetails.Installments", Type: "required"}

	// ErrRevivalDetailsRevivalAmountRequiredValidation is returned when the RevivalAmount is required but not provided.
	ErrRevivalDetailsRevivalAmountRequiredValidation = govaliderrors.ValidationError{Reason: "field RevivalAmount is required", Path: "RevivalDetails.RevivalAmount", Type: "required"}

	// ErrRevivalDetailsInstallmentAmountRequiredValidation is returned when the InstallmentAmount is required but not provided.
	ErrRevivalDetailsInstallmentAmountRequiredValidation = govaliderrors.ValidationError{Reason: "field InstallmentAmount is required", Path: "RevivalDetails.InstallmentAmount", Type: "required"}

	// ErrRevivalDetailsTotalAmountDueRequiredValidation is returned when the TotalAmountDue is required but not provided.
	ErrRevivalDetailsTotalAmountDueRequiredValidation = govaliderrors.ValidationError{Reason: "field TotalAmountDue is required", Path: "RevivalDetails.TotalAmountDue", Type: "required"}

	// ErrRevivalDetailsLumpsumInstallmentsMustBeOneValidation is returned when revival_type is lumpsum but installments is greater than 1.
	ErrRevivalDetailsLumpsumInstallmentsMustBeOneValidation = govaliderrors.ValidationError{Reason: "installments must be 1 when revival_type is lumpsum", Path: "RevivalDetails.Installments", Type: "invalid"}
)

func ValidateRevivalDetails(t *RevivalDetails) error {
	if t == nil {
		return ErrNilRevivalDetails
	}

	var errs govaliderrors.ValidationErrors

	// Validate lumpsum revival type: installments must not exceed 1
	if t.RevivalType == "lumpsum" && t.Installments > 1 {
		err := ErrRevivalDetailsLumpsumInstallmentsMustBeOneValidation
		err.Value = t.Installments
		errs = append(errs, err)
	}

	// Validate SGST, CGST if present
	if t.TaxBreakdown.SGST < 0 {
		err := govaliderrors.ValidationError{Reason: "field SGST must be non-negative", Path: "RevivalDetails.TaxBreakdown.SGST", Type: "min"}
		err.Value = t.TaxBreakdown.SGST
		errs = append(errs, err)
	}
	if t.TaxBreakdown.CGST < 0 {
		err := govaliderrors.ValidationError{Reason: "field CGST must be non-negative", Path: "RevivalDetails.TaxBreakdown.CGST", Type: "min"}
		err.Value = t.TaxBreakdown.CGST
		errs = append(errs, err)
	}

	if t.RevivalType != "lumpsum" && t.Installments == 0 {
		err := ErrRevivalDetailsInstallmentsRequiredValidation
		err.Value = t.Installments
		errs = append(errs, err)
	}

	if t.RevivalAmount == 0.0 {
		err := ErrRevivalDetailsRevivalAmountRequiredValidation
		err.Value = t.RevivalAmount
		errs = append(errs, err)
	}

	if t.RevivalType != "lumpsum" && t.InstallmentAmount == 0.0 {
		err := ErrRevivalDetailsInstallmentAmountRequiredValidation
		err.Value = t.InstallmentAmount
		errs = append(errs, err)
	}

	if t.TotalAmountDue == 0.0 {
		err := ErrRevivalDetailsTotalAmountDueRequiredValidation
		err.Value = t.TotalAmountDue
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*RevivalDetails)(nil)

func (t *RevivalDetails) Validate() error {
	return ValidateRevivalDetails(t)
}
