// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilApprovalDecisionRequest is returned when the ApprovalDecisionRequest is nil.
	ErrNilApprovalDecisionRequest = errors.New("input ApprovalDecisionRequest is nil")

	// ErrApprovalDecisionRequestTicketIDRequiredValidation is returned when the TicketID is required but not provided.
	ErrApprovalDecisionRequestTicketIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TicketID is required", Path: "ApprovalDecisionRequest.TicketID", Type: "required"}

	// ErrApprovalDecisionRequestCommentsRequiredValidation is returned when the Comments is required but not provided.
	ErrApprovalDecisionRequestCommentsRequiredValidation = govaliderrors.ValidationError{Reason: "field Comments is required", Path: "ApprovalDecisionRequest.Comments", Type: "required"}

	// ErrApprovalDecisionRequestPerformedByRequiredValidation is returned when the PerformedBy is required but not provided.
	ErrApprovalDecisionRequestPerformedByRequiredValidation = govaliderrors.ValidationError{Reason: "field PerformedBy is required", Path: "ApprovalDecisionRequest.PerformedBy", Type: "required"}

	// ErrApprovalDecisionRequestOfficeIDRequiredValidation is returned when the OfficeID is required but not provided.
	ErrApprovalDecisionRequestOfficeIDRequiredValidation = govaliderrors.ValidationError{Reason: "field OfficeID is required", Path: "ApprovalDecisionRequest.OfficeID", Type: "required"}
)

func ValidateApprovalDecisionRequest(t *ApprovalDecisionRequest) error {
	if t == nil {
		return ErrNilApprovalDecisionRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TicketID == "" {
		err := ErrApprovalDecisionRequestTicketIDRequiredValidation
		err.Value = t.TicketID
		errs = append(errs, err)
	}

	if t.Comments == "" {
		err := ErrApprovalDecisionRequestCommentsRequiredValidation
		err.Value = t.Comments
		errs = append(errs, err)
	}

	if t.PerformedBy == "" {
		err := ErrApprovalDecisionRequestPerformedByRequiredValidation
		err.Value = t.PerformedBy
		errs = append(errs, err)
	}

	if t.OfficeID == "" {
		err := ErrApprovalDecisionRequestOfficeIDRequiredValidation
		err.Value = t.OfficeID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ApprovalDecisionRequest)(nil)

func (t *ApprovalDecisionRequest) Validate() error {
	return ValidateApprovalDecisionRequest(t)
}
