// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilApprovalRedirectRequest is returned when the ApprovalRedirectRequest is nil.
	ErrNilApprovalRedirectRequest = errors.New("input ApprovalRedirectRequest is nil")

	// ErrApprovalRedirectRequestTicketIDRequiredValidation is returned when the TicketID is required but not provided.
	ErrApprovalRedirectRequestTicketIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TicketID is required", Path: "ApprovalRedirectRequest.TicketID", Type: "required"}

	// ErrApprovalRedirectRequestRedirectToOneofValidation is the error returned when the field is not one of the allowed values.
	ErrApprovalRedirectRequestRedirectToOneofValidation = govaliderrors.ValidationError{Reason: "field RedirectTo must be one of DATA_ENTRY QC", Path: "ApprovalRedirectRequest.RedirectTo", Type: "oneof"}

	// ErrApprovalRedirectRequestRedirectToRequiredValidation is returned when the RedirectTo is required but not provided.
	ErrApprovalRedirectRequestRedirectToRequiredValidation = govaliderrors.ValidationError{Reason: "field RedirectTo is required", Path: "ApprovalRedirectRequest.RedirectTo", Type: "required"}

	// ErrApprovalRedirectRequestPerformedByRequiredValidation is returned when the PerformedBy is required but not provided.
	ErrApprovalRedirectRequestPerformedByRequiredValidation = govaliderrors.ValidationError{Reason: "field PerformedBy is required", Path: "ApprovalRedirectRequest.PerformedBy", Type: "required"}

	// ErrApprovalRedirectRequestOfficeIDRequiredValidation is returned when the OfficeID is required but not provided.
	ErrApprovalRedirectRequestOfficeIDRequiredValidation = govaliderrors.ValidationError{Reason: "field OfficeID is required", Path: "ApprovalRedirectRequest.OfficeID", Type: "required"}
)

func ValidateApprovalRedirectRequest(t *ApprovalRedirectRequest) error {
	if t == nil {
		return ErrNilApprovalRedirectRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TicketID == "" {
		err := ErrApprovalRedirectRequestTicketIDRequiredValidation
		err.Value = t.TicketID
		errs = append(errs, err)
	}

	if !(t.RedirectTo == "DATA_ENTRY" || t.RedirectTo == "QC") {
		err := ErrApprovalRedirectRequestRedirectToOneofValidation
		err.Value = t.RedirectTo
		errs = append(errs, err)
	}

	if t.RedirectTo == "" {
		err := ErrApprovalRedirectRequestRedirectToRequiredValidation
		err.Value = t.RedirectTo
		errs = append(errs, err)
	}

	if t.PerformedBy == "" {
		err := ErrApprovalRedirectRequestPerformedByRequiredValidation
		err.Value = t.PerformedBy
		errs = append(errs, err)
	}

	if t.OfficeID == "" {
		err := ErrApprovalRedirectRequestOfficeIDRequiredValidation
		err.Value = t.OfficeID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ApprovalRedirectRequest)(nil)

func (t *ApprovalRedirectRequest) Validate() error {
	return ValidateApprovalRedirectRequest(t)
}
