// Code generated by govalid; DO NOT EDIT.
package port

import (
	"errors"
	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilBatchInstallmentRequest is returned when the BatchInstallmentRequest is nil.
	ErrNilBatchInstallmentRequest = errors.New("input BatchInstallmentRequest is nil")

	// ErrBatchInstallmentRequestInstallmentsMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrBatchInstallmentRequestInstallmentsMinItemsValidation = govaliderrors.ValidationError{Reason: "field Installments must have a minimum of 1 items", Path: "BatchInstallmentRequest.Installments", Type: "minitems"}

	// ErrBatchInstallmentRequestInstallmentsRequiredValidation is returned when the Installments is required but not provided.
	ErrBatchInstallmentRequestInstallmentsRequiredValidation = govaliderrors.ValidationError{Reason: "field Installments is required", Path: "BatchInstallmentRequest.Installments", Type: "required"}

	// Deprecated: Use ErrBatchInstallmentRequestInstallmentsiTicketIDRequiredValidation
	//
	// ErrBatchInstallmentRequestTicketIDRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrBatchInstallmentRequestTicketIDRequiredValidation = ErrBatchInstallmentRequestInstallmentsiTicketIDRequiredValidation

	// ErrBatchInstallmentRequestInstallmentsiTicketIDRequiredValidation is returned when the TicketID is required but not provided.
	ErrBatchInstallmentRequestInstallmentsiTicketIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TicketID is required", Path: "BatchInstallmentRequest.Installments[i].TicketID", Type: "required"}

	// Deprecated: Use ErrBatchInstallmentRequestInstallmentsiPolicyNumberLengthValidation
	//
	// ErrBatchInstallmentRequestPolicyNumberLengthValidation is deprecated and is kept for compatibility purpose.
	ErrBatchInstallmentRequestPolicyNumberLengthValidation = ErrBatchInstallmentRequestInstallmentsiPolicyNumberLengthValidation

	// ErrBatchInstallmentRequestInstallmentsiPolicyNumberLengthValidation is the error returned when the length of the field is not exactly 13.
	ErrBatchInstallmentRequestInstallmentsiPolicyNumberLengthValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber length must be exactly 13", Path: "BatchInstallmentRequest.Installments[i].PolicyNumber", Type: "length"}

	// Deprecated: Use ErrBatchInstallmentRequestInstallmentsiPolicyNumberRequiredValidation
	//
	// ErrBatchInstallmentRequestPolicyNumberRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrBatchInstallmentRequestPolicyNumberRequiredValidation = ErrBatchInstallmentRequestInstallmentsiPolicyNumberRequiredValidation

	// ErrBatchInstallmentRequestInstallmentsiPolicyNumberRequiredValidation is returned when the PolicyNumber is required but not provided.
	ErrBatchInstallmentRequestInstallmentsiPolicyNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber is required", Path: "BatchInstallmentRequest.Installments[i].PolicyNumber", Type: "required"}

	// Deprecated: Use ErrBatchInstallmentRequestInstallmentsiInstallmentNumberRequiredValidation
	//
	// ErrBatchInstallmentRequestInstallmentNumberRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrBatchInstallmentRequestInstallmentNumberRequiredValidation = ErrBatchInstallmentRequestInstallmentsiInstallmentNumberRequiredValidation

	// ErrBatchInstallmentRequestInstallmentsiInstallmentNumberRequiredValidation is returned when the InstallmentNumber is required but not provided.
	ErrBatchInstallmentRequestInstallmentsiInstallmentNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field InstallmentNumber is required", Path: "BatchInstallmentRequest.Installments[i].InstallmentNumber", Type: "required"}

	// Deprecated: Use ErrBatchInstallmentRequestInstallmentsiInstallmentAmountRequiredValidation
	//
	// ErrBatchInstallmentRequestInstallmentAmountRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrBatchInstallmentRequestInstallmentAmountRequiredValidation = ErrBatchInstallmentRequestInstallmentsiInstallmentAmountRequiredValidation

	// ErrBatchInstallmentRequestInstallmentsiInstallmentAmountRequiredValidation is returned when the InstallmentAmount is required but not provided.
	ErrBatchInstallmentRequestInstallmentsiInstallmentAmountRequiredValidation = govaliderrors.ValidationError{Reason: "field InstallmentAmount is required", Path: "BatchInstallmentRequest.Installments[i].InstallmentAmount", Type: "required"}

	// Deprecated: Use ErrBatchInstallmentRequestInstallmentsiPaymentModeOneofValidation
	//
	// ErrBatchInstallmentRequestPaymentModeOneofValidation is deprecated and is kept for compatibility purpose.
	ErrBatchInstallmentRequestPaymentModeOneofValidation = ErrBatchInstallmentRequestInstallmentsiPaymentModeOneofValidation

	// ErrBatchInstallmentRequestInstallmentsiPaymentModeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrBatchInstallmentRequestInstallmentsiPaymentModeOneofValidation = govaliderrors.ValidationError{Reason: "field PaymentMode must be one of CASH CHEQUE NEFT RTGS UPI CARD", Path: "BatchInstallmentRequest.Installments[i].PaymentMode", Type: "oneof"}

	// Deprecated: Use ErrBatchInstallmentRequestInstallmentsiPaymentModeRequiredValidation
	//
	// ErrBatchInstallmentRequestPaymentModeRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrBatchInstallmentRequestPaymentModeRequiredValidation = ErrBatchInstallmentRequestInstallmentsiPaymentModeRequiredValidation

	// ErrBatchInstallmentRequestInstallmentsiPaymentModeRequiredValidation is returned when the PaymentMode is required but not provided.
	ErrBatchInstallmentRequestInstallmentsiPaymentModeRequiredValidation = govaliderrors.ValidationError{Reason: "field PaymentMode is required", Path: "BatchInstallmentRequest.Installments[i].PaymentMode", Type: "required"}

	// Deprecated: Use ErrBatchInstallmentRequestInstallmentsiStatusOneofValidation
	//
	// ErrBatchInstallmentRequestStatusOneofValidation is deprecated and is kept for compatibility purpose.
	ErrBatchInstallmentRequestStatusOneofValidation = ErrBatchInstallmentRequestInstallmentsiStatusOneofValidation

	// ErrBatchInstallmentRequestInstallmentsiStatusOneofValidation is the error returned when the field is not one of the allowed values.
	ErrBatchInstallmentRequestInstallmentsiStatusOneofValidation = govaliderrors.ValidationError{Reason: "field Status must be one of PENDING PAID DEFAULTED", Path: "BatchInstallmentRequest.Installments[i].Status", Type: "oneof"}

	// Deprecated: Use ErrBatchInstallmentRequestInstallmentsiStatusRequiredValidation
	//
	// ErrBatchInstallmentRequestStatusRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrBatchInstallmentRequestStatusRequiredValidation = ErrBatchInstallmentRequestInstallmentsiStatusRequiredValidation

	// ErrBatchInstallmentRequestInstallmentsiStatusRequiredValidation is returned when the Status is required but not provided.
	ErrBatchInstallmentRequestInstallmentsiStatusRequiredValidation = govaliderrors.ValidationError{Reason: "field Status is required", Path: "BatchInstallmentRequest.Installments[i].Status", Type: "required"}
)

func ValidateBatchInstallmentRequest(t *BatchInstallmentRequest) error {
	if t == nil {
		return ErrNilBatchInstallmentRequest
	}

	var errs govaliderrors.ValidationErrors

	if len(t.Installments) < 1 {
		err := ErrBatchInstallmentRequestInstallmentsMinItemsValidation
		err.Value = t.Installments
		errs = append(errs, err)
	}

	if t.Installments == nil {
		err := ErrBatchInstallmentRequestInstallmentsRequiredValidation
		err.Value = t.Installments
		errs = append(errs, err)
	}

	for i := range t.Installments {
		{
			t := t.Installments[i]

			if t.TicketID == "" {
				err := ErrBatchInstallmentRequestInstallmentsiTicketIDRequiredValidation
				err.Value = t.TicketID
				errs = append(errs, err)
			}

			if utf8.RuneCountInString(t.PolicyNumber) != 13 {
				err := ErrBatchInstallmentRequestInstallmentsiPolicyNumberLengthValidation
				err.Value = t.PolicyNumber
				errs = append(errs, err)
			}

			if t.PolicyNumber == "" {
				err := ErrBatchInstallmentRequestInstallmentsiPolicyNumberRequiredValidation
				err.Value = t.PolicyNumber
				errs = append(errs, err)
			}

			if t.InstallmentNumber == 0 {
				err := ErrBatchInstallmentRequestInstallmentsiInstallmentNumberRequiredValidation
				err.Value = t.InstallmentNumber
				errs = append(errs, err)
			}

			if t.InstallmentAmount == 0.0 {
				err := ErrBatchInstallmentRequestInstallmentsiInstallmentAmountRequiredValidation
				err.Value = t.InstallmentAmount
				errs = append(errs, err)
			}

			if !(t.PaymentMode == "CASH" || t.PaymentMode == "CHEQUE" || t.PaymentMode == "NEFT" || t.PaymentMode == "RTGS" || t.PaymentMode == "UPI" || t.PaymentMode == "CARD") {
				err := ErrBatchInstallmentRequestInstallmentsiPaymentModeOneofValidation
				err.Value = t.PaymentMode
				errs = append(errs, err)
			}

			if t.PaymentMode == "" {
				err := ErrBatchInstallmentRequestInstallmentsiPaymentModeRequiredValidation
				err.Value = t.PaymentMode
				errs = append(errs, err)
			}

			if !(t.Status == "PENDING" || t.Status == "PAID" || t.Status == "DEFAULTED") {
				err := ErrBatchInstallmentRequestInstallmentsiStatusOneofValidation
				err.Value = t.Status
				errs = append(errs, err)
			}

			if t.Status == "" {
				err := ErrBatchInstallmentRequestInstallmentsiStatusRequiredValidation
				err.Value = t.Status
				errs = append(errs, err)
			}

		}
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*BatchInstallmentRequest)(nil)

func (t *BatchInstallmentRequest) Validate() error {
	return ValidateBatchInstallmentRequest(t)
}
