// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilCreateOrderRequest is returned when the CreateOrderRequest is nil.
	ErrNilCreateOrderRequest = errors.New("input CreateOrderRequest is nil")

	// ErrCreateOrderRequestOrderItemsRequiredValidation is returned when the OrderItems is required but not provided.
	ErrCreateOrderRequestOrderItemsRequiredValidation = govaliderrors.ValidationError{Reason: "field OrderItems is required", Path: "CreateOrderRequest.OrderItems", Type: "required"}
)

func ValidateCreateOrderRequest(t *CreateOrderRequest) error {
	if t == nil {
		return ErrNilCreateOrderRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.OrderItems == nil {
		err := ErrCreateOrderRequestOrderItemsRequiredValidation
		err.Value = t.OrderItems
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CreateOrderRequest)(nil)

func (t *CreateOrderRequest) Validate() error {
	return ValidateCreateOrderRequest(t)
}
