// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilOrder is returned when the Order is nil.
	ErrNilOrder = errors.New("input Order is nil")

	// ErrOrderUserIDRequiredValidation is returned when the UserID is required but not provided.
	ErrOrderUserIDRequiredValidation = govaliderrors.ValidationError{Reason: "field UserID is required", Path: "Order.UserID", Type: "required"}

	// ErrOrderTotalAmountRequiredValidation is returned when the TotalAmount is required but not provided.
	ErrOrderTotalAmountRequiredValidation = govaliderrors.ValidationError{Reason: "field TotalAmount is required", Path: "Order.TotalAmount", Type: "required"}

	// ErrOrderShippingAddressRequiredValidation is returned when the ShippingAddress is required but not provided.
	ErrOrderShippingAddressRequiredValidation = govaliderrors.ValidationError{Reason: "field ShippingAddress is required", Path: "Order.ShippingAddress", Type: "required"}

	// ErrOrderPaymentMethodRequiredValidation is returned when the PaymentMethod is required but not provided.
	ErrOrderPaymentMethodRequiredValidation = govaliderrors.ValidationError{Reason: "field PaymentMethod is required", Path: "Order.PaymentMethod", Type: "required"}
)

func ValidateOrder(t *Order) error {
	if t == nil {
		return ErrNilOrder
	}

	var errs govaliderrors.ValidationErrors

	if t.UserID == 0 {
		err := ErrOrderUserIDRequiredValidation
		err.Value = t.UserID
		errs = append(errs, err)
	}

	if t.TotalAmount == 0.0 {
		err := ErrOrderTotalAmountRequiredValidation
		err.Value = t.TotalAmount
		errs = append(errs, err)
	}

	if t.ShippingAddress == "" {
		err := ErrOrderShippingAddressRequiredValidation
		err.Value = t.ShippingAddress
		errs = append(errs, err)
	}

	if t.PaymentMethod == "" {
		err := ErrOrderPaymentMethodRequiredValidation
		err.Value = t.PaymentMethod
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Order)(nil)

func (t *Order) Validate() error {
	return ValidateOrder(t)
}
