// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilGetFileReq is returned when the GetFileReq is nil.
	ErrNilGetFileReq = errors.New("input GetFileReq is nil")

	// ErrGetFileReqFileNameIDRequiredValidation is returned when the FileNameID is required but not provided.
	ErrGetFileReqFileNameIDRequiredValidation = govaliderrors.ValidationError{Reason: "field FileNameID is required", Path: "GetFileReq.FileNameID", Type: "required"}

	// ErrGetFileReqEmployeeIDRequiredValidation is returned when the EmployeeID is required but not provided.
	ErrGetFileReqEmployeeIDRequiredValidation = govaliderrors.ValidationError{Reason: "field EmployeeID is required", Path: "GetFileReq.EmployeeID", Type: "required"}
)

func ValidateGetFileReq(t *GetFileReq) error {
	if t == nil {
		return ErrNilGetFileReq
	}

	var errs govaliderrors.ValidationErrors

	if t.FileNameID == "" {
		err := ErrGetFileReqFileNameIDRequiredValidation
		err.Value = t.FileNameID
		errs = append(errs, err)
	}

	if t.EmployeeID == "" {
		err := ErrGetFileReqEmployeeIDRequiredValidation
		err.Value = t.EmployeeID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*GetFileReq)(nil)

func (t *GetFileReq) Validate() error {
	return ValidateGetFileReq(t)
}
