// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilApproveAwardsParams is returned when the ApproveAwardsParams is nil.
	ErrNilApproveAwardsParams = errors.New("input ApproveAwardsParams is nil")

	// ErrApproveAwardsParamsAwardIDsRequiredValidation is returned when the AwardIDs is required but not provided.
	ErrApproveAwardsParamsAwardIDsRequiredValidation = govaliderrors.ValidationError{Reason: "field AwardIDs is required", Path: "ApproveAwardsParams.AwardIDs", Type: "required"}

	// ErrApproveAwardsParamsApprovedByRequiredValidation is returned when the ApprovedBy is required but not provided.
	ErrApproveAwardsParamsApprovedByRequiredValidation = govaliderrors.ValidationError{Reason: "field ApprovedBy is required", Path: "ApproveAwardsParams.ApprovedBy", Type: "required"}

	// ErrApproveAwardsParamsApproveStatusRequiredValidation is returned when the ApproveStatus is required but not provided.
	ErrApproveAwardsParamsApproveStatusRequiredValidation = govaliderrors.ValidationError{Reason: "field ApproveStatus is required", Path: "ApproveAwardsParams.ApproveStatus", Type: "required"}

	// ErrApproveAwardsParamsApproverRemarksRequiredValidation is returned when the ApproverRemarks is required but not provided.
	ErrApproveAwardsParamsApproverRemarksRequiredValidation = govaliderrors.ValidationError{Reason: "field ApproverRemarks is required", Path: "ApproveAwardsParams.ApproverRemarks", Type: "required"}
)

func ValidateApproveAwardsParams(t *ApproveAwardsParams) error {
	if t == nil {
		return ErrNilApproveAwardsParams
	}

	var errs govaliderrors.ValidationErrors

	if t.AwardIDs == nil {
		err := ErrApproveAwardsParamsAwardIDsRequiredValidation
		err.Value = t.AwardIDs
		errs = append(errs, err)
	}

	if t.ApprovedBy == "" {
		err := ErrApproveAwardsParamsApprovedByRequiredValidation
		err.Value = t.ApprovedBy
		errs = append(errs, err)
	}

	if t.ApproveStatus == "" {
		err := ErrApproveAwardsParamsApproveStatusRequiredValidation
		err.Value = t.ApproveStatus
		errs = append(errs, err)
	}

	if t.ApproverRemarks == "" {
		err := ErrApproveAwardsParamsApproverRemarksRequiredValidation
		err.Value = t.ApproverRemarks
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ApproveAwardsParams)(nil)

func (t *ApproveAwardsParams) Validate() error {
	return ValidateApproveAwardsParams(t)
}
