// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"
	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilCreateUserRequest is returned when the CreateUserRequest is nil.
	ErrNilCreateUserRequest = errors.New("input CreateUserRequest is nil")

	// ErrCreateUserRequestNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrCreateUserRequestNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Name must have a maximum length of 100", Path: "CreateUserRequest.Name", Type: "maxlength"}

	// ErrCreateUserRequestNameMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrCreateUserRequestNameMinLengthValidation = govaliderrors.ValidationError{Reason: "field Name must have a minimum length of 1", Path: "CreateUserRequest.Name", Type: "minlength"}

	// ErrCreateUserRequestNameRequiredValidation is returned when the Name is required but not provided.
	ErrCreateUserRequestNameRequiredValidation = govaliderrors.ValidationError{Reason: "field Name is required", Path: "CreateUserRequest.Name", Type: "required"}

	// ErrCreateUserRequestEmailEmailValidation is the error returned when the field is not a valid email address.
	ErrCreateUserRequestEmailEmailValidation = govaliderrors.ValidationError{Reason: "field Email must be a valid email address", Path: "CreateUserRequest.Email", Type: "email"}

	// ErrCreateUserRequestEmailMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 255.
	ErrCreateUserRequestEmailMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Email must have a maximum length of 255", Path: "CreateUserRequest.Email", Type: "maxlength"}

	// ErrCreateUserRequestEmailRequiredValidation is returned when the Email is required but not provided.
	ErrCreateUserRequestEmailRequiredValidation = govaliderrors.ValidationError{Reason: "field Email is required", Path: "CreateUserRequest.Email", Type: "required"}
)

func ValidateCreateUserRequest(t *CreateUserRequest) error {
	if t == nil {
		return ErrNilCreateUserRequest
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.Name) > 100 {
		err := ErrCreateUserRequestNameMaxLengthValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.Name) < 1 {
		err := ErrCreateUserRequestNameMinLengthValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if t.Name == "" {
		err := ErrCreateUserRequestNameRequiredValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if !validationhelper.IsValidEmail(t.Email) {
		err := ErrCreateUserRequestEmailEmailValidation
		err.Value = t.Email
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.Email) > 255 {
		err := ErrCreateUserRequestEmailMaxLengthValidation
		err.Value = t.Email
		errs = append(errs, err)
	}

	if t.Email == "" {
		err := ErrCreateUserRequestEmailRequiredValidation
		err.Value = t.Email
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CreateUserRequest)(nil)

func (t *CreateUserRequest) Validate() error {
	return ValidateCreateUserRequest(t)
}
