// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilDetailTableGetParams is returned when the DetailTableGetParams is nil.
	ErrNilDetailTableGetParams = errors.New("input DetailTableGetParams is nil")

	// ErrDetailTableGetParamsEmpIDRequiredValidation is returned when the EmpID is required but not provided.
	ErrDetailTableGetParamsEmpIDRequiredValidation = govaliderrors.ValidationError{Reason: "field EmpID is required", Path: "DetailTableGetParams.EmpID", Type: "required"}
)

func ValidateDetailTableGetParams(t *DetailTableGetParams) error {
	if t == nil {
		return ErrNilDetailTableGetParams
	}

	var errs govaliderrors.ValidationErrors

	if t.EmpID == 0 {
		err := ErrDetailTableGetParamsEmpIDRequiredValidation
		err.Value = t.EmpID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*DetailTableGetParams)(nil)

func (t *DetailTableGetParams) Validate() error {
	return ValidateDetailTableGetParams(t)
}
