// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilMakerGetParams is returned when the MakerGetParams is nil.
	ErrNilMakerGetParams = errors.New("input MakerGetParams is nil")

	// ErrMakerGetParamsEmpIDRequiredValidation is returned when the EmpID is required but not provided.
	ErrMakerGetParamsEmpIDRequiredValidation = govaliderrors.ValidationError{Reason: "field EmpID is required", Path: "MakerGetParams.EmpID", Type: "required"}

	// ErrMakerGetParamsStatusOneofValidation is the error returned when the field is not one of the allowed values.
	ErrMakerGetParamsStatusOneofValidation = govaliderrors.ValidationError{Reason: "field Status must be one of Pending Forwarded Approved Rejected Cancelled UnApproved", Path: "MakerGetParams.Status", Type: "oneof"}
)

func ValidateMakerGetParams(t *MakerGetParams) error {
	if t == nil {
		return ErrNilMakerGetParams
	}

	var errs govaliderrors.ValidationErrors

	if t.EmpID == 0 {
		err := ErrMakerGetParamsEmpIDRequiredValidation
		err.Value = t.EmpID
		errs = append(errs, err)
	}

	if !(t.Status == "Pending" || t.Status == "Forwarded" || t.Status == "Approved" || t.Status == "Rejected" || t.Status == "Cancelled" || t.Status == "UnApproved") {
		err := ErrMakerGetParamsStatusOneofValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*MakerGetParams)(nil)

func (t *MakerGetParams) Validate() error {
	return ValidateMakerGetParams(t)
}
