// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"
	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilUpdateUserRequest is returned when the UpdateUserRequest is nil.
	ErrNilUpdateUserRequest = errors.New("input UpdateUserRequest is nil")

	// ErrUpdateUserRequestIDRequiredValidation is returned when the ID is required but not provided.
	ErrUpdateUserRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ID is required", Path: "UpdateUserRequest.ID", Type: "required"}

	// ErrUpdateUserRequestNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrUpdateUserRequestNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Name must have a maximum length of 100", Path: "UpdateUserRequest.Name", Type: "maxlength"}

	// ErrUpdateUserRequestNameMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrUpdateUserRequestNameMinLengthValidation = govaliderrors.ValidationError{Reason: "field Name must have a minimum length of 1", Path: "UpdateUserRequest.Name", Type: "minlength"}

	// ErrUpdateUserRequestEmailEmailValidation is the error returned when the field is not a valid email address.
	ErrUpdateUserRequestEmailEmailValidation = govaliderrors.ValidationError{Reason: "field Email must be a valid email address", Path: "UpdateUserRequest.Email", Type: "email"}

	// ErrUpdateUserRequestEmailMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 255.
	ErrUpdateUserRequestEmailMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Email must have a maximum length of 255", Path: "UpdateUserRequest.Email", Type: "maxlength"}
)

func ValidateUpdateUserRequest(t *UpdateUserRequest) error {
	if t == nil {
		return ErrNilUpdateUserRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ID == 0 {
		err := ErrUpdateUserRequestIDRequiredValidation
		err.Value = t.ID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.Name) > 100 {
		err := ErrUpdateUserRequestNameMaxLengthValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.Name) < 1 {
		err := ErrUpdateUserRequestNameMinLengthValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if !validationhelper.IsValidEmail(t.Email) {
		err := ErrUpdateUserRequestEmailEmailValidation
		err.Value = t.Email
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.Email) > 255 {
		err := ErrUpdateUserRequestEmailMaxLengthValidation
		err.Value = t.Email
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*UpdateUserRequest)(nil)

func (t *UpdateUserRequest) Validate() error {
	return ValidateUpdateUserRequest(t)
}
