// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilCustomerGetInput is returned when the CustomerGetInput is nil.
	ErrNilCustomerGetInput = errors.New("input CustomerGetInput is nil")

	// ErrCustomerGetInputCustomerIDRequiredValidation is returned when the CustomerID is required but not provided.
	ErrCustomerGetInputCustomerIDRequiredValidation = govaliderrors.ValidationError{Reason: "field CustomerID is required", Path: "CustomerGetInput.CustomerID", Type: "required"}
)

func ValidateCustomerGetInput(t *CustomerGetInput) error {
	if t == nil {
		return ErrNilCustomerGetInput
	}

	var errs govaliderrors.ValidationErrors

	if t.CustomerID == "" {
		err := ErrCustomerGetInputCustomerIDRequiredValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CustomerGetInput)(nil)

func (t *CustomerGetInput) Validate() error {
	return ValidateCustomerGetInput(t)
}
