// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilAddressInput is returned when the AddressInput is nil.
	ErrNilAddressInput = errors.New("input AddressInput is nil")

	// ErrAddressInputAddressTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrAddressInputAddressTypeOneofValidation = govaliderrors.ValidationError{Reason: "field AddressType must be one of COMMUNICATION PERMANENT EMPLOYER", Path: "AddressInput.AddressType", Type: "oneof"}

	// ErrAddressInputAddressTypeRequiredValidation is returned when the AddressType is required but not provided.
	ErrAddressInputAddressTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field AddressType is required", Path: "AddressInput.AddressType", Type: "required"}

	// ErrAddressInputLine1MaxLengthValidation is the error returned when the length of the field exceeds the maximum of 200.
	ErrAddressInputLine1MaxLengthValidation = govaliderrors.ValidationError{Reason: "field Line1 must have a maximum length of 200", Path: "AddressInput.Line1", Type: "maxlength"}

	// ErrAddressInputLine1MinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrAddressInputLine1MinLengthValidation = govaliderrors.ValidationError{Reason: "field Line1 must have a minimum length of 1", Path: "AddressInput.Line1", Type: "minlength"}

	// ErrAddressInputLine1RequiredValidation is returned when the Line1 is required but not provided.
	ErrAddressInputLine1RequiredValidation = govaliderrors.ValidationError{Reason: "field Line1 is required", Path: "AddressInput.Line1", Type: "required"}

	// ErrAddressInputLine2MaxLengthValidation is the error returned when the length of the field exceeds the maximum of 200.
	ErrAddressInputLine2MaxLengthValidation = govaliderrors.ValidationError{Reason: "field Line2 must have a maximum length of 200", Path: "AddressInput.Line2", Type: "maxlength"}

	// ErrAddressInputVillageMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrAddressInputVillageMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Village must have a maximum length of 100", Path: "AddressInput.Village", Type: "maxlength"}

	// ErrAddressInputTalukaMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrAddressInputTalukaMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Taluka must have a maximum length of 100", Path: "AddressInput.Taluka", Type: "maxlength"}

	// ErrAddressInputMandalMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrAddressInputMandalMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Mandal must have a maximum length of 100", Path: "AddressInput.Mandal", Type: "maxlength"}

	// ErrAddressInputCityMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrAddressInputCityMaxLengthValidation = govaliderrors.ValidationError{Reason: "field City must have a maximum length of 100", Path: "AddressInput.City", Type: "maxlength"}

	// ErrAddressInputCityMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrAddressInputCityMinLengthValidation = govaliderrors.ValidationError{Reason: "field City must have a minimum length of 1", Path: "AddressInput.City", Type: "minlength"}

	// ErrAddressInputCityRequiredValidation is returned when the City is required but not provided.
	ErrAddressInputCityRequiredValidation = govaliderrors.ValidationError{Reason: "field City is required", Path: "AddressInput.City", Type: "required"}

	// ErrAddressInputDistrictMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrAddressInputDistrictMaxLengthValidation = govaliderrors.ValidationError{Reason: "field District must have a maximum length of 100", Path: "AddressInput.District", Type: "maxlength"}

	// ErrAddressInputDistrictMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrAddressInputDistrictMinLengthValidation = govaliderrors.ValidationError{Reason: "field District must have a minimum length of 1", Path: "AddressInput.District", Type: "minlength"}

	// ErrAddressInputDistrictRequiredValidation is returned when the District is required but not provided.
	ErrAddressInputDistrictRequiredValidation = govaliderrors.ValidationError{Reason: "field District is required", Path: "AddressInput.District", Type: "required"}

	// ErrAddressInputStateMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrAddressInputStateMaxLengthValidation = govaliderrors.ValidationError{Reason: "field State must have a maximum length of 50", Path: "AddressInput.State", Type: "maxlength"}

	// ErrAddressInputStateMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrAddressInputStateMinLengthValidation = govaliderrors.ValidationError{Reason: "field State must have a minimum length of 1", Path: "AddressInput.State", Type: "minlength"}

	// ErrAddressInputStateRequiredValidation is returned when the State is required but not provided.
	ErrAddressInputStateRequiredValidation = govaliderrors.ValidationError{Reason: "field State is required", Path: "AddressInput.State", Type: "required"}

	// ErrAddressInputCountryMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrAddressInputCountryMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Country must have a maximum length of 50", Path: "AddressInput.Country", Type: "maxlength"}

	// ErrAddressInputCountryMinLengthValidation is the error returned when the length of the field is less than the minimum of 2.
	ErrAddressInputCountryMinLengthValidation = govaliderrors.ValidationError{Reason: "field Country must have a minimum length of 2", Path: "AddressInput.Country", Type: "minlength"}

	// ErrAddressInputCountryRequiredValidation is returned when the Country is required but not provided.
	ErrAddressInputCountryRequiredValidation = govaliderrors.ValidationError{Reason: "field Country is required", Path: "AddressInput.Country", Type: "required"}

	// ErrAddressInputPinCodeLengthValidation is the error returned when the length of the field is not exactly 6.
	ErrAddressInputPinCodeLengthValidation = govaliderrors.ValidationError{Reason: "field PinCode length must be exactly 6", Path: "AddressInput.PinCode", Type: "length"}

	// ErrAddressInputPinCodeRequiredValidation is returned when the PinCode is required but not provided.
	ErrAddressInputPinCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field PinCode is required", Path: "AddressInput.PinCode", Type: "required"}

	// ErrAddressInputChangeReasonMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 500.
	ErrAddressInputChangeReasonMaxLengthValidation = govaliderrors.ValidationError{Reason: "field ChangeReason must have a maximum length of 500", Path: "AddressInput.ChangeReason", Type: "maxlength"}

	// ErrAddressInputApprovedByMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrAddressInputApprovedByMaxLengthValidation = govaliderrors.ValidationError{Reason: "field ApprovedBy must have a maximum length of 100", Path: "AddressInput.ApprovedBy", Type: "maxlength"}
)

func ValidateAddressInput(t *AddressInput) error {
	if t == nil {
		return ErrNilAddressInput
	}

	var errs govaliderrors.ValidationErrors

	if !(t.AddressType == "COMMUNICATION" || t.AddressType == "PERMANENT" || t.AddressType == "EMPLOYER") {
		err := ErrAddressInputAddressTypeOneofValidation
		err.Value = t.AddressType
		errs = append(errs, err)
	}

	if t.AddressType == "" {
		err := ErrAddressInputAddressTypeRequiredValidation
		err.Value = t.AddressType
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.Line1) > 200 {
		err := ErrAddressInputLine1MaxLengthValidation
		err.Value = t.Line1
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.Line1) < 1 {
		err := ErrAddressInputLine1MinLengthValidation
		err.Value = t.Line1
		errs = append(errs, err)
	}

	if t.Line1 == "" {
		err := ErrAddressInputLine1RequiredValidation
		err.Value = t.Line1
		errs = append(errs, err)
	}

	if t.Line2 != "" && utf8.RuneCountInString(t.Line2) > 200 {
		err := ErrAddressInputLine2MaxLengthValidation
		err.Value = t.Line2
		errs = append(errs, err)
	}

	if t.Village != "" && utf8.RuneCountInString(t.Village) > 100 {
		err := ErrAddressInputVillageMaxLengthValidation
		err.Value = t.Village
		errs = append(errs, err)
	}

	if t.Taluka != "" && utf8.RuneCountInString(t.Taluka) > 100 {
		err := ErrAddressInputTalukaMaxLengthValidation
		err.Value = t.Taluka
		errs = append(errs, err)
	}

	if t.Mandal != "" && utf8.RuneCountInString(t.Mandal) > 100 {
		err := ErrAddressInputMandalMaxLengthValidation
		err.Value = t.Mandal
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.City) > 100 {
		err := ErrAddressInputCityMaxLengthValidation
		err.Value = t.City
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.City) < 1 {
		err := ErrAddressInputCityMinLengthValidation
		err.Value = t.City
		errs = append(errs, err)
	}

	if t.City == "" {
		err := ErrAddressInputCityRequiredValidation
		err.Value = t.City
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.District) > 100 {
		err := ErrAddressInputDistrictMaxLengthValidation
		err.Value = t.District
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.District) < 1 {
		err := ErrAddressInputDistrictMinLengthValidation
		err.Value = t.District
		errs = append(errs, err)
	}

	if t.District == "" {
		err := ErrAddressInputDistrictRequiredValidation
		err.Value = t.District
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.State) > 50 {
		err := ErrAddressInputStateMaxLengthValidation
		err.Value = t.State
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.State) < 1 {
		err := ErrAddressInputStateMinLengthValidation
		err.Value = t.State
		errs = append(errs, err)
	}

	if t.State == "" {
		err := ErrAddressInputStateRequiredValidation
		err.Value = t.State
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.Country) > 50 {
		err := ErrAddressInputCountryMaxLengthValidation
		err.Value = t.Country
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.Country) < 2 {
		err := ErrAddressInputCountryMinLengthValidation
		err.Value = t.Country
		errs = append(errs, err)
	}

	if t.Country == "" {
		err := ErrAddressInputCountryRequiredValidation
		err.Value = t.Country
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.PinCode) != 6 {
		err := ErrAddressInputPinCodeLengthValidation
		err.Value = t.PinCode
		errs = append(errs, err)
	}

	if t.PinCode == "" {
		err := ErrAddressInputPinCodeRequiredValidation
		err.Value = t.PinCode
		errs = append(errs, err)
	}

	if t.ChangeReason != "" && utf8.RuneCountInString(t.ChangeReason) > 500 {
		err := ErrAddressInputChangeReasonMaxLengthValidation
		err.Value = t.ChangeReason
		errs = append(errs, err)
	}

	if t.ApprovedBy != "" && utf8.RuneCountInString(t.ApprovedBy) > 100 {
		err := ErrAddressInputApprovedByMaxLengthValidation
		err.Value = t.ApprovedBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*AddressInput)(nil)

func (t *AddressInput) Validate() error {
	return ValidateAddressInput(t)
}
