// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilGetTermOrPremiumCeasingAgeRequest is returned when the GetTermOrPremiumCeasingAgeRequest is nil.
	ErrNilGetTermOrPremiumCeasingAgeRequest = errors.New("input GetTermOrPremiumCeasingAgeRequest is nil")

	// ErrGetTermOrPremiumCeasingAgeRequestProductCodeRequiredValidation is returned when the ProductCode is required but not provided.
	ErrGetTermOrPremiumCeasingAgeRequestProductCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field ProductCode is required", Path: "GetTermOrPremiumCeasingAgeRequest.ProductCode", Type: "required"}

	// ErrGetTermOrPremiumCeasingAgeRequestDateOfBirthRequiredValidation is returned when the DateOfBirth is required but not provided.
	ErrGetTermOrPremiumCeasingAgeRequestDateOfBirthRequiredValidation = govaliderrors.ValidationError{Reason: "field DateOfBirth is required", Path: "GetTermOrPremiumCeasingAgeRequest.DateOfBirth", Type: "required"}

	// ErrGetTermOrPremiumCeasingAgeRequestDateOfCalculationRequiredValidation is returned when the DateOfCalculation is required but not provided.
	ErrGetTermOrPremiumCeasingAgeRequestDateOfCalculationRequiredValidation = govaliderrors.ValidationError{Reason: "field DateOfCalculation is required", Path: "GetTermOrPremiumCeasingAgeRequest.DateOfCalculation", Type: "required"}
)

func ValidateGetTermOrPremiumCeasingAgeRequest(t *GetTermOrPremiumCeasingAgeRequest) error {
	if t == nil {
		return ErrNilGetTermOrPremiumCeasingAgeRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProductCode == "" {
		err := ErrGetTermOrPremiumCeasingAgeRequestProductCodeRequiredValidation
		err.Value = t.ProductCode
		errs = append(errs, err)
	}

	if t.DateOfBirth == "" {
		err := ErrGetTermOrPremiumCeasingAgeRequestDateOfBirthRequiredValidation
		err.Value = t.DateOfBirth
		errs = append(errs, err)
	}

	if t.DateOfCalculation == "" {
		err := ErrGetTermOrPremiumCeasingAgeRequestDateOfCalculationRequiredValidation
		err.Value = t.DateOfCalculation
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*GetTermOrPremiumCeasingAgeRequest)(nil)

func (t *GetTermOrPremiumCeasingAgeRequest) Validate() error {
	return ValidateGetTermOrPremiumCeasingAgeRequest(t)
}
