// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilMissingDocumentsQuery is returned when the MissingDocumentsQuery is nil.
	ErrNilMissingDocumentsQuery = errors.New("input MissingDocumentsQuery is nil")

	// ErrMissingDocumentsQueryProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrMissingDocumentsQueryProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "MissingDocumentsQuery.ProposalID", Type: "required"}

	// ErrMissingDocumentsQueryStageOneofValidation is the error returned when the field is not one of the allowed values.
	ErrMissingDocumentsQueryStageOneofValidation = govaliderrors.ValidationError{Reason: "field Stage must be one of QC_REVIEW APPROVAL", Path: "MissingDocumentsQuery.Stage", Type: "oneof"}

	// ErrMissingDocumentsQueryStatusOneofValidation is the error returned when the field is not one of the allowed values.
	ErrMissingDocumentsQueryStatusOneofValidation = govaliderrors.ValidationError{Reason: "field Status must be one of PENDING UPLOADED WAIVED", Path: "MissingDocumentsQuery.Status", Type: "oneof"}
)

func ValidateMissingDocumentsQuery(t *MissingDocumentsQuery) error {
	if t == nil {
		return ErrNilMissingDocumentsQuery
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrMissingDocumentsQueryProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if t.Stage != "" && !(t.Stage == "QC_REVIEW" || t.Stage == "APPROVAL") {
		err := ErrMissingDocumentsQueryStageOneofValidation
		err.Value = t.Stage
		errs = append(errs, err)
	}

	if t.Status != "" && !(t.Status == "PENDING" || t.Status == "UPLOADED" || t.Status == "WAIVED") {
		err := ErrMissingDocumentsQueryStatusOneofValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*MissingDocumentsQuery)(nil)

func (t *MissingDocumentsQuery) Validate() error {
	return ValidateMissingDocumentsQuery(t)
}
