// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilDocumentUploadRequest is returned when the DocumentUploadRequest is nil.
	ErrNilDocumentUploadRequest = errors.New("input DocumentUploadRequest is nil")

	// ErrDocumentUploadRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrDocumentUploadRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "DocumentUploadRequest.ProposalID", Type: "required"}

	// ErrDocumentUploadRequestDocumentTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrDocumentUploadRequestDocumentTypeOneofValidation = govaliderrors.ValidationError{Reason: "field DocumentType must be one of PROPOSAL_FORM DOB_PROOF ADDRESS_PROOF PHOTO_ID MEDICAL_REPORT PAYMENT_COPY HEALTH_DECLARATION PHOTO INCOME_PROOF EMPLOYMENT_PROOF OTHER", Path: "DocumentUploadRequest.DocumentType", Type: "oneof"}

	// ErrDocumentUploadRequestDocumentTypeRequiredValidation is returned when the DocumentType is required but not provided.
	ErrDocumentUploadRequestDocumentTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field DocumentType is required", Path: "DocumentUploadRequest.DocumentType", Type: "required"}

	// ErrDocumentUploadRequestFileNameRequiredValidation is returned when the FileName is required but not provided.
	ErrDocumentUploadRequestFileNameRequiredValidation = govaliderrors.ValidationError{Reason: "field FileName is required", Path: "DocumentUploadRequest.FileName", Type: "required"}

	// ErrDocumentUploadRequestMimeTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrDocumentUploadRequestMimeTypeOneofValidation = govaliderrors.ValidationError{Reason: "field MimeType must be one of application/pdf image/jpeg image/png image/jpg", Path: "DocumentUploadRequest.MimeType", Type: "oneof"}

	// ErrDocumentUploadRequestMimeTypeRequiredValidation is returned when the MimeType is required but not provided.
	ErrDocumentUploadRequestMimeTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field MimeType is required", Path: "DocumentUploadRequest.MimeType", Type: "required"}

	// ErrDocumentUploadRequestFileSizeGTValidation is the error returned when the value of the field is less than the 0.
	ErrDocumentUploadRequestFileSizeGTValidation = govaliderrors.ValidationError{Reason: "field FileSize must be greater than 0", Path: "DocumentUploadRequest.FileSize", Type: "gt"}

	// ErrDocumentUploadRequestFileSizeRequiredValidation is returned when the FileSize is required but not provided.
	ErrDocumentUploadRequestFileSizeRequiredValidation = govaliderrors.ValidationError{Reason: "field FileSize is required", Path: "DocumentUploadRequest.FileSize", Type: "required"}

	// ErrDocumentUploadRequestDocumentDateRequiredValidation is returned when the DocumentDate is required but not provided.
	ErrDocumentUploadRequestDocumentDateRequiredValidation = govaliderrors.ValidationError{Reason: "field DocumentDate is required", Path: "DocumentUploadRequest.DocumentDate", Type: "required"}

	// ErrDocumentUploadRequestUploadedByRequiredValidation is returned when the UploadedBy is required but not provided.
	ErrDocumentUploadRequestUploadedByRequiredValidation = govaliderrors.ValidationError{Reason: "field UploadedBy is required", Path: "DocumentUploadRequest.UploadedBy", Type: "required"}
)

func ValidateDocumentUploadRequest(t *DocumentUploadRequest) error {
	if t == nil {
		return ErrNilDocumentUploadRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrDocumentUploadRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if !(t.DocumentType == "PROPOSAL_FORM" || t.DocumentType == "DOB_PROOF" || t.DocumentType == "ADDRESS_PROOF" || t.DocumentType == "PHOTO_ID" || t.DocumentType == "MEDICAL_REPORT" || t.DocumentType == "PAYMENT_COPY" || t.DocumentType == "HEALTH_DECLARATION" || t.DocumentType == "PHOTO" || t.DocumentType == "INCOME_PROOF" || t.DocumentType == "EMPLOYMENT_PROOF" || t.DocumentType == "OTHER") {
		err := ErrDocumentUploadRequestDocumentTypeOneofValidation
		err.Value = t.DocumentType
		errs = append(errs, err)
	}

	if t.DocumentType == "" {
		err := ErrDocumentUploadRequestDocumentTypeRequiredValidation
		err.Value = t.DocumentType
		errs = append(errs, err)
	}

	if t.FileName == "" {
		err := ErrDocumentUploadRequestFileNameRequiredValidation
		err.Value = t.FileName
		errs = append(errs, err)
	}

	if !(t.MimeType == "application/pdf" || t.MimeType == "image/jpeg" || t.MimeType == "image/png" || t.MimeType == "image/jpg") {
		err := ErrDocumentUploadRequestMimeTypeOneofValidation
		err.Value = t.MimeType
		errs = append(errs, err)
	}

	if t.MimeType == "" {
		err := ErrDocumentUploadRequestMimeTypeRequiredValidation
		err.Value = t.MimeType
		errs = append(errs, err)
	}

	if !(t.FileSize > 0) {
		err := ErrDocumentUploadRequestFileSizeGTValidation
		err.Value = t.FileSize
		errs = append(errs, err)
	}

	if t.FileSize == 0 {
		err := ErrDocumentUploadRequestFileSizeRequiredValidation
		err.Value = t.FileSize
		errs = append(errs, err)
	}

	if t.DocumentDate == "" {
		err := ErrDocumentUploadRequestDocumentDateRequiredValidation
		err.Value = t.DocumentDate
		errs = append(errs, err)
	}

	if t.UploadedBy == 0 {
		err := ErrDocumentUploadRequestUploadedByRequiredValidation
		err.Value = t.UploadedBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*DocumentUploadRequest)(nil)

func (t *DocumentUploadRequest) Validate() error {
	return ValidateDocumentUploadRequest(t)
}
