// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilCoverageInfo is returned when the CoverageInfo is nil.
	ErrNilCoverageInfo = errors.New("input CoverageInfo is nil")

	// ErrCoverageInfoSumAssuredGTValidation is the error returned when the value of the field is less than the 0.
	ErrCoverageInfoSumAssuredGTValidation = govaliderrors.ValidationError{Reason: "field SumAssured must be greater than 0", Path: "CoverageInfo.SumAssured", Type: "gt"}

	// ErrCoverageInfoSumAssuredRequiredValidation is returned when the SumAssured is required but not provided.
	ErrCoverageInfoSumAssuredRequiredValidation = govaliderrors.ValidationError{Reason: "field SumAssured is required", Path: "CoverageInfo.SumAssured", Type: "required"}

	// ErrCoverageInfoPolicyTermGTEValidation is the error returned when the value of the field is less than 5.
	ErrCoverageInfoPolicyTermGTEValidation = govaliderrors.ValidationError{Reason: "field PolicyTerm must be greater than or equal to 5", Path: "CoverageInfo.PolicyTerm", Type: "gte"}

	// ErrCoverageInfoPolicyTermLTEValidation is the error returned when the value of the field is greater than 50.
	ErrCoverageInfoPolicyTermLTEValidation = govaliderrors.ValidationError{Reason: "field PolicyTerm must be less than or equal to 50", Path: "CoverageInfo.PolicyTerm", Type: "lte"}

	// ErrCoverageInfoPolicyTermRequiredValidation is returned when the PolicyTerm is required but not provided.
	ErrCoverageInfoPolicyTermRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyTerm is required", Path: "CoverageInfo.PolicyTerm", Type: "required"}

	// ErrCoverageInfoPaymentFrequencyOneofValidation is the error returned when the field is not one of the allowed values.
	ErrCoverageInfoPaymentFrequencyOneofValidation = govaliderrors.ValidationError{Reason: "field PaymentFrequency must be one of MONTHLY QUARTERLY HALF_YEARLY YEARLY", Path: "CoverageInfo.PaymentFrequency", Type: "oneof"}

	// ErrCoverageInfoPaymentFrequencyRequiredValidation is returned when the PaymentFrequency is required but not provided.
	ErrCoverageInfoPaymentFrequencyRequiredValidation = govaliderrors.ValidationError{Reason: "field PaymentFrequency is required", Path: "CoverageInfo.PaymentFrequency", Type: "required"}
)

func ValidateCoverageInfo(t *CoverageInfo) error {
	if t == nil {
		return ErrNilCoverageInfo
	}

	var errs govaliderrors.ValidationErrors

	if !(t.SumAssured > 0) {
		err := ErrCoverageInfoSumAssuredGTValidation
		err.Value = t.SumAssured
		errs = append(errs, err)
	}

	if t.SumAssured == 0.0 {
		err := ErrCoverageInfoSumAssuredRequiredValidation
		err.Value = t.SumAssured
		errs = append(errs, err)
	}

	if !(t.PolicyTerm >= 5) {
		err := ErrCoverageInfoPolicyTermGTEValidation
		err.Value = t.PolicyTerm
		errs = append(errs, err)
	}

	if !(t.PolicyTerm <= 50) {
		err := ErrCoverageInfoPolicyTermLTEValidation
		err.Value = t.PolicyTerm
		errs = append(errs, err)
	}

	if t.PolicyTerm == 0 {
		err := ErrCoverageInfoPolicyTermRequiredValidation
		err.Value = t.PolicyTerm
		errs = append(errs, err)
	}

	if !(t.PaymentFrequency == "MONTHLY" || t.PaymentFrequency == "QUARTERLY" || t.PaymentFrequency == "HALF_YEARLY" || t.PaymentFrequency == "YEARLY") {
		err := ErrCoverageInfoPaymentFrequencyOneofValidation
		err.Value = t.PaymentFrequency
		errs = append(errs, err)
	}

	if t.PaymentFrequency == "" {
		err := ErrCoverageInfoPaymentFrequencyRequiredValidation
		err.Value = t.PaymentFrequency
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CoverageInfo)(nil)

func (t *CoverageInfo) Validate() error {
	return ValidateCoverageInfo(t)
}
