// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilBulkUploadRequest is returned when the BulkUploadRequest is nil.
	ErrNilBulkUploadRequest = errors.New("input BulkUploadRequest is nil")

	// ErrBulkUploadRequestFileNameRequiredValidation is returned when the FileName is required but not provided.
	ErrBulkUploadRequestFileNameRequiredValidation = govaliderrors.ValidationError{Reason: "field FileName is required", Path: "BulkUploadRequest.FileName", Type: "required"}

	// ErrBulkUploadRequestMimeTypeRequiredValidation is returned when the MimeType is required but not provided.
	ErrBulkUploadRequestMimeTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field MimeType is required", Path: "BulkUploadRequest.MimeType", Type: "required"}

	// ErrBulkUploadRequestFileSizeGTValidation is the error returned when the value of the field is less than the 0.
	ErrBulkUploadRequestFileSizeGTValidation = govaliderrors.ValidationError{Reason: "field FileSize must be greater than 0", Path: "BulkUploadRequest.FileSize", Type: "gt"}

	// ErrBulkUploadRequestFileSizeRequiredValidation is returned when the FileSize is required but not provided.
	ErrBulkUploadRequestFileSizeRequiredValidation = govaliderrors.ValidationError{Reason: "field FileSize is required", Path: "BulkUploadRequest.FileSize", Type: "required"}

	// ErrBulkUploadRequestTotalRowsGTValidation is the error returned when the value of the field is less than the 0.
	ErrBulkUploadRequestTotalRowsGTValidation = govaliderrors.ValidationError{Reason: "field TotalRows must be greater than 0", Path: "BulkUploadRequest.TotalRows", Type: "gt"}

	// ErrBulkUploadRequestTotalRowsLTEValidation is the error returned when the value of the field is greater than 1000.
	ErrBulkUploadRequestTotalRowsLTEValidation = govaliderrors.ValidationError{Reason: "field TotalRows must be less than or equal to 1000", Path: "BulkUploadRequest.TotalRows", Type: "lte"}

	// ErrBulkUploadRequestTotalRowsRequiredValidation is returned when the TotalRows is required but not provided.
	ErrBulkUploadRequestTotalRowsRequiredValidation = govaliderrors.ValidationError{Reason: "field TotalRows is required", Path: "BulkUploadRequest.TotalRows", Type: "required"}

	// ErrBulkUploadRequestPaymentTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrBulkUploadRequestPaymentTypeOneofValidation = govaliderrors.ValidationError{Reason: "field PaymentType must be one of INDIVIDUAL COMBINED_CHEQUE", Path: "BulkUploadRequest.PaymentType", Type: "oneof"}

	// ErrBulkUploadRequestPaymentTypeRequiredValidation is returned when the PaymentType is required but not provided.
	ErrBulkUploadRequestPaymentTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field PaymentType is required", Path: "BulkUploadRequest.PaymentType", Type: "required"}

	// ErrBulkUploadRequestUploadedByRequiredValidation is returned when the UploadedBy is required but not provided.
	ErrBulkUploadRequestUploadedByRequiredValidation = govaliderrors.ValidationError{Reason: "field UploadedBy is required", Path: "BulkUploadRequest.UploadedBy", Type: "required"}
)

func ValidateBulkUploadRequest(t *BulkUploadRequest) error {
	if t == nil {
		return ErrNilBulkUploadRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.FileName == "" {
		err := ErrBulkUploadRequestFileNameRequiredValidation
		err.Value = t.FileName
		errs = append(errs, err)
	}

	if t.MimeType == "" {
		err := ErrBulkUploadRequestMimeTypeRequiredValidation
		err.Value = t.MimeType
		errs = append(errs, err)
	}

	if !(t.FileSize > 0) {
		err := ErrBulkUploadRequestFileSizeGTValidation
		err.Value = t.FileSize
		errs = append(errs, err)
	}

	if t.FileSize == 0 {
		err := ErrBulkUploadRequestFileSizeRequiredValidation
		err.Value = t.FileSize
		errs = append(errs, err)
	}

	if !(t.TotalRows > 0) {
		err := ErrBulkUploadRequestTotalRowsGTValidation
		err.Value = t.TotalRows
		errs = append(errs, err)
	}

	if !(t.TotalRows <= 1000) {
		err := ErrBulkUploadRequestTotalRowsLTEValidation
		err.Value = t.TotalRows
		errs = append(errs, err)
	}

	if t.TotalRows == 0 {
		err := ErrBulkUploadRequestTotalRowsRequiredValidation
		err.Value = t.TotalRows
		errs = append(errs, err)
	}

	if !(t.PaymentType == "INDIVIDUAL" || t.PaymentType == "COMBINED_CHEQUE") {
		err := ErrBulkUploadRequestPaymentTypeOneofValidation
		err.Value = t.PaymentType
		errs = append(errs, err)
	}

	if t.PaymentType == "" {
		err := ErrBulkUploadRequestPaymentTypeRequiredValidation
		err.Value = t.PaymentType
		errs = append(errs, err)
	}

	if t.UploadedBy == 0 {
		err := ErrBulkUploadRequestUploadedByRequiredValidation
		err.Value = t.UploadedBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*BulkUploadRequest)(nil)

func (t *BulkUploadRequest) Validate() error {
	return ValidateBulkUploadRequest(t)
}
