// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilApproverRejectRequest is returned when the ApproverRejectRequest is nil.
	ErrNilApproverRejectRequest = errors.New("input ApproverRejectRequest is nil")

	// ErrApproverRejectRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrApproverRejectRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "ApproverRejectRequest.ProposalID", Type: "required"}

	// ErrApproverRejectRequestApproverIDRequiredValidation is returned when the ApproverID is required but not provided.
	ErrApproverRejectRequestApproverIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApproverID is required", Path: "ApproverRejectRequest.ApproverID", Type: "required"}

	// ErrApproverRejectRequestCommentsRequiredValidation is returned when the Comments is required but not provided.
	ErrApproverRejectRequestCommentsRequiredValidation = govaliderrors.ValidationError{Reason: "field Comments is required", Path: "ApproverRejectRequest.Comments", Type: "required"}
)

func ValidateApproverRejectRequest(t *ApproverRejectRequest) error {
	if t == nil {
		return ErrNilApproverRejectRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrApproverRejectRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if t.ApproverID == "" {
		err := ErrApproverRejectRequestApproverIDRequiredValidation
		err.Value = t.ApproverID
		errs = append(errs, err)
	}

	if t.Comments == "" {
		err := ErrApproverRejectRequestCommentsRequiredValidation
		err.Value = t.Comments
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ApproverRejectRequest)(nil)

func (t *ApproverRejectRequest) Validate() error {
	return ValidateApproverRejectRequest(t)
}
