// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilQuoteCreateRequest is returned when the QuoteCreateRequest is nil.
	ErrNilQuoteCreateRequest = errors.New("input QuoteCreateRequest is nil")

	// ErrQuoteCreateRequestCalculationIDRequiredValidation is returned when the CalculationID is required but not provided.
	ErrQuoteCreateRequestCalculationIDRequiredValidation = govaliderrors.ValidationError{Reason: "field CalculationID is required", Path: "QuoteCreateRequest.CalculationID", Type: "required"}

	// isValidUUID validates UUID format manually for maximum performance
	// Validates RFC 4122 format: 8-4-4-4-12 hex digits with hyphens
	isValidUUID = func(s string) bool {
		// Check length: 36 characters (32 hex + 4 hyphens)
		if len(s) != 36 {
			return false
		}

		// Check hyphen positions: 8-4-4-4-12
		if s[8] != '-' || s[13] != '-' || s[18] != '-' || s[23] != '-' {
			return false
		}

		// Check hex characters and version/variant
		for i := 0; i < 36; i++ {
			if i == 8 || i == 13 || i == 18 || i == 23 {
				continue // skip hyphens
			}

			c := s[i]
			if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')) {
				return false
			}
		}

		// Check version (position 14): must be 1-5
		version := s[14]
		if version < '1' || version > '5' {
			return false
		}

		// Check variant (position 19): must be 8, 9, A, B (case insensitive)
		variant := s[19]
		if !(variant == '8' || variant == '9' ||
			variant == 'A' || variant == 'a' ||
			variant == 'B' || variant == 'b') {
			return false
		}

		return true
	}
	// ErrQuoteCreateRequestCalculationIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrQuoteCreateRequestCalculationIDUUIDValidation = govaliderrors.ValidationError{Reason: "field CalculationID must be a valid UUID", Path: "QuoteCreateRequest.CalculationID", Type: "uuid"}

	// ErrQuoteCreateRequestPolicyTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrQuoteCreateRequestPolicyTypeOneofValidation = govaliderrors.ValidationError{Reason: "field PolicyType must be one of PLI RPLI", Path: "QuoteCreateRequest.PolicyType", Type: "oneof"}

	// ErrQuoteCreateRequestPolicyTypeRequiredValidation is returned when the PolicyType is required but not provided.
	ErrQuoteCreateRequestPolicyTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyType is required", Path: "QuoteCreateRequest.PolicyType", Type: "required"}

	// ErrQuoteCreateRequestProductCodeRequiredValidation is returned when the ProductCode is required but not provided.
	ErrQuoteCreateRequestProductCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field ProductCode is required", Path: "QuoteCreateRequest.ProductCode", Type: "required"}

	// ErrQuoteCreateRequestChannelOneofValidation is the error returned when the field is not one of the allowed values.
	ErrQuoteCreateRequestChannelOneofValidation = govaliderrors.ValidationError{Reason: "field Channel must be one of DIRECT AGENCY WEB MOBILE POS CSC", Path: "QuoteCreateRequest.Channel", Type: "oneof"}

	// ErrQuoteCreateRequestChannelRequiredValidation is returned when the Channel is required but not provided.
	ErrQuoteCreateRequestChannelRequiredValidation = govaliderrors.ValidationError{Reason: "field Channel is required", Path: "QuoteCreateRequest.Channel", Type: "required"}

	// ErrQuoteCreateRequestCreatedByRequiredValidation is returned when the CreatedBy is required but not provided.
	ErrQuoteCreateRequestCreatedByRequiredValidation = govaliderrors.ValidationError{Reason: "field CreatedBy is required", Path: "QuoteCreateRequest.CreatedBy", Type: "required"}
)

func ValidateQuoteCreateRequest(t *QuoteCreateRequest) error {
	if t == nil {
		return ErrNilQuoteCreateRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.CalculationID == "" {
		err := ErrQuoteCreateRequestCalculationIDRequiredValidation
		err.Value = t.CalculationID
		errs = append(errs, err)
	}

	if !isValidUUID(t.CalculationID) {
		err := ErrQuoteCreateRequestCalculationIDUUIDValidation
		err.Value = t.CalculationID
		errs = append(errs, err)
	}

	if !(t.PolicyType == "PLI" || t.PolicyType == "RPLI") {
		err := ErrQuoteCreateRequestPolicyTypeOneofValidation
		err.Value = t.PolicyType
		errs = append(errs, err)
	}

	if t.PolicyType == "" {
		err := ErrQuoteCreateRequestPolicyTypeRequiredValidation
		err.Value = t.PolicyType
		errs = append(errs, err)
	}

	if t.ProductCode == "" {
		err := ErrQuoteCreateRequestProductCodeRequiredValidation
		err.Value = t.ProductCode
		errs = append(errs, err)
	}

	if !(t.Channel == "DIRECT" || t.Channel == "AGENCY" || t.Channel == "WEB" || t.Channel == "MOBILE" || t.Channel == "POS" || t.Channel == "CSC") {
		err := ErrQuoteCreateRequestChannelOneofValidation
		err.Value = t.Channel
		errs = append(errs, err)
	}

	if t.Channel == "" {
		err := ErrQuoteCreateRequestChannelRequiredValidation
		err.Value = t.Channel
		errs = append(errs, err)
	}

	if t.CreatedBy == 0 {
		err := ErrQuoteCreateRequestCreatedByRequiredValidation
		err.Value = t.CreatedBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*QuoteCreateRequest)(nil)

func (t *QuoteCreateRequest) Validate() error {
	return ValidateQuoteCreateRequest(t)
}
