// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilPremiumCalculationRequest is returned when the PremiumCalculationRequest is nil.
	ErrNilPremiumCalculationRequest = errors.New("input PremiumCalculationRequest is nil")

	// ErrPremiumCalculationRequestProductCodeRequiredValidation is returned when the ProductCode is required but not provided.
	ErrPremiumCalculationRequestProductCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field ProductCode is required", Path: "PremiumCalculationRequest.ProductCode", Type: "required"}

	// ErrPremiumCalculationRequestDateOfBirthRequiredValidation is returned when the DateOfBirth is required but not provided.
	ErrPremiumCalculationRequestDateOfBirthRequiredValidation = govaliderrors.ValidationError{Reason: "field DateOfBirth is required", Path: "PremiumCalculationRequest.DateOfBirth", Type: "required"}

	// ErrPremiumCalculationRequestDateOfCalculationRequiredValidation is returned when the DateOfCalculation is required but not provided.
	ErrPremiumCalculationRequestDateOfCalculationRequiredValidation = govaliderrors.ValidationError{Reason: "field DateOfCalculation is required", Path: "PremiumCalculationRequest.DateOfCalculation", Type: "required"}

	// ErrPremiumCalculationRequestGenderRequiredValidation is returned when the Gender is required but not provided.
	ErrPremiumCalculationRequestGenderRequiredValidation = govaliderrors.ValidationError{Reason: "field Gender is required", Path: "PremiumCalculationRequest.Gender", Type: "required"}

	// ErrPremiumCalculationRequestSumAssuredGTValidation is the error returned when the value of the field is less than the 0.
	ErrPremiumCalculationRequestSumAssuredGTValidation = govaliderrors.ValidationError{Reason: "field SumAssured must be greater than 0", Path: "PremiumCalculationRequest.SumAssured", Type: "gt"}

	// ErrPremiumCalculationRequestSumAssuredRequiredValidation is returned when the SumAssured is required but not provided.
	ErrPremiumCalculationRequestSumAssuredRequiredValidation = govaliderrors.ValidationError{Reason: "field SumAssured is required", Path: "PremiumCalculationRequest.SumAssured", Type: "required"}

	// ErrPremiumCalculationRequestPeriodicityRequiredValidation is returned when the Periodicity is required but not provided.
	ErrPremiumCalculationRequestPeriodicityRequiredValidation = govaliderrors.ValidationError{Reason: "field Periodicity is required", Path: "PremiumCalculationRequest.Periodicity", Type: "required"}
)

func ValidatePremiumCalculationRequest(t *PremiumCalculationRequest) error {
	if t == nil {
		return ErrNilPremiumCalculationRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProductCode == "" {
		err := ErrPremiumCalculationRequestProductCodeRequiredValidation
		err.Value = t.ProductCode
		errs = append(errs, err)
	}

	if t.DateOfBirth == "" {
		err := ErrPremiumCalculationRequestDateOfBirthRequiredValidation
		err.Value = t.DateOfBirth
		errs = append(errs, err)
	}

	if t.DateOfCalculation == "" {
		err := ErrPremiumCalculationRequestDateOfCalculationRequiredValidation
		err.Value = t.DateOfCalculation
		errs = append(errs, err)
	}

	if t.Gender == "" {
		err := ErrPremiumCalculationRequestGenderRequiredValidation
		err.Value = t.Gender
		errs = append(errs, err)
	}

	if !(t.SumAssured > 0) {
		err := ErrPremiumCalculationRequestSumAssuredGTValidation
		err.Value = t.SumAssured
		errs = append(errs, err)
	}

	if t.SumAssured == 0 {
		err := ErrPremiumCalculationRequestSumAssuredRequiredValidation
		err.Value = t.SumAssured
		errs = append(errs, err)
	}

	if t.Periodicity == "" {
		err := ErrPremiumCalculationRequestPeriodicityRequiredValidation
		err.Value = t.Periodicity
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*PremiumCalculationRequest)(nil)

func (t *PremiumCalculationRequest) Validate() error {
	return ValidatePremiumCalculationRequest(t)
}
