// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilEligibilityCheckRequest is returned when the EligibilityCheckRequest is nil.
	ErrNilEligibilityCheckRequest = errors.New("input EligibilityCheckRequest is nil")

	// ErrEligibilityCheckRequestProductCodeRequiredValidation is returned when the ProductCode is required but not provided.
	ErrEligibilityCheckRequestProductCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field ProductCode is required", Path: "EligibilityCheckRequest.ProductCode", Type: "required"}

	// ErrEligibilityCheckRequestPolicyTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrEligibilityCheckRequestPolicyTypeOneofValidation = govaliderrors.ValidationError{Reason: "field PolicyType must be one of PLI RPLI", Path: "EligibilityCheckRequest.PolicyType", Type: "oneof"}

	// ErrEligibilityCheckRequestDateOfBirthDateValidation is the error returned when the field is not a valid date (dd/mm/yy).
	ErrEligibilityCheckRequestDateOfBirthDateValidation = govaliderrors.ValidationError{Reason: "field DateOfBirth must be a valid date (dd/mm/yy)", Path: "EligibilityCheckRequest.DateOfBirth", Type: "date"}

	// ErrEligibilityCheckRequestDateOfBirthRequiredValidation is returned when the DateOfBirth is required but not provided.
	ErrEligibilityCheckRequestDateOfBirthRequiredValidation = govaliderrors.ValidationError{Reason: "field DateOfBirth is required", Path: "EligibilityCheckRequest.DateOfBirth", Type: "required"}

	// ErrEligibilityCheckRequestSumAssuredGTValidation is the error returned when the value of the field is less than the 0.
	ErrEligibilityCheckRequestSumAssuredGTValidation = govaliderrors.ValidationError{Reason: "field SumAssured must be greater than 0", Path: "EligibilityCheckRequest.SumAssured", Type: "gt"}

	// ErrEligibilityCheckRequestSumAssuredRequiredValidation is returned when the SumAssured is required but not provided.
	ErrEligibilityCheckRequestSumAssuredRequiredValidation = govaliderrors.ValidationError{Reason: "field SumAssured is required", Path: "EligibilityCheckRequest.SumAssured", Type: "required"}

	// ErrEligibilityCheckRequestPolicyTermGTValidation is the error returned when the value of the field is less than the 0.
	ErrEligibilityCheckRequestPolicyTermGTValidation = govaliderrors.ValidationError{Reason: "field PolicyTerm must be greater than 0", Path: "EligibilityCheckRequest.PolicyTerm", Type: "gt"}
)

func ValidateEligibilityCheckRequest(t *EligibilityCheckRequest) error {
	if t == nil {
		return ErrNilEligibilityCheckRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProductCode == "" {
		err := ErrEligibilityCheckRequestProductCodeRequiredValidation
		err.Value = t.ProductCode
		errs = append(errs, err)
	}

	if t.PolicyType != "" && !(t.PolicyType == "PLI" || t.PolicyType == "RPLI") {
		err := ErrEligibilityCheckRequestPolicyTypeOneofValidation
		err.Value = t.PolicyType
		errs = append(errs, err)
	}

	if !validationhelper.IsValidDateDDMMYY(t.DateOfBirth) {
		err := ErrEligibilityCheckRequestDateOfBirthDateValidation
		err.Value = t.DateOfBirth
		errs = append(errs, err)
	}

	if t.DateOfBirth == "" {
		err := ErrEligibilityCheckRequestDateOfBirthRequiredValidation
		err.Value = t.DateOfBirth
		errs = append(errs, err)
	}

	if !(t.SumAssured > 0) {
		err := ErrEligibilityCheckRequestSumAssuredGTValidation
		err.Value = t.SumAssured
		errs = append(errs, err)
	}

	if t.SumAssured == 0.0 {
		err := ErrEligibilityCheckRequestSumAssuredRequiredValidation
		err.Value = t.SumAssured
		errs = append(errs, err)
	}

	if t.PolicyTerm != 0 && !(t.PolicyTerm > 0) {
		err := ErrEligibilityCheckRequestPolicyTermGTValidation
		err.Value = t.PolicyTerm
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*EligibilityCheckRequest)(nil)

func (t *EligibilityCheckRequest) Validate() error {
	return ValidateEligibilityCheckRequest(t)
}
