// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilCustomerCreateInput is returned when the CustomerCreateInput is nil.
	ErrNilCustomerCreateInput = errors.New("input CustomerCreateInput is nil")

	// ErrCustomerCreateInputIdempotencyKeyMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrCustomerCreateInputIdempotencyKeyMaxLengthValidation = govaliderrors.ValidationError{Reason: "field IdempotencyKey must have a maximum length of 100", Path: "CustomerCreateInput.IdempotencyKey", Type: "maxlength"}

	// ErrCustomerCreateInputIdempotencyKeyMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrCustomerCreateInputIdempotencyKeyMinLengthValidation = govaliderrors.ValidationError{Reason: "field IdempotencyKey must have a minimum length of 1", Path: "CustomerCreateInput.IdempotencyKey", Type: "minlength"}

	// ErrCustomerCreateInputIdempotencyKeyRequiredValidation is returned when the IdempotencyKey is required but not provided.
	ErrCustomerCreateInputIdempotencyKeyRequiredValidation = govaliderrors.ValidationError{Reason: "field IdempotencyKey is required", Path: "CustomerCreateInput.IdempotencyKey", Type: "required"}

	// ErrCustomerCreateInputProductTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrCustomerCreateInputProductTypeOneofValidation = govaliderrors.ValidationError{Reason: "field ProductType must be one of PLI RPLI", Path: "CustomerCreateInput.ProductType", Type: "oneof"}

	// ErrCustomerCreateInputProductTypeRequiredValidation is returned when the ProductType is required but not provided.
	ErrCustomerCreateInputProductTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field ProductType is required", Path: "CustomerCreateInput.ProductType", Type: "required"}

	// Deprecated: Use ErrCustomerCreateInputBankAccountsiAccountNumberMaxLengthValidation
	//
	// ErrCustomerCreateInputAccountNumberMaxLengthValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputAccountNumberMaxLengthValidation = ErrCustomerCreateInputBankAccountsiAccountNumberMaxLengthValidation

	// ErrCustomerCreateInputBankAccountsiAccountNumberMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 18.
	ErrCustomerCreateInputBankAccountsiAccountNumberMaxLengthValidation = govaliderrors.ValidationError{Reason: "field AccountNumber must have a maximum length of 18", Path: "CustomerCreateInput.BankAccounts[i].AccountNumber", Type: "maxlength"}

	// Deprecated: Use ErrCustomerCreateInputBankAccountsiAccountNumberMinLengthValidation
	//
	// ErrCustomerCreateInputAccountNumberMinLengthValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputAccountNumberMinLengthValidation = ErrCustomerCreateInputBankAccountsiAccountNumberMinLengthValidation

	// ErrCustomerCreateInputBankAccountsiAccountNumberMinLengthValidation is the error returned when the length of the field is less than the minimum of 9.
	ErrCustomerCreateInputBankAccountsiAccountNumberMinLengthValidation = govaliderrors.ValidationError{Reason: "field AccountNumber must have a minimum length of 9", Path: "CustomerCreateInput.BankAccounts[i].AccountNumber", Type: "minlength"}

	// Deprecated: Use ErrCustomerCreateInputBankAccountsiAccountNumberRequiredValidation
	//
	// ErrCustomerCreateInputAccountNumberRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputAccountNumberRequiredValidation = ErrCustomerCreateInputBankAccountsiAccountNumberRequiredValidation

	// ErrCustomerCreateInputBankAccountsiAccountNumberRequiredValidation is returned when the AccountNumber is required but not provided.
	ErrCustomerCreateInputBankAccountsiAccountNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field AccountNumber is required", Path: "CustomerCreateInput.BankAccounts[i].AccountNumber", Type: "required"}

	// Deprecated: Use ErrCustomerCreateInputBankAccountsiIFSCCodeLengthValidation
	//
	// ErrCustomerCreateInputIFSCCodeLengthValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputIFSCCodeLengthValidation = ErrCustomerCreateInputBankAccountsiIFSCCodeLengthValidation

	// ErrCustomerCreateInputBankAccountsiIFSCCodeLengthValidation is the error returned when the length of the field is not exactly 11.
	ErrCustomerCreateInputBankAccountsiIFSCCodeLengthValidation = govaliderrors.ValidationError{Reason: "field IFSCCode length must be exactly 11", Path: "CustomerCreateInput.BankAccounts[i].IFSCCode", Type: "length"}

	// Deprecated: Use ErrCustomerCreateInputBankAccountsiIFSCCodeRequiredValidation
	//
	// ErrCustomerCreateInputIFSCCodeRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputIFSCCodeRequiredValidation = ErrCustomerCreateInputBankAccountsiIFSCCodeRequiredValidation

	// ErrCustomerCreateInputBankAccountsiIFSCCodeRequiredValidation is returned when the IFSCCode is required but not provided.
	ErrCustomerCreateInputBankAccountsiIFSCCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field IFSCCode is required", Path: "CustomerCreateInput.BankAccounts[i].IFSCCode", Type: "required"}

	// Deprecated: Use ErrCustomerCreateInputBankAccountsiBankNameMaxLengthValidation
	//
	// ErrCustomerCreateInputBankNameMaxLengthValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputBankNameMaxLengthValidation = ErrCustomerCreateInputBankAccountsiBankNameMaxLengthValidation

	// ErrCustomerCreateInputBankAccountsiBankNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrCustomerCreateInputBankAccountsiBankNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field BankName must have a maximum length of 100", Path: "CustomerCreateInput.BankAccounts[i].BankName", Type: "maxlength"}

	// Deprecated: Use ErrCustomerCreateInputBankAccountsiBankNameMinLengthValidation
	//
	// ErrCustomerCreateInputBankNameMinLengthValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputBankNameMinLengthValidation = ErrCustomerCreateInputBankAccountsiBankNameMinLengthValidation

	// ErrCustomerCreateInputBankAccountsiBankNameMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrCustomerCreateInputBankAccountsiBankNameMinLengthValidation = govaliderrors.ValidationError{Reason: "field BankName must have a minimum length of 1", Path: "CustomerCreateInput.BankAccounts[i].BankName", Type: "minlength"}

	// Deprecated: Use ErrCustomerCreateInputBankAccountsiBankNameRequiredValidation
	//
	// ErrCustomerCreateInputBankNameRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputBankNameRequiredValidation = ErrCustomerCreateInputBankAccountsiBankNameRequiredValidation

	// ErrCustomerCreateInputBankAccountsiBankNameRequiredValidation is returned when the BankName is required but not provided.
	ErrCustomerCreateInputBankAccountsiBankNameRequiredValidation = govaliderrors.ValidationError{Reason: "field BankName is required", Path: "CustomerCreateInput.BankAccounts[i].BankName", Type: "required"}

	// Deprecated: Use ErrCustomerCreateInputBankAccountsiBranchNameMaxLengthValidation
	//
	// ErrCustomerCreateInputBranchNameMaxLengthValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputBranchNameMaxLengthValidation = ErrCustomerCreateInputBankAccountsiBranchNameMaxLengthValidation

	// ErrCustomerCreateInputBankAccountsiBranchNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrCustomerCreateInputBankAccountsiBranchNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field BranchName must have a maximum length of 100", Path: "CustomerCreateInput.BankAccounts[i].BranchName", Type: "maxlength"}

	// Deprecated: Use ErrCustomerCreateInputBankAccountsiAccountTypeOneofValidation
	//
	// ErrCustomerCreateInputAccountTypeOneofValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputAccountTypeOneofValidation = ErrCustomerCreateInputBankAccountsiAccountTypeOneofValidation

	// ErrCustomerCreateInputBankAccountsiAccountTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrCustomerCreateInputBankAccountsiAccountTypeOneofValidation = govaliderrors.ValidationError{Reason: "field AccountType must be one of SAVINGS CURRENT SALARY NRE NRO", Path: "CustomerCreateInput.BankAccounts[i].AccountType", Type: "oneof"}

	// Deprecated: Use ErrCustomerCreateInputBankAccountsiAccountTypeRequiredValidation
	//
	// ErrCustomerCreateInputAccountTypeRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputAccountTypeRequiredValidation = ErrCustomerCreateInputBankAccountsiAccountTypeRequiredValidation

	// ErrCustomerCreateInputBankAccountsiAccountTypeRequiredValidation is returned when the AccountType is required but not provided.
	ErrCustomerCreateInputBankAccountsiAccountTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field AccountType is required", Path: "CustomerCreateInput.BankAccounts[i].AccountType", Type: "required"}

	// Deprecated: Use ErrCustomerCreateInputBankAccountsiPurposeOneofValidation
	//
	// ErrCustomerCreateInputPurposeOneofValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputPurposeOneofValidation = ErrCustomerCreateInputBankAccountsiPurposeOneofValidation

	// ErrCustomerCreateInputBankAccountsiPurposeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrCustomerCreateInputBankAccountsiPurposeOneofValidation = govaliderrors.ValidationError{Reason: "field Purpose must be one of PREMIUM_PAYMENT CLAIM_SETTLEMENT REFUND", Path: "CustomerCreateInput.BankAccounts[i].Purpose", Type: "oneof"}

	// Deprecated: Use ErrCustomerCreateInputBankAccountsiPurposeRequiredValidation
	//
	// ErrCustomerCreateInputPurposeRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputPurposeRequiredValidation = ErrCustomerCreateInputBankAccountsiPurposeRequiredValidation

	// ErrCustomerCreateInputBankAccountsiPurposeRequiredValidation is returned when the Purpose is required but not provided.
	ErrCustomerCreateInputBankAccountsiPurposeRequiredValidation = govaliderrors.ValidationError{Reason: "field Purpose is required", Path: "CustomerCreateInput.BankAccounts[i].Purpose", Type: "required"}

	// Deprecated: Use ErrCustomerCreateInputBankAccountsiIsPrimaryRequiredValidation
	//
	// ErrCustomerCreateInputIsPrimaryRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputIsPrimaryRequiredValidation = ErrCustomerCreateInputBankAccountsiIsPrimaryRequiredValidation

	// ErrCustomerCreateInputBankAccountsiIsPrimaryRequiredValidation is returned when the IsPrimary is required but not provided.
	ErrCustomerCreateInputBankAccountsiIsPrimaryRequiredValidation = govaliderrors.ValidationError{Reason: "field IsPrimary is required", Path: "CustomerCreateInput.BankAccounts[i].IsPrimary", Type: "required"}

	// Deprecated: Use ErrCustomerCreateInputPreferencesiKeyMaxLengthValidation
	//
	// ErrCustomerCreateInputKeyMaxLengthValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputKeyMaxLengthValidation = ErrCustomerCreateInputPreferencesiKeyMaxLengthValidation

	// ErrCustomerCreateInputPreferencesiKeyMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrCustomerCreateInputPreferencesiKeyMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Key must have a maximum length of 50", Path: "CustomerCreateInput.Preferences[i].Key", Type: "maxlength"}

	// Deprecated: Use ErrCustomerCreateInputPreferencesiKeyMinLengthValidation
	//
	// ErrCustomerCreateInputKeyMinLengthValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputKeyMinLengthValidation = ErrCustomerCreateInputPreferencesiKeyMinLengthValidation

	// ErrCustomerCreateInputPreferencesiKeyMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrCustomerCreateInputPreferencesiKeyMinLengthValidation = govaliderrors.ValidationError{Reason: "field Key must have a minimum length of 1", Path: "CustomerCreateInput.Preferences[i].Key", Type: "minlength"}

	// Deprecated: Use ErrCustomerCreateInputPreferencesiKeyRequiredValidation
	//
	// ErrCustomerCreateInputKeyRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputKeyRequiredValidation = ErrCustomerCreateInputPreferencesiKeyRequiredValidation

	// ErrCustomerCreateInputPreferencesiKeyRequiredValidation is returned when the Key is required but not provided.
	ErrCustomerCreateInputPreferencesiKeyRequiredValidation = govaliderrors.ValidationError{Reason: "field Key is required", Path: "CustomerCreateInput.Preferences[i].Key", Type: "required"}

	// Deprecated: Use ErrCustomerCreateInputPreferencesiValueMaxLengthValidation
	//
	// ErrCustomerCreateInputValueMaxLengthValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputValueMaxLengthValidation = ErrCustomerCreateInputPreferencesiValueMaxLengthValidation

	// ErrCustomerCreateInputPreferencesiValueMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 200.
	ErrCustomerCreateInputPreferencesiValueMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Value must have a maximum length of 200", Path: "CustomerCreateInput.Preferences[i].Value", Type: "maxlength"}

	// Deprecated: Use ErrCustomerCreateInputPreferencesiValueMinLengthValidation
	//
	// ErrCustomerCreateInputValueMinLengthValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputValueMinLengthValidation = ErrCustomerCreateInputPreferencesiValueMinLengthValidation

	// ErrCustomerCreateInputPreferencesiValueMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrCustomerCreateInputPreferencesiValueMinLengthValidation = govaliderrors.ValidationError{Reason: "field Value must have a minimum length of 1", Path: "CustomerCreateInput.Preferences[i].Value", Type: "minlength"}

	// Deprecated: Use ErrCustomerCreateInputPreferencesiValueRequiredValidation
	//
	// ErrCustomerCreateInputValueRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrCustomerCreateInputValueRequiredValidation = ErrCustomerCreateInputPreferencesiValueRequiredValidation

	// ErrCustomerCreateInputPreferencesiValueRequiredValidation is returned when the Value is required but not provided.
	ErrCustomerCreateInputPreferencesiValueRequiredValidation = govaliderrors.ValidationError{Reason: "field Value is required", Path: "CustomerCreateInput.Preferences[i].Value", Type: "required"}
)

func ValidateCustomerCreateInput(t *CustomerCreateInput) error {
	if t == nil {
		return ErrNilCustomerCreateInput
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.IdempotencyKey) > 100 {
		err := ErrCustomerCreateInputIdempotencyKeyMaxLengthValidation
		err.Value = t.IdempotencyKey
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.IdempotencyKey) < 1 {
		err := ErrCustomerCreateInputIdempotencyKeyMinLengthValidation
		err.Value = t.IdempotencyKey
		errs = append(errs, err)
	}

	if t.IdempotencyKey == "" {
		err := ErrCustomerCreateInputIdempotencyKeyRequiredValidation
		err.Value = t.IdempotencyKey
		errs = append(errs, err)
	}

	if !(t.ProductType == "PLI" || t.ProductType == "RPLI") {
		err := ErrCustomerCreateInputProductTypeOneofValidation
		err.Value = t.ProductType
		errs = append(errs, err)
	}

	if t.ProductType == "" {
		err := ErrCustomerCreateInputProductTypeRequiredValidation
		err.Value = t.ProductType
		errs = append(errs, err)
	}

	for i := range t.BankAccounts {
		{
			t := t.BankAccounts[i]

			if utf8.RuneCountInString(t.AccountNumber) > 18 {
				err := ErrCustomerCreateInputBankAccountsiAccountNumberMaxLengthValidation
				err.Value = t.AccountNumber
				errs = append(errs, err)
			}

			if utf8.RuneCountInString(t.AccountNumber) < 9 {
				err := ErrCustomerCreateInputBankAccountsiAccountNumberMinLengthValidation
				err.Value = t.AccountNumber
				errs = append(errs, err)
			}

			if t.AccountNumber == "" {
				err := ErrCustomerCreateInputBankAccountsiAccountNumberRequiredValidation
				err.Value = t.AccountNumber
				errs = append(errs, err)
			}

			if utf8.RuneCountInString(t.IFSCCode) != 11 {
				err := ErrCustomerCreateInputBankAccountsiIFSCCodeLengthValidation
				err.Value = t.IFSCCode
				errs = append(errs, err)
			}

			if t.IFSCCode == "" {
				err := ErrCustomerCreateInputBankAccountsiIFSCCodeRequiredValidation
				err.Value = t.IFSCCode
				errs = append(errs, err)
			}

			if utf8.RuneCountInString(t.BankName) > 100 {
				err := ErrCustomerCreateInputBankAccountsiBankNameMaxLengthValidation
				err.Value = t.BankName
				errs = append(errs, err)
			}

			if utf8.RuneCountInString(t.BankName) < 1 {
				err := ErrCustomerCreateInputBankAccountsiBankNameMinLengthValidation
				err.Value = t.BankName
				errs = append(errs, err)
			}

			if t.BankName == "" {
				err := ErrCustomerCreateInputBankAccountsiBankNameRequiredValidation
				err.Value = t.BankName
				errs = append(errs, err)
			}

			if t.BranchName != "" && utf8.RuneCountInString(t.BranchName) > 100 {
				err := ErrCustomerCreateInputBankAccountsiBranchNameMaxLengthValidation
				err.Value = t.BranchName
				errs = append(errs, err)
			}

			if !(t.AccountType == "SAVINGS" || t.AccountType == "CURRENT" || t.AccountType == "SALARY" || t.AccountType == "NRE" || t.AccountType == "NRO") {
				err := ErrCustomerCreateInputBankAccountsiAccountTypeOneofValidation
				err.Value = t.AccountType
				errs = append(errs, err)
			}

			if t.AccountType == "" {
				err := ErrCustomerCreateInputBankAccountsiAccountTypeRequiredValidation
				err.Value = t.AccountType
				errs = append(errs, err)
			}

			if !(t.Purpose == "PREMIUM_PAYMENT" || t.Purpose == "CLAIM_SETTLEMENT" || t.Purpose == "REFUND") {
				err := ErrCustomerCreateInputBankAccountsiPurposeOneofValidation
				err.Value = t.Purpose
				errs = append(errs, err)
			}

			if t.Purpose == "" {
				err := ErrCustomerCreateInputBankAccountsiPurposeRequiredValidation
				err.Value = t.Purpose
				errs = append(errs, err)
			}

			if t.IsPrimary == false {
				err := ErrCustomerCreateInputBankAccountsiIsPrimaryRequiredValidation
				err.Value = t.IsPrimary
				errs = append(errs, err)
			}

		}
	}

	for i := range t.Preferences {
		{
			t := t.Preferences[i]

			if utf8.RuneCountInString(t.Key) > 50 {
				err := ErrCustomerCreateInputPreferencesiKeyMaxLengthValidation
				err.Value = t.Key
				errs = append(errs, err)
			}

			if utf8.RuneCountInString(t.Key) < 1 {
				err := ErrCustomerCreateInputPreferencesiKeyMinLengthValidation
				err.Value = t.Key
				errs = append(errs, err)
			}

			if t.Key == "" {
				err := ErrCustomerCreateInputPreferencesiKeyRequiredValidation
				err.Value = t.Key
				errs = append(errs, err)
			}

			if utf8.RuneCountInString(t.Value) > 200 {
				err := ErrCustomerCreateInputPreferencesiValueMaxLengthValidation
				err.Value = t.Value
				errs = append(errs, err)
			}

			if utf8.RuneCountInString(t.Value) < 1 {
				err := ErrCustomerCreateInputPreferencesiValueMinLengthValidation
				err.Value = t.Value
				errs = append(errs, err)
			}

			if t.Value == "" {
				err := ErrCustomerCreateInputPreferencesiValueRequiredValidation
				err.Value = t.Value
				errs = append(errs, err)
			}

		}
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CustomerCreateInput)(nil)

func (t *CustomerCreateInput) Validate() error {
	return ValidateCustomerCreateInput(t)
}
