// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilPANFormatRequest is returned when the PANFormatRequest is nil.
	ErrNilPANFormatRequest = errors.New("input PANFormatRequest is nil")

	// ErrPANFormatRequestPANNumberRequiredValidation is returned when the PANNumber is required but not provided.
	ErrPANFormatRequestPANNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field PANNumber is required", Path: "PANFormatRequest.PANNumber", Type: "required"}
)

func ValidatePANFormatRequest(t *PANFormatRequest) error {
	if t == nil {
		return ErrNilPANFormatRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.PANNumber == "" {
		err := ErrPANFormatRequestPANNumberRequiredValidation
		err.Value = t.PANNumber
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*PANFormatRequest)(nil)

func (t *PANFormatRequest) Validate() error {
	return ValidatePANFormatRequest(t)
}
