// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilFLCInitiateRequest is returned when the FLCInitiateRequest is nil.
	ErrNilFLCInitiateRequest = errors.New("input FLCInitiateRequest is nil")

	// ErrFLCInitiateRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrFLCInitiateRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "FLCInitiateRequest.ProposalID", Type: "required"}

	// ErrFLCInitiateRequestCustomerIDRequiredValidation is returned when the CustomerID is required but not provided.
	ErrFLCInitiateRequestCustomerIDRequiredValidation = govaliderrors.ValidationError{Reason: "field CustomerID is required", Path: "FLCInitiateRequest.CustomerID", Type: "required"}

	// ErrFLCInitiateRequestRequestReasonRequiredValidation is returned when the RequestReason is required but not provided.
	ErrFLCInitiateRequestRequestReasonRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestReason is required", Path: "FLCInitiateRequest.RequestReason", Type: "required"}
)

func ValidateFLCInitiateRequest(t *FLCInitiateRequest) error {
	if t == nil {
		return ErrNilFLCInitiateRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrFLCInitiateRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if t.CustomerID == "" {
		err := ErrFLCInitiateRequestCustomerIDRequiredValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if t.RequestReason == "" {
		err := ErrFLCInitiateRequestRequestReasonRequiredValidation
		err.Value = t.RequestReason
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*FLCInitiateRequest)(nil)

func (t *FLCInitiateRequest) Validate() error {
	return ValidateFLCInitiateRequest(t)
}
