// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilQRRejectRequest is returned when the QRRejectRequest is nil.
	ErrNilQRRejectRequest = errors.New("input QRRejectRequest is nil")

	// ErrQRRejectRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrQRRejectRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "QRRejectRequest.ProposalID", Type: "required"}

	// ErrQRRejectRequestReviewerIDRequiredValidation is returned when the ReviewerID is required but not provided.
	ErrQRRejectRequestReviewerIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ReviewerID is required", Path: "QRRejectRequest.ReviewerID", Type: "required"}

	// ErrQRRejectRequestCommentsRequiredValidation is returned when the Comments is required but not provided.
	ErrQRRejectRequestCommentsRequiredValidation = govaliderrors.ValidationError{Reason: "field Comments is required", Path: "QRRejectRequest.Comments", Type: "required"}
)

func ValidateQRRejectRequest(t *QRRejectRequest) error {
	if t == nil {
		return ErrNilQRRejectRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrQRRejectRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if t.ReviewerID == "" {
		err := ErrQRRejectRequestReviewerIDRequiredValidation
		err.Value = t.ReviewerID
		errs = append(errs, err)
	}

	if t.Comments == "" {
		err := ErrQRRejectRequestCommentsRequiredValidation
		err.Value = t.Comments
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*QRRejectRequest)(nil)

func (t *QRRejectRequest) Validate() error {
	return ValidateQRRejectRequest(t)
}
