// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilFLCRejectRequest is returned when the FLCRejectRequest is nil.
	ErrNilFLCRejectRequest = errors.New("input FLCRejectRequest is nil")

	// ErrFLCRejectRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrFLCRejectRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "FLCRejectRequest.ProposalID", Type: "required"}

	// ErrFLCRejectRequestApproverIDRequiredValidation is returned when the ApproverID is required but not provided.
	ErrFLCRejectRequestApproverIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApproverID is required", Path: "FLCRejectRequest.ApproverID", Type: "required"}

	// ErrFLCRejectRequestRejectReasonRequiredValidation is returned when the RejectReason is required but not provided.
	ErrFLCRejectRequestRejectReasonRequiredValidation = govaliderrors.ValidationError{Reason: "field RejectReason is required", Path: "FLCRejectRequest.RejectReason", Type: "required"}
)

func ValidateFLCRejectRequest(t *FLCRejectRequest) error {
	if t == nil {
		return ErrNilFLCRejectRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrFLCRejectRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if t.ApproverID == "" {
		err := ErrFLCRejectRequestApproverIDRequiredValidation
		err.Value = t.ApproverID
		errs = append(errs, err)
	}

	if t.RejectReason == "" {
		err := ErrFLCRejectRequestRejectReasonRequiredValidation
		err.Value = t.RejectReason
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*FLCRejectRequest)(nil)

func (t *FLCRejectRequest) Validate() error {
	return ValidateFLCRejectRequest(t)
}
