// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilQRApproveRequest is returned when the QRApproveRequest is nil.
	ErrNilQRApproveRequest = errors.New("input QRApproveRequest is nil")

	// ErrQRApproveRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrQRApproveRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "QRApproveRequest.ProposalID", Type: "required"}

	// ErrQRApproveRequestReviewerIDRequiredValidation is returned when the ReviewerID is required but not provided.
	ErrQRApproveRequestReviewerIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ReviewerID is required", Path: "QRApproveRequest.ReviewerID", Type: "required"}
)

func ValidateQRApproveRequest(t *QRApproveRequest) error {
	if t == nil {
		return ErrNilQRApproveRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrQRApproveRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if t.ReviewerID == "" {
		err := ErrQRApproveRequestReviewerIDRequiredValidation
		err.Value = t.ReviewerID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*QRApproveRequest)(nil)

func (t *QRApproveRequest) Validate() error {
	return ValidateQRApproveRequest(t)
}
