// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilMedicalInfoRequest is returned when the MedicalInfoRequest is nil.
	ErrNilMedicalInfoRequest = errors.New("input MedicalInfoRequest is nil")

	// ErrMedicalInfoRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrMedicalInfoRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "MedicalInfoRequest.ProposalID", Type: "required"}

	// ErrMedicalInfoRequestMedicalInfoMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrMedicalInfoRequestMedicalInfoMinItemsValidation = govaliderrors.ValidationError{Reason: "field MedicalInfo must have a minimum of 1 items", Path: "MedicalInfoRequest.MedicalInfo", Type: "minitems"}

	// ErrMedicalInfoRequestMedicalInfoRequiredValidation is returned when the MedicalInfo is required but not provided.
	ErrMedicalInfoRequestMedicalInfoRequiredValidation = govaliderrors.ValidationError{Reason: "field MedicalInfo is required", Path: "MedicalInfoRequest.MedicalInfo", Type: "required"}
)

func ValidateMedicalInfoRequest(t *MedicalInfoRequest) error {
	if t == nil {
		return ErrNilMedicalInfoRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrMedicalInfoRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if len(t.MedicalInfo) < 1 {
		err := ErrMedicalInfoRequestMedicalInfoMinItemsValidation
		err.Value = t.MedicalInfo
		errs = append(errs, err)
	}

	if t.MedicalInfo == nil {
		err := ErrMedicalInfoRequestMedicalInfoRequiredValidation
		err.Value = t.MedicalInfo
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*MedicalInfoRequest)(nil)

func (t *MedicalInfoRequest) Validate() error {
	return ValidateMedicalInfoRequest(t)
}
