// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilMaturityCalculationRequest is returned when the MaturityCalculationRequest is nil.
	ErrNilMaturityCalculationRequest = errors.New("input MaturityCalculationRequest is nil")

	// ErrMaturityCalculationRequestProductCodeRequiredValidation is returned when the ProductCode is required but not provided.
	ErrMaturityCalculationRequestProductCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field ProductCode is required", Path: "MaturityCalculationRequest.ProductCode", Type: "required"}

	// ErrMaturityCalculationRequestSumAssuredGTValidation is the error returned when the value of the field is less than the 0.
	ErrMaturityCalculationRequestSumAssuredGTValidation = govaliderrors.ValidationError{Reason: "field SumAssured must be greater than 0", Path: "MaturityCalculationRequest.SumAssured", Type: "gt"}

	// ErrMaturityCalculationRequestSumAssuredRequiredValidation is returned when the SumAssured is required but not provided.
	ErrMaturityCalculationRequestSumAssuredRequiredValidation = govaliderrors.ValidationError{Reason: "field SumAssured is required", Path: "MaturityCalculationRequest.SumAssured", Type: "required"}

	// ErrMaturityCalculationRequestPolicyTermGTValidation is the error returned when the value of the field is less than the 0.
	ErrMaturityCalculationRequestPolicyTermGTValidation = govaliderrors.ValidationError{Reason: "field PolicyTerm must be greater than 0", Path: "MaturityCalculationRequest.PolicyTerm", Type: "gt"}

	// ErrMaturityCalculationRequestPolicyTermRequiredValidation is returned when the PolicyTerm is required but not provided.
	ErrMaturityCalculationRequestPolicyTermRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyTerm is required", Path: "MaturityCalculationRequest.PolicyTerm", Type: "required"}
)

func ValidateMaturityCalculationRequest(t *MaturityCalculationRequest) error {
	if t == nil {
		return ErrNilMaturityCalculationRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProductCode == "" {
		err := ErrMaturityCalculationRequestProductCodeRequiredValidation
		err.Value = t.ProductCode
		errs = append(errs, err)
	}

	if !(t.SumAssured > 0) {
		err := ErrMaturityCalculationRequestSumAssuredGTValidation
		err.Value = t.SumAssured
		errs = append(errs, err)
	}

	if t.SumAssured == 0.0 {
		err := ErrMaturityCalculationRequestSumAssuredRequiredValidation
		err.Value = t.SumAssured
		errs = append(errs, err)
	}

	if !(t.PolicyTerm > 0) {
		err := ErrMaturityCalculationRequestPolicyTermGTValidation
		err.Value = t.PolicyTerm
		errs = append(errs, err)
	}

	if t.PolicyTerm == 0 {
		err := ErrMaturityCalculationRequestPolicyTermRequiredValidation
		err.Value = t.PolicyTerm
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*MaturityCalculationRequest)(nil)

func (t *MaturityCalculationRequest) Validate() error {
	return ValidateMaturityCalculationRequest(t)
}
