// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilBatchIDUri is returned when the BatchIDUri is nil.
	ErrNilBatchIDUri = errors.New("input BatchIDUri is nil")

	// ErrBatchIDUriBatchIDRequiredValidation is returned when the BatchID is required but not provided.
	ErrBatchIDUriBatchIDRequiredValidation = govaliderrors.ValidationError{Reason: "field BatchID is required", Path: "BatchIDUri.BatchID", Type: "required"}
)

func ValidateBatchIDUri(t *BatchIDUri) error {
	if t == nil {
		return ErrNilBatchIDUri
	}

	var errs govaliderrors.ValidationErrors

	if t.BatchID == 0 {
		err := ErrBatchIDUriBatchIDRequiredValidation
		err.Value = t.BatchID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*BatchIDUri)(nil)

func (t *BatchIDUri) Validate() error {
	return ValidateBatchIDUri(t)
}
