// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilProposerDetailsRequest is returned when the ProposerDetailsRequest is nil.
	ErrNilProposerDetailsRequest = errors.New("input ProposerDetailsRequest is nil")

	// ErrProposerDetailsRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrProposerDetailsRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "ProposerDetailsRequest.ProposalID", Type: "required"}

	// ErrProposerDetailsRequestGenderOneofValidation is the error returned when the field is not one of the allowed values.
	ErrProposerDetailsRequestGenderOneofValidation = govaliderrors.ValidationError{Reason: "field Gender must be one of MALE FEMALE OTHER", Path: "ProposerDetailsRequest.Gender", Type: "oneof"}

	// ErrProposerDetailsRequestEmailEmailValidation is the error returned when the field is not a valid email address.
	ErrProposerDetailsRequestEmailEmailValidation = govaliderrors.ValidationError{Reason: "field Email must be a valid email address", Path: "ProposerDetailsRequest.Email", Type: "email"}
)

func ValidateProposerDetailsRequest(t *ProposerDetailsRequest) error {
	if t == nil {
		return ErrNilProposerDetailsRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrProposerDetailsRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if t.Gender != "" && !(t.Gender == "MALE" || t.Gender == "FEMALE" || t.Gender == "OTHER") {
		err := ErrProposerDetailsRequestGenderOneofValidation
		err.Value = t.Gender
		errs = append(errs, err)
	}

	if t.Email != "" && !validationhelper.IsValidEmail(t.Email) {
		err := ErrProposerDetailsRequestEmailEmailValidation
		err.Value = t.Email
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ProposerDetailsRequest)(nil)

func (t *ProposerDetailsRequest) Validate() error {
	return ValidateProposerDetailsRequest(t)
}
