// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilMissingDocumentCreateRequest is returned when the MissingDocumentCreateRequest is nil.
	ErrNilMissingDocumentCreateRequest = errors.New("input MissingDocumentCreateRequest is nil")

	// ErrMissingDocumentCreateRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrMissingDocumentCreateRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "MissingDocumentCreateRequest.ProposalID", Type: "required"}

	// ErrMissingDocumentCreateRequestDocumentTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrMissingDocumentCreateRequestDocumentTypeOneofValidation = govaliderrors.ValidationError{Reason: "field DocumentType must be one of PROPOSAL_FORM DOB_PROOF ADDRESS_PROOF PHOTO_ID MEDICAL_REPORT PAYMENT_COPY HEALTH_DECLARATION PHOTO INCOME_PROOF EMPLOYMENT_PROOF OTHER", Path: "MissingDocumentCreateRequest.DocumentType", Type: "oneof"}

	// ErrMissingDocumentCreateRequestDocumentTypeRequiredValidation is returned when the DocumentType is required but not provided.
	ErrMissingDocumentCreateRequestDocumentTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field DocumentType is required", Path: "MissingDocumentCreateRequest.DocumentType", Type: "required"}

	// ErrMissingDocumentCreateRequestStageOneofValidation is the error returned when the field is not one of the allowed values.
	ErrMissingDocumentCreateRequestStageOneofValidation = govaliderrors.ValidationError{Reason: "field Stage must be one of QC_REVIEW APPROVAL", Path: "MissingDocumentCreateRequest.Stage", Type: "oneof"}

	// ErrMissingDocumentCreateRequestStageRequiredValidation is returned when the Stage is required but not provided.
	ErrMissingDocumentCreateRequestStageRequiredValidation = govaliderrors.ValidationError{Reason: "field Stage is required", Path: "MissingDocumentCreateRequest.Stage", Type: "required"}

	// ErrMissingDocumentCreateRequestNotedByRequiredValidation is returned when the NotedBy is required but not provided.
	ErrMissingDocumentCreateRequestNotedByRequiredValidation = govaliderrors.ValidationError{Reason: "field NotedBy is required", Path: "MissingDocumentCreateRequest.NotedBy", Type: "required"}
)

func ValidateMissingDocumentCreateRequest(t *MissingDocumentCreateRequest) error {
	if t == nil {
		return ErrNilMissingDocumentCreateRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrMissingDocumentCreateRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if !(t.DocumentType == "PROPOSAL_FORM" || t.DocumentType == "DOB_PROOF" || t.DocumentType == "ADDRESS_PROOF" || t.DocumentType == "PHOTO_ID" || t.DocumentType == "MEDICAL_REPORT" || t.DocumentType == "PAYMENT_COPY" || t.DocumentType == "HEALTH_DECLARATION" || t.DocumentType == "PHOTO" || t.DocumentType == "INCOME_PROOF" || t.DocumentType == "EMPLOYMENT_PROOF" || t.DocumentType == "OTHER") {
		err := ErrMissingDocumentCreateRequestDocumentTypeOneofValidation
		err.Value = t.DocumentType
		errs = append(errs, err)
	}

	if t.DocumentType == "" {
		err := ErrMissingDocumentCreateRequestDocumentTypeRequiredValidation
		err.Value = t.DocumentType
		errs = append(errs, err)
	}

	if !(t.Stage == "QC_REVIEW" || t.Stage == "APPROVAL") {
		err := ErrMissingDocumentCreateRequestStageOneofValidation
		err.Value = t.Stage
		errs = append(errs, err)
	}

	if t.Stage == "" {
		err := ErrMissingDocumentCreateRequestStageRequiredValidation
		err.Value = t.Stage
		errs = append(errs, err)
	}

	if t.NotedBy == 0 {
		err := ErrMissingDocumentCreateRequestNotedByRequiredValidation
		err.Value = t.NotedBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*MissingDocumentCreateRequest)(nil)

func (t *MissingDocumentCreateRequest) Validate() error {
	return ValidateMissingDocumentCreateRequest(t)
}
