// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilAadhaarVerifyOTPRequest is returned when the AadhaarVerifyOTPRequest is nil.
	ErrNilAadhaarVerifyOTPRequest = errors.New("input AadhaarVerifyOTPRequest is nil")

	// ErrAadhaarVerifyOTPRequestTransactionIDRequiredValidation is returned when the TransactionID is required but not provided.
	ErrAadhaarVerifyOTPRequestTransactionIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TransactionID is required", Path: "AadhaarVerifyOTPRequest.TransactionID", Type: "required"}

	// ErrAadhaarVerifyOTPRequestOTPLengthValidation is the error returned when the length of the field is not exactly 6.
	ErrAadhaarVerifyOTPRequestOTPLengthValidation = govaliderrors.ValidationError{Reason: "field OTP length must be exactly 6", Path: "AadhaarVerifyOTPRequest.OTP", Type: "length"}

	// ErrAadhaarVerifyOTPRequestOTPRequiredValidation is returned when the OTP is required but not provided.
	ErrAadhaarVerifyOTPRequestOTPRequiredValidation = govaliderrors.ValidationError{Reason: "field OTP is required", Path: "AadhaarVerifyOTPRequest.OTP", Type: "required"}
)

func ValidateAadhaarVerifyOTPRequest(t *AadhaarVerifyOTPRequest) error {
	if t == nil {
		return ErrNilAadhaarVerifyOTPRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TransactionID == "" {
		err := ErrAadhaarVerifyOTPRequestTransactionIDRequiredValidation
		err.Value = t.TransactionID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.OTP) != 6 {
		err := ErrAadhaarVerifyOTPRequestOTPLengthValidation
		err.Value = t.OTP
		errs = append(errs, err)
	}

	if t.OTP == "" {
		err := ErrAadhaarVerifyOTPRequestOTPRequiredValidation
		err.Value = t.OTP
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*AadhaarVerifyOTPRequest)(nil)

func (t *AadhaarVerifyOTPRequest) Validate() error {
	return ValidateAadhaarVerifyOTPRequest(t)
}
