// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilQuoteGenerateRequest is returned when the QuoteGenerateRequest is nil.
	ErrNilQuoteGenerateRequest = errors.New("input QuoteGenerateRequest is nil")

	// ErrQuoteGenerateRequestProductCodeRequiredValidation is returned when the ProductCode is required but not provided.
	ErrQuoteGenerateRequestProductCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field ProductCode is required", Path: "QuoteGenerateRequest.ProductCode", Type: "required"}

	// ErrQuoteGenerateRequestDateOfCalculationRequiredValidation is returned when the DateOfCalculation is required but not provided.
	ErrQuoteGenerateRequestDateOfCalculationRequiredValidation = govaliderrors.ValidationError{Reason: "field DateOfCalculation is required", Path: "QuoteGenerateRequest.DateOfCalculation", Type: "required"}

	// ErrQuoteGenerateRequestPeriodicityRequiredValidation is returned when the Periodicity is required but not provided.
	ErrQuoteGenerateRequestPeriodicityRequiredValidation = govaliderrors.ValidationError{Reason: "field Periodicity is required", Path: "QuoteGenerateRequest.Periodicity", Type: "required"}

	// ErrQuoteGenerateRequestSumAssuredGTValidation is the error returned when the value of the field is less than the 0.
	ErrQuoteGenerateRequestSumAssuredGTValidation = govaliderrors.ValidationError{Reason: "field SumAssured must be greater than 0", Path: "QuoteGenerateRequest.SumAssured", Type: "gt"}

	// ErrQuoteGenerateRequestSumAssuredRequiredValidation is returned when the SumAssured is required but not provided.
	ErrQuoteGenerateRequestSumAssuredRequiredValidation = govaliderrors.ValidationError{Reason: "field SumAssured is required", Path: "QuoteGenerateRequest.SumAssured", Type: "required"}

	// ErrQuoteGenerateRequestPolicyTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrQuoteGenerateRequestPolicyTypeOneofValidation = govaliderrors.ValidationError{Reason: "field PolicyType must be one of PLI RPLI", Path: "QuoteGenerateRequest.PolicyType", Type: "oneof"}

	// ErrQuoteGenerateRequestPolicyTypeRequiredValidation is returned when the PolicyType is required but not provided.
	ErrQuoteGenerateRequestPolicyTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyType is required", Path: "QuoteGenerateRequest.PolicyType", Type: "required"}

	// ErrQuoteGenerateRequestChannelOneofValidation is the error returned when the field is not one of the allowed values.
	ErrQuoteGenerateRequestChannelOneofValidation = govaliderrors.ValidationError{Reason: "field Channel must be one of DIRECT AGENCY WEB MOBILE POS CSC", Path: "QuoteGenerateRequest.Channel", Type: "oneof"}

	// ErrQuoteGenerateRequestChannelRequiredValidation is returned when the Channel is required but not provided.
	ErrQuoteGenerateRequestChannelRequiredValidation = govaliderrors.ValidationError{Reason: "field Channel is required", Path: "QuoteGenerateRequest.Channel", Type: "required"}

	// ErrQuoteGenerateRequestCreatedByRequiredValidation is returned when the CreatedBy is required but not provided.
	ErrQuoteGenerateRequestCreatedByRequiredValidation = govaliderrors.ValidationError{Reason: "field CreatedBy is required", Path: "QuoteGenerateRequest.CreatedBy", Type: "required"}
)

func ValidateQuoteGenerateRequest(t *QuoteGenerateRequest) error {
	if t == nil {
		return ErrNilQuoteGenerateRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProductCode == "" {
		err := ErrQuoteGenerateRequestProductCodeRequiredValidation
		err.Value = t.ProductCode
		errs = append(errs, err)
	}

	if t.DateOfCalculation == "" {
		err := ErrQuoteGenerateRequestDateOfCalculationRequiredValidation
		err.Value = t.DateOfCalculation
		errs = append(errs, err)
	}

	if t.Periodicity == "" {
		err := ErrQuoteGenerateRequestPeriodicityRequiredValidation
		err.Value = t.Periodicity
		errs = append(errs, err)
	}

	if !(t.SumAssured > 0) {
		err := ErrQuoteGenerateRequestSumAssuredGTValidation
		err.Value = t.SumAssured
		errs = append(errs, err)
	}

	if t.SumAssured == 0 {
		err := ErrQuoteGenerateRequestSumAssuredRequiredValidation
		err.Value = t.SumAssured
		errs = append(errs, err)
	}

	if !(t.PolicyType == "PLI" || t.PolicyType == "RPLI") {
		err := ErrQuoteGenerateRequestPolicyTypeOneofValidation
		err.Value = t.PolicyType
		errs = append(errs, err)
	}

	if t.PolicyType == "" {
		err := ErrQuoteGenerateRequestPolicyTypeRequiredValidation
		err.Value = t.PolicyType
		errs = append(errs, err)
	}

	if !(t.Channel == "DIRECT" || t.Channel == "AGENCY" || t.Channel == "WEB" || t.Channel == "MOBILE" || t.Channel == "POS" || t.Channel == "CSC") {
		err := ErrQuoteGenerateRequestChannelOneofValidation
		err.Value = t.Channel
		errs = append(errs, err)
	}

	if t.Channel == "" {
		err := ErrQuoteGenerateRequestChannelRequiredValidation
		err.Value = t.Channel
		errs = append(errs, err)
	}

	if t.CreatedBy == 0 {
		err := ErrQuoteGenerateRequestCreatedByRequiredValidation
		err.Value = t.CreatedBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*QuoteGenerateRequest)(nil)

func (t *QuoteGenerateRequest) Validate() error {
	return ValidateQuoteGenerateRequest(t)
}
