// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilDeclarationRequest is returned when the DeclarationRequest is nil.
	ErrNilDeclarationRequest = errors.New("input DeclarationRequest is nil")

	// ErrDeclarationRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrDeclarationRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "DeclarationRequest.ProposalID", Type: "required"}

	// ErrDeclarationRequestIsAgreedRequiredValidation is returned when the IsAgreed is required but not provided.
	ErrDeclarationRequestIsAgreedRequiredValidation = govaliderrors.ValidationError{Reason: "field IsAgreed is required", Path: "DeclarationRequest.IsAgreed", Type: "required"}
)

func ValidateDeclarationRequest(t *DeclarationRequest) error {
	if t == nil {
		return ErrNilDeclarationRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrDeclarationRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if t.IsAgreed == false {
		err := ErrDeclarationRequestIsAgreedRequiredValidation
		err.Value = t.IsAgreed
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*DeclarationRequest)(nil)

func (t *DeclarationRequest) Validate() error {
	return ValidateDeclarationRequest(t)
}
