// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilProposalIndexingRequest is returned when the ProposalIndexingRequest is nil.
	ErrNilProposalIndexingRequest = errors.New("input ProposalIndexingRequest is nil")

	// ErrProposalIndexingRequestPolicyTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrProposalIndexingRequestPolicyTypeOneofValidation = govaliderrors.ValidationError{Reason: "field PolicyType must be one of PLI RPLI", Path: "ProposalIndexingRequest.PolicyType", Type: "oneof"}

	// ErrProposalIndexingRequestPolicyTypeRequiredValidation is returned when the PolicyType is required but not provided.
	ErrProposalIndexingRequestPolicyTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyType is required", Path: "ProposalIndexingRequest.PolicyType", Type: "required"}

	// ErrProposalIndexingRequestProductCodeRequiredValidation is returned when the ProductCode is required but not provided.
	ErrProposalIndexingRequestProductCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field ProductCode is required", Path: "ProposalIndexingRequest.ProductCode", Type: "required"}

	// ErrProposalIndexingRequestInsurantNameRequiredValidation is returned when the InsurantName is required but not provided.
	ErrProposalIndexingRequestInsurantNameRequiredValidation = govaliderrors.ValidationError{Reason: "field InsurantName is required", Path: "ProposalIndexingRequest.InsurantName", Type: "required"}

	// ErrProposalIndexingRequestEntryPathOneofValidation is the error returned when the field is not one of the allowed values.
	ErrProposalIndexingRequestEntryPathOneofValidation = govaliderrors.ValidationError{Reason: "field EntryPath must be one of WITHOUT_AADHAAR WITH_AADHAAR BULK_UPLOAD QUOTE_CONVERSION", Path: "ProposalIndexingRequest.EntryPath", Type: "oneof"}

	// ErrProposalIndexingRequestEntryPathRequiredValidation is returned when the EntryPath is required but not provided.
	ErrProposalIndexingRequestEntryPathRequiredValidation = govaliderrors.ValidationError{Reason: "field EntryPath is required", Path: "ProposalIndexingRequest.EntryPath", Type: "required"}

	// ErrProposalIndexingRequestPOCodeRequiredValidation is returned when the POCode is required but not provided.
	ErrProposalIndexingRequestPOCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field POCode is required", Path: "ProposalIndexingRequest.POCode", Type: "required"}

	// ErrProposalIndexingRequestIssueCircleRequiredValidation is returned when the IssueCircle is required but not provided.
	ErrProposalIndexingRequestIssueCircleRequiredValidation = govaliderrors.ValidationError{Reason: "field IssueCircle is required", Path: "ProposalIndexingRequest.IssueCircle", Type: "required"}

	// ErrProposalIndexingRequestIssueHORequiredValidation is returned when the IssueHO is required but not provided.
	ErrProposalIndexingRequestIssueHORequiredValidation = govaliderrors.ValidationError{Reason: "field IssueHO is required", Path: "ProposalIndexingRequest.IssueHO", Type: "required"}

	// ErrProposalIndexingRequestIssuePostOfficeRequiredValidation is returned when the IssuePostOffice is required but not provided.
	ErrProposalIndexingRequestIssuePostOfficeRequiredValidation = govaliderrors.ValidationError{Reason: "field IssuePostOffice is required", Path: "ProposalIndexingRequest.IssuePostOffice", Type: "required"}

	// ErrProposalIndexingRequestChannelOneofValidation is the error returned when the field is not one of the allowed values.
	ErrProposalIndexingRequestChannelOneofValidation = govaliderrors.ValidationError{Reason: "field Channel must be one of DIRECT AGENCY WEB MOBILE POS CSC", Path: "ProposalIndexingRequest.Channel", Type: "oneof"}

	// ErrProposalIndexingRequestChannelRequiredValidation is returned when the Channel is required but not provided.
	ErrProposalIndexingRequestChannelRequiredValidation = govaliderrors.ValidationError{Reason: "field Channel is required", Path: "ProposalIndexingRequest.Channel", Type: "required"}

	// ErrProposalIndexingRequestSumAssuredGTValidation is the error returned when the value of the field is less than the 0.
	ErrProposalIndexingRequestSumAssuredGTValidation = govaliderrors.ValidationError{Reason: "field SumAssured must be greater than 0", Path: "ProposalIndexingRequest.SumAssured", Type: "gt"}

	// ErrProposalIndexingRequestSumAssuredRequiredValidation is returned when the SumAssured is required but not provided.
	ErrProposalIndexingRequestSumAssuredRequiredValidation = govaliderrors.ValidationError{Reason: "field SumAssured is required", Path: "ProposalIndexingRequest.SumAssured", Type: "required"}

	// ErrProposalIndexingRequestPolicyTermGTValidation is the error returned when the value of the field is less than the 0.
	ErrProposalIndexingRequestPolicyTermGTValidation = govaliderrors.ValidationError{Reason: "field PolicyTerm must be greater than 0", Path: "ProposalIndexingRequest.PolicyTerm", Type: "gt"}

	// ErrProposalIndexingRequestPolicyTermRequiredValidation is returned when the PolicyTerm is required but not provided.
	ErrProposalIndexingRequestPolicyTermRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyTerm is required", Path: "ProposalIndexingRequest.PolicyTerm", Type: "required"}

	// ErrProposalIndexingRequestPremiumPaymentFrequencyOneofValidation is the error returned when the field is not one of the allowed values.
	ErrProposalIndexingRequestPremiumPaymentFrequencyOneofValidation = govaliderrors.ValidationError{Reason: "field PremiumPaymentFrequency must be one of MONTHLY QUARTERLY HALF_YEARLY YEARLY SINGLE", Path: "ProposalIndexingRequest.PremiumPaymentFrequency", Type: "oneof"}

	// ErrProposalIndexingRequestPremiumPaymentFrequencyRequiredValidation is returned when the PremiumPaymentFrequency is required but not provided.
	ErrProposalIndexingRequestPremiumPaymentFrequencyRequiredValidation = govaliderrors.ValidationError{Reason: "field PremiumPaymentFrequency is required", Path: "ProposalIndexingRequest.PremiumPaymentFrequency", Type: "required"}

	// ErrProposalIndexingRequestBasePremiumGTValidation is the error returned when the value of the field is less than the 0.
	ErrProposalIndexingRequestBasePremiumGTValidation = govaliderrors.ValidationError{Reason: "field BasePremium must be greater than 0", Path: "ProposalIndexingRequest.BasePremium", Type: "gt"}

	// ErrProposalIndexingRequestBasePremiumRequiredValidation is returned when the BasePremium is required but not provided.
	ErrProposalIndexingRequestBasePremiumRequiredValidation = govaliderrors.ValidationError{Reason: "field BasePremium is required", Path: "ProposalIndexingRequest.BasePremium", Type: "required"}

	// ErrProposalIndexingRequestTotalPremiumGTValidation is the error returned when the value of the field is less than the 0.
	ErrProposalIndexingRequestTotalPremiumGTValidation = govaliderrors.ValidationError{Reason: "field TotalPremium must be greater than 0", Path: "ProposalIndexingRequest.TotalPremium", Type: "gt"}

	// ErrProposalIndexingRequestTotalPremiumRequiredValidation is returned when the TotalPremium is required but not provided.
	ErrProposalIndexingRequestTotalPremiumRequiredValidation = govaliderrors.ValidationError{Reason: "field TotalPremium is required", Path: "ProposalIndexingRequest.TotalPremium", Type: "required"}

	// ErrProposalIndexingRequestCreatedByRequiredValidation is returned when the CreatedBy is required but not provided.
	ErrProposalIndexingRequestCreatedByRequiredValidation = govaliderrors.ValidationError{Reason: "field CreatedBy is required", Path: "ProposalIndexingRequest.CreatedBy", Type: "required"}
)

func ValidateProposalIndexingRequest(t *ProposalIndexingRequest) error {
	if t == nil {
		return ErrNilProposalIndexingRequest
	}

	var errs govaliderrors.ValidationErrors

	if !(t.PolicyType == "PLI" || t.PolicyType == "RPLI") {
		err := ErrProposalIndexingRequestPolicyTypeOneofValidation
		err.Value = t.PolicyType
		errs = append(errs, err)
	}

	if t.PolicyType == "" {
		err := ErrProposalIndexingRequestPolicyTypeRequiredValidation
		err.Value = t.PolicyType
		errs = append(errs, err)
	}

	if t.ProductCode == "" {
		err := ErrProposalIndexingRequestProductCodeRequiredValidation
		err.Value = t.ProductCode
		errs = append(errs, err)
	}

	if t.InsurantName == "" {
		err := ErrProposalIndexingRequestInsurantNameRequiredValidation
		err.Value = t.InsurantName
		errs = append(errs, err)
	}

	if !(t.EntryPath == "WITHOUT_AADHAAR" || t.EntryPath == "WITH_AADHAAR" || t.EntryPath == "BULK_UPLOAD" || t.EntryPath == "QUOTE_CONVERSION") {
		err := ErrProposalIndexingRequestEntryPathOneofValidation
		err.Value = t.EntryPath
		errs = append(errs, err)
	}

	if t.EntryPath == "" {
		err := ErrProposalIndexingRequestEntryPathRequiredValidation
		err.Value = t.EntryPath
		errs = append(errs, err)
	}

	if t.POCode == "" {
		err := ErrProposalIndexingRequestPOCodeRequiredValidation
		err.Value = t.POCode
		errs = append(errs, err)
	}

	if t.IssueCircle == "" {
		err := ErrProposalIndexingRequestIssueCircleRequiredValidation
		err.Value = t.IssueCircle
		errs = append(errs, err)
	}

	if t.IssueHO == "" {
		err := ErrProposalIndexingRequestIssueHORequiredValidation
		err.Value = t.IssueHO
		errs = append(errs, err)
	}

	if t.IssuePostOffice == "" {
		err := ErrProposalIndexingRequestIssuePostOfficeRequiredValidation
		err.Value = t.IssuePostOffice
		errs = append(errs, err)
	}

	if !(t.Channel == "DIRECT" || t.Channel == "AGENCY" || t.Channel == "WEB" || t.Channel == "MOBILE" || t.Channel == "POS" || t.Channel == "CSC") {
		err := ErrProposalIndexingRequestChannelOneofValidation
		err.Value = t.Channel
		errs = append(errs, err)
	}

	if t.Channel == "" {
		err := ErrProposalIndexingRequestChannelRequiredValidation
		err.Value = t.Channel
		errs = append(errs, err)
	}

	if !(t.SumAssured > 0) {
		err := ErrProposalIndexingRequestSumAssuredGTValidation
		err.Value = t.SumAssured
		errs = append(errs, err)
	}

	if t.SumAssured == 0.0 {
		err := ErrProposalIndexingRequestSumAssuredRequiredValidation
		err.Value = t.SumAssured
		errs = append(errs, err)
	}

	if !(t.PolicyTerm > 0) {
		err := ErrProposalIndexingRequestPolicyTermGTValidation
		err.Value = t.PolicyTerm
		errs = append(errs, err)
	}

	if t.PolicyTerm == 0 {
		err := ErrProposalIndexingRequestPolicyTermRequiredValidation
		err.Value = t.PolicyTerm
		errs = append(errs, err)
	}

	if !(t.PremiumPaymentFrequency == "MONTHLY" || t.PremiumPaymentFrequency == "QUARTERLY" || t.PremiumPaymentFrequency == "HALF_YEARLY" || t.PremiumPaymentFrequency == "YEARLY" || t.PremiumPaymentFrequency == "SINGLE") {
		err := ErrProposalIndexingRequestPremiumPaymentFrequencyOneofValidation
		err.Value = t.PremiumPaymentFrequency
		errs = append(errs, err)
	}

	if t.PremiumPaymentFrequency == "" {
		err := ErrProposalIndexingRequestPremiumPaymentFrequencyRequiredValidation
		err.Value = t.PremiumPaymentFrequency
		errs = append(errs, err)
	}

	if !(t.BasePremium > 0) {
		err := ErrProposalIndexingRequestBasePremiumGTValidation
		err.Value = t.BasePremium
		errs = append(errs, err)
	}

	if t.BasePremium == 0.0 {
		err := ErrProposalIndexingRequestBasePremiumRequiredValidation
		err.Value = t.BasePremium
		errs = append(errs, err)
	}

	if !(t.TotalPremium > 0) {
		err := ErrProposalIndexingRequestTotalPremiumGTValidation
		err.Value = t.TotalPremium
		errs = append(errs, err)
	}

	if t.TotalPremium == 0.0 {
		err := ErrProposalIndexingRequestTotalPremiumRequiredValidation
		err.Value = t.TotalPremium
		errs = append(errs, err)
	}

	if t.CreatedBy == 0 {
		err := ErrProposalIndexingRequestCreatedByRequiredValidation
		err.Value = t.CreatedBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ProposalIndexingRequest)(nil)

func (t *ProposalIndexingRequest) Validate() error {
	return ValidateProposalIndexingRequest(t)
}
