// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilFLCRefundCalculationRequest is returned when the FLCRefundCalculationRequest is nil.
	ErrNilFLCRefundCalculationRequest = errors.New("input FLCRefundCalculationRequest is nil")

	// ErrFLCRefundCalculationRequestPremiumPaidGTValidation is the error returned when the value of the field is less than the 0.
	ErrFLCRefundCalculationRequestPremiumPaidGTValidation = govaliderrors.ValidationError{Reason: "field PremiumPaid must be greater than 0", Path: "FLCRefundCalculationRequest.PremiumPaid", Type: "gt"}

	// ErrFLCRefundCalculationRequestPremiumPaidRequiredValidation is returned when the PremiumPaid is required but not provided.
	ErrFLCRefundCalculationRequestPremiumPaidRequiredValidation = govaliderrors.ValidationError{Reason: "field PremiumPaid is required", Path: "FLCRefundCalculationRequest.PremiumPaid", Type: "required"}

	// ErrFLCRefundCalculationRequestDaysOfCoverageGTValidation is the error returned when the value of the field is less than the 0.
	ErrFLCRefundCalculationRequestDaysOfCoverageGTValidation = govaliderrors.ValidationError{Reason: "field DaysOfCoverage must be greater than 0", Path: "FLCRefundCalculationRequest.DaysOfCoverage", Type: "gt"}

	// ErrFLCRefundCalculationRequestDaysOfCoverageRequiredValidation is returned when the DaysOfCoverage is required but not provided.
	ErrFLCRefundCalculationRequestDaysOfCoverageRequiredValidation = govaliderrors.ValidationError{Reason: "field DaysOfCoverage is required", Path: "FLCRefundCalculationRequest.DaysOfCoverage", Type: "required"}

	// ErrFLCRefundCalculationRequestBasePremiumGTValidation is the error returned when the value of the field is less than the 0.
	ErrFLCRefundCalculationRequestBasePremiumGTValidation = govaliderrors.ValidationError{Reason: "field BasePremium must be greater than 0", Path: "FLCRefundCalculationRequest.BasePremium", Type: "gt"}

	// ErrFLCRefundCalculationRequestBasePremiumRequiredValidation is returned when the BasePremium is required but not provided.
	ErrFLCRefundCalculationRequestBasePremiumRequiredValidation = govaliderrors.ValidationError{Reason: "field BasePremium is required", Path: "FLCRefundCalculationRequest.BasePremium", Type: "required"}
)

func ValidateFLCRefundCalculationRequest(t *FLCRefundCalculationRequest) error {
	if t == nil {
		return ErrNilFLCRefundCalculationRequest
	}

	var errs govaliderrors.ValidationErrors

	if !(t.PremiumPaid > 0) {
		err := ErrFLCRefundCalculationRequestPremiumPaidGTValidation
		err.Value = t.PremiumPaid
		errs = append(errs, err)
	}

	if t.PremiumPaid == 0.0 {
		err := ErrFLCRefundCalculationRequestPremiumPaidRequiredValidation
		err.Value = t.PremiumPaid
		errs = append(errs, err)
	}

	if !(t.DaysOfCoverage > 0) {
		err := ErrFLCRefundCalculationRequestDaysOfCoverageGTValidation
		err.Value = t.DaysOfCoverage
		errs = append(errs, err)
	}

	if t.DaysOfCoverage == 0 {
		err := ErrFLCRefundCalculationRequestDaysOfCoverageRequiredValidation
		err.Value = t.DaysOfCoverage
		errs = append(errs, err)
	}

	if !(t.BasePremium > 0) {
		err := ErrFLCRefundCalculationRequestBasePremiumGTValidation
		err.Value = t.BasePremium
		errs = append(errs, err)
	}

	if t.BasePremium == 0.0 {
		err := ErrFLCRefundCalculationRequestBasePremiumRequiredValidation
		err.Value = t.BasePremium
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*FLCRefundCalculationRequest)(nil)

func (t *FLCRefundCalculationRequest) Validate() error {
	return ValidateFLCRefundCalculationRequest(t)
}
