// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilEmploymentInput is returned when the EmploymentInput is nil.
	ErrNilEmploymentInput = errors.New("input EmploymentInput is nil")

	// ErrEmploymentInputOccupationMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrEmploymentInputOccupationMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Occupation must have a maximum length of 100", Path: "EmploymentInput.Occupation", Type: "maxlength"}

	// ErrEmploymentInputOccupationMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrEmploymentInputOccupationMinLengthValidation = govaliderrors.ValidationError{Reason: "field Occupation must have a minimum length of 1", Path: "EmploymentInput.Occupation", Type: "minlength"}

	// ErrEmploymentInputOccupationRequiredValidation is returned when the Occupation is required but not provided.
	ErrEmploymentInputOccupationRequiredValidation = govaliderrors.ValidationError{Reason: "field Occupation is required", Path: "EmploymentInput.Occupation", Type: "required"}

	// ErrEmploymentInputPAODDOCodeMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrEmploymentInputPAODDOCodeMaxLengthValidation = govaliderrors.ValidationError{Reason: "field PAODDOCode must have a maximum length of 50", Path: "EmploymentInput.PAODDOCode", Type: "maxlength"}

	// ErrEmploymentInputPAODDOCodeMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrEmploymentInputPAODDOCodeMinLengthValidation = govaliderrors.ValidationError{Reason: "field PAODDOCode must have a minimum length of 1", Path: "EmploymentInput.PAODDOCode", Type: "minlength"}

	// ErrEmploymentInputOrganizationMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 200.
	ErrEmploymentInputOrganizationMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Organization must have a maximum length of 200", Path: "EmploymentInput.Organization", Type: "maxlength"}

	// ErrEmploymentInputDesignationMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrEmploymentInputDesignationMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Designation must have a maximum length of 100", Path: "EmploymentInput.Designation", Type: "maxlength"}

	// ErrEmploymentInputSuperiorDesignationMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrEmploymentInputSuperiorDesignationMaxLengthValidation = govaliderrors.ValidationError{Reason: "field SuperiorDesignation must have a maximum length of 100", Path: "EmploymentInput.SuperiorDesignation", Type: "maxlength"}

	// ErrEmploymentInputQualificationMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrEmploymentInputQualificationMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Qualification must have a maximum length of 100", Path: "EmploymentInput.Qualification", Type: "maxlength"}
)

func ValidateEmploymentInput(t *EmploymentInput) error {
	if t == nil {
		return ErrNilEmploymentInput
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.Occupation) > 100 {
		err := ErrEmploymentInputOccupationMaxLengthValidation
		err.Value = t.Occupation
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.Occupation) < 1 {
		err := ErrEmploymentInputOccupationMinLengthValidation
		err.Value = t.Occupation
		errs = append(errs, err)
	}

	if t.Occupation == "" {
		err := ErrEmploymentInputOccupationRequiredValidation
		err.Value = t.Occupation
		errs = append(errs, err)
	}

	if t.PAODDOCode != "" && utf8.RuneCountInString(t.PAODDOCode) > 50 {
		err := ErrEmploymentInputPAODDOCodeMaxLengthValidation
		err.Value = t.PAODDOCode
		errs = append(errs, err)
	}

	if t.PAODDOCode != "" && utf8.RuneCountInString(t.PAODDOCode) < 1 {
		err := ErrEmploymentInputPAODDOCodeMinLengthValidation
		err.Value = t.PAODDOCode
		errs = append(errs, err)
	}

	if t.Organization != "" && utf8.RuneCountInString(t.Organization) > 200 {
		err := ErrEmploymentInputOrganizationMaxLengthValidation
		err.Value = t.Organization
		errs = append(errs, err)
	}

	if t.Designation != "" && utf8.RuneCountInString(t.Designation) > 100 {
		err := ErrEmploymentInputDesignationMaxLengthValidation
		err.Value = t.Designation
		errs = append(errs, err)
	}

	if t.SuperiorDesignation != "" && utf8.RuneCountInString(t.SuperiorDesignation) > 100 {
		err := ErrEmploymentInputSuperiorDesignationMaxLengthValidation
		err.Value = t.SuperiorDesignation
		errs = append(errs, err)
	}

	if t.Qualification != "" && utf8.RuneCountInString(t.Qualification) > 100 {
		err := ErrEmploymentInputQualificationMaxLengthValidation
		err.Value = t.Qualification
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*EmploymentInput)(nil)

func (t *EmploymentInput) Validate() error {
	return ValidateEmploymentInput(t)
}
