// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilFLCStatusUri is returned when the FLCStatusUri is nil.
	ErrNilFLCStatusUri = errors.New("input FLCStatusUri is nil")

	// ErrFLCStatusUriProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrFLCStatusUriProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "FLCStatusUri.ProposalID", Type: "required"}
)

func ValidateFLCStatusUri(t *FLCStatusUri) error {
	if t == nil {
		return ErrNilFLCStatusUri
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrFLCStatusUriProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*FLCStatusUri)(nil)

func (t *FLCStatusUri) Validate() error {
	return ValidateFLCStatusUri(t)
}
