// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilDateChainValidationRequest is returned when the DateChainValidationRequest is nil.
	ErrNilDateChainValidationRequest = errors.New("input DateChainValidationRequest is nil")

	// ErrDateChainValidationRequestDeclarationDateDateValidation is the error returned when the field is not a valid date (dd/mm/yy).
	ErrDateChainValidationRequestDeclarationDateDateValidation = govaliderrors.ValidationError{Reason: "field DeclarationDate must be a valid date (dd/mm/yy)", Path: "DateChainValidationRequest.DeclarationDate", Type: "date"}

	// ErrDateChainValidationRequestDeclarationDateRequiredValidation is returned when the DeclarationDate is required but not provided.
	ErrDateChainValidationRequestDeclarationDateRequiredValidation = govaliderrors.ValidationError{Reason: "field DeclarationDate is required", Path: "DateChainValidationRequest.DeclarationDate", Type: "required"}

	// ErrDateChainValidationRequestReceiptDateDateValidation is the error returned when the field is not a valid date (dd/mm/yy).
	ErrDateChainValidationRequestReceiptDateDateValidation = govaliderrors.ValidationError{Reason: "field ReceiptDate must be a valid date (dd/mm/yy)", Path: "DateChainValidationRequest.ReceiptDate", Type: "date"}

	// ErrDateChainValidationRequestReceiptDateRequiredValidation is returned when the ReceiptDate is required but not provided.
	ErrDateChainValidationRequestReceiptDateRequiredValidation = govaliderrors.ValidationError{Reason: "field ReceiptDate is required", Path: "DateChainValidationRequest.ReceiptDate", Type: "required"}

	// ErrDateChainValidationRequestIndexingDateDateValidation is the error returned when the field is not a valid date (dd/mm/yy).
	ErrDateChainValidationRequestIndexingDateDateValidation = govaliderrors.ValidationError{Reason: "field IndexingDate must be a valid date (dd/mm/yy)", Path: "DateChainValidationRequest.IndexingDate", Type: "date"}

	// ErrDateChainValidationRequestIndexingDateRequiredValidation is returned when the IndexingDate is required but not provided.
	ErrDateChainValidationRequestIndexingDateRequiredValidation = govaliderrors.ValidationError{Reason: "field IndexingDate is required", Path: "DateChainValidationRequest.IndexingDate", Type: "required"}

	// ErrDateChainValidationRequestProposalDateDateValidation is the error returned when the field is not a valid date (dd/mm/yy).
	ErrDateChainValidationRequestProposalDateDateValidation = govaliderrors.ValidationError{Reason: "field ProposalDate must be a valid date (dd/mm/yy)", Path: "DateChainValidationRequest.ProposalDate", Type: "date"}

	// ErrDateChainValidationRequestProposalDateRequiredValidation is returned when the ProposalDate is required but not provided.
	ErrDateChainValidationRequestProposalDateRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalDate is required", Path: "DateChainValidationRequest.ProposalDate", Type: "required"}
)

func ValidateDateChainValidationRequest(t *DateChainValidationRequest) error {
	if t == nil {
		return ErrNilDateChainValidationRequest
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsValidDateDDMMYY(t.DeclarationDate) {
		err := ErrDateChainValidationRequestDeclarationDateDateValidation
		err.Value = t.DeclarationDate
		errs = append(errs, err)
	}

	if t.DeclarationDate == "" {
		err := ErrDateChainValidationRequestDeclarationDateRequiredValidation
		err.Value = t.DeclarationDate
		errs = append(errs, err)
	}

	if !validationhelper.IsValidDateDDMMYY(t.ReceiptDate) {
		err := ErrDateChainValidationRequestReceiptDateDateValidation
		err.Value = t.ReceiptDate
		errs = append(errs, err)
	}

	if t.ReceiptDate == "" {
		err := ErrDateChainValidationRequestReceiptDateRequiredValidation
		err.Value = t.ReceiptDate
		errs = append(errs, err)
	}

	if !validationhelper.IsValidDateDDMMYY(t.IndexingDate) {
		err := ErrDateChainValidationRequestIndexingDateDateValidation
		err.Value = t.IndexingDate
		errs = append(errs, err)
	}

	if t.IndexingDate == "" {
		err := ErrDateChainValidationRequestIndexingDateRequiredValidation
		err.Value = t.IndexingDate
		errs = append(errs, err)
	}

	if !validationhelper.IsValidDateDDMMYY(t.ProposalDate) {
		err := ErrDateChainValidationRequestProposalDateDateValidation
		err.Value = t.ProposalDate
		errs = append(errs, err)
	}

	if t.ProposalDate == "" {
		err := ErrDateChainValidationRequestProposalDateRequiredValidation
		err.Value = t.ProposalDate
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*DateChainValidationRequest)(nil)

func (t *DateChainValidationRequest) Validate() error {
	return ValidateDateChainValidationRequest(t)
}
