// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilFirstPremiumRequest is returned when the FirstPremiumRequest is nil.
	ErrNilFirstPremiumRequest = errors.New("input FirstPremiumRequest is nil")

	// ErrFirstPremiumRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrFirstPremiumRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "FirstPremiumRequest.ProposalID", Type: "required"}

	// ErrFirstPremiumRequestPaymentMethodOneofValidation is the error returned when the field is not one of the allowed values.
	ErrFirstPremiumRequestPaymentMethodOneofValidation = govaliderrors.ValidationError{Reason: "field PaymentMethod must be one of CASH CHEQUE DD ONLINE POSB NACH", Path: "FirstPremiumRequest.PaymentMethod", Type: "oneof"}

	// ErrFirstPremiumRequestPaymentMethodRequiredValidation is returned when the PaymentMethod is required but not provided.
	ErrFirstPremiumRequestPaymentMethodRequiredValidation = govaliderrors.ValidationError{Reason: "field PaymentMethod is required", Path: "FirstPremiumRequest.PaymentMethod", Type: "required"}

	// ErrFirstPremiumRequestAmountGTValidation is the error returned when the value of the field is less than the 0.
	ErrFirstPremiumRequestAmountGTValidation = govaliderrors.ValidationError{Reason: "field Amount must be greater than 0", Path: "FirstPremiumRequest.Amount", Type: "gt"}

	// ErrFirstPremiumRequestAmountRequiredValidation is returned when the Amount is required but not provided.
	ErrFirstPremiumRequestAmountRequiredValidation = govaliderrors.ValidationError{Reason: "field Amount is required", Path: "FirstPremiumRequest.Amount", Type: "required"}

	// ErrFirstPremiumRequestReceiptNumberRequiredValidation is returned when the ReceiptNumber is required but not provided.
	ErrFirstPremiumRequestReceiptNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field ReceiptNumber is required", Path: "FirstPremiumRequest.ReceiptNumber", Type: "required"}

	// ErrFirstPremiumRequestPaymentDateRequiredValidation is returned when the PaymentDate is required but not provided.
	ErrFirstPremiumRequestPaymentDateRequiredValidation = govaliderrors.ValidationError{Reason: "field PaymentDate is required", Path: "FirstPremiumRequest.PaymentDate", Type: "required"}
)

func ValidateFirstPremiumRequest(t *FirstPremiumRequest) error {
	if t == nil {
		return ErrNilFirstPremiumRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrFirstPremiumRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if !(t.PaymentMethod == "CASH" || t.PaymentMethod == "CHEQUE" || t.PaymentMethod == "DD" || t.PaymentMethod == "ONLINE" || t.PaymentMethod == "POSB" || t.PaymentMethod == "NACH") {
		err := ErrFirstPremiumRequestPaymentMethodOneofValidation
		err.Value = t.PaymentMethod
		errs = append(errs, err)
	}

	if t.PaymentMethod == "" {
		err := ErrFirstPremiumRequestPaymentMethodRequiredValidation
		err.Value = t.PaymentMethod
		errs = append(errs, err)
	}

	if !(t.Amount > 0) {
		err := ErrFirstPremiumRequestAmountGTValidation
		err.Value = t.Amount
		errs = append(errs, err)
	}

	if t.Amount == 0.0 {
		err := ErrFirstPremiumRequestAmountRequiredValidation
		err.Value = t.Amount
		errs = append(errs, err)
	}

	if t.ReceiptNumber == "" {
		err := ErrFirstPremiumRequestReceiptNumberRequiredValidation
		err.Value = t.ReceiptNumber
		errs = append(errs, err)
	}

	if t.PaymentDate == "" {
		err := ErrFirstPremiumRequestPaymentDateRequiredValidation
		err.Value = t.PaymentDate
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*FirstPremiumRequest)(nil)

func (t *FirstPremiumRequest) Validate() error {
	return ValidateFirstPremiumRequest(t)
}
