// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilWorkflowSignalRequest is returned when the WorkflowSignalRequest is nil.
	ErrNilWorkflowSignalRequest = errors.New("input WorkflowSignalRequest is nil")

	// ErrWorkflowSignalRequestWorkflowIDRequiredValidation is returned when the WorkflowID is required but not provided.
	ErrWorkflowSignalRequestWorkflowIDRequiredValidation = govaliderrors.ValidationError{Reason: "field WorkflowID is required", Path: "WorkflowSignalRequest.WorkflowID", Type: "required"}

	// ErrWorkflowSignalRequestSignalNameOneofValidation is the error returned when the field is not one of the allowed values.
	ErrWorkflowSignalRequestSignalNameOneofValidation = govaliderrors.ValidationError{Reason: "field SignalName must be one of qr-decision medical-result approver-decision payment-received cpc-resubmit flc-cancel-request death-notification", Path: "WorkflowSignalRequest.SignalName", Type: "oneof"}

	// ErrWorkflowSignalRequestSignalNameRequiredValidation is returned when the SignalName is required but not provided.
	ErrWorkflowSignalRequestSignalNameRequiredValidation = govaliderrors.ValidationError{Reason: "field SignalName is required", Path: "WorkflowSignalRequest.SignalName", Type: "required"}
)

func ValidateWorkflowSignalRequest(t *WorkflowSignalRequest) error {
	if t == nil {
		return ErrNilWorkflowSignalRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.WorkflowID == "" {
		err := ErrWorkflowSignalRequestWorkflowIDRequiredValidation
		err.Value = t.WorkflowID
		errs = append(errs, err)
	}

	if !(t.SignalName == "qr-decision" || t.SignalName == "medical-result" || t.SignalName == "approver-decision" || t.SignalName == "payment-received" || t.SignalName == "cpc-resubmit" || t.SignalName == "flc-cancel-request" || t.SignalName == "death-notification") {
		err := ErrWorkflowSignalRequestSignalNameOneofValidation
		err.Value = t.SignalName
		errs = append(errs, err)
	}

	if t.SignalName == "" {
		err := ErrWorkflowSignalRequestSignalNameRequiredValidation
		err.Value = t.SignalName
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*WorkflowSignalRequest)(nil)

func (t *WorkflowSignalRequest) Validate() error {
	return ValidateWorkflowSignalRequest(t)
}
