// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilGetProposalSectionRequest is returned when the GetProposalSectionRequest is nil.
	ErrNilGetProposalSectionRequest = errors.New("input GetProposalSectionRequest is nil")

	// ErrGetProposalSectionRequestSectionRequiredValidation is returned when the Section is required but not provided.
	ErrGetProposalSectionRequestSectionRequiredValidation = govaliderrors.ValidationError{Reason: "field Section is required", Path: "GetProposalSectionRequest.Section", Type: "required"}
)

func ValidateGetProposalSectionRequest(t *GetProposalSectionRequest) error {
	if t == nil {
		return ErrNilGetProposalSectionRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.Section == "" {
		err := ErrGetProposalSectionRequestSectionRequiredValidation
		err.Value = t.Section
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*GetProposalSectionRequest)(nil)

func (t *GetProposalSectionRequest) Validate() error {
	return ValidateGetProposalSectionRequest(t)
}
