// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilAadhaarInitiateRequest is returned when the AadhaarInitiateRequest is nil.
	ErrNilAadhaarInitiateRequest = errors.New("input AadhaarInitiateRequest is nil")

	// ErrAadhaarInitiateRequestAadhaarNumberRequiredValidation is returned when the AadhaarNumber is required but not provided.
	ErrAadhaarInitiateRequestAadhaarNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field AadhaarNumber is required", Path: "AadhaarInitiateRequest.AadhaarNumber", Type: "required"}

	// ErrAadhaarInitiateRequestPurposeRequiredValidation is returned when the Purpose is required but not provided.
	ErrAadhaarInitiateRequestPurposeRequiredValidation = govaliderrors.ValidationError{Reason: "field Purpose is required", Path: "AadhaarInitiateRequest.Purpose", Type: "required"}
)

func ValidateAadhaarInitiateRequest(t *AadhaarInitiateRequest) error {
	if t == nil {
		return ErrNilAadhaarInitiateRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.AadhaarNumber == "" {
		err := ErrAadhaarInitiateRequestAadhaarNumberRequiredValidation
		err.Value = t.AadhaarNumber
		errs = append(errs, err)
	}

	if t.Purpose == "" {
		err := ErrAadhaarInitiateRequestPurposeRequiredValidation
		err.Value = t.Purpose
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*AadhaarInitiateRequest)(nil)

func (t *AadhaarInitiateRequest) Validate() error {
	return ValidateAadhaarInitiateRequest(t)
}
