// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilContactInput is returned when the ContactInput is nil.
	ErrNilContactInput = errors.New("input ContactInput is nil")

	// ErrContactInputContactTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrContactInputContactTypeOneofValidation = govaliderrors.ValidationError{Reason: "field ContactType must be one of MOBILE EMAIL LANDLINE", Path: "ContactInput.ContactType", Type: "oneof"}

	// ErrContactInputContactTypeRequiredValidation is returned when the ContactType is required but not provided.
	ErrContactInputContactTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field ContactType is required", Path: "ContactInput.ContactType", Type: "required"}

	// ErrContactInputContactValueMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrContactInputContactValueMaxLengthValidation = govaliderrors.ValidationError{Reason: "field ContactValue must have a maximum length of 100", Path: "ContactInput.ContactValue", Type: "maxlength"}

	// ErrContactInputContactValueMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrContactInputContactValueMinLengthValidation = govaliderrors.ValidationError{Reason: "field ContactValue must have a minimum length of 1", Path: "ContactInput.ContactValue", Type: "minlength"}

	// ErrContactInputContactValueRequiredValidation is returned when the ContactValue is required but not provided.
	ErrContactInputContactValueRequiredValidation = govaliderrors.ValidationError{Reason: "field ContactValue is required", Path: "ContactInput.ContactValue", Type: "required"}
)

func ValidateContactInput(t *ContactInput) error {
	if t == nil {
		return ErrNilContactInput
	}

	var errs govaliderrors.ValidationErrors

	if !(t.ContactType == "MOBILE" || t.ContactType == "EMAIL" || t.ContactType == "LANDLINE") {
		err := ErrContactInputContactTypeOneofValidation
		err.Value = t.ContactType
		errs = append(errs, err)
	}

	if t.ContactType == "" {
		err := ErrContactInputContactTypeRequiredValidation
		err.Value = t.ContactType
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.ContactValue) > 100 {
		err := ErrContactInputContactValueMaxLengthValidation
		err.Value = t.ContactValue
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.ContactValue) < 1 {
		err := ErrContactInputContactValueMinLengthValidation
		err.Value = t.ContactValue
		errs = append(errs, err)
	}

	if t.ContactValue == "" {
		err := ErrContactInputContactValueRequiredValidation
		err.Value = t.ContactValue
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ContactInput)(nil)

func (t *ContactInput) Validate() error {
	return ValidateContactInput(t)
}
