// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilAggregateSACheckRequest is returned when the AggregateSACheckRequest is nil.
	ErrNilAggregateSACheckRequest = errors.New("input AggregateSACheckRequest is nil")

	// ErrAggregateSACheckRequestCustomerIDRequiredValidation is returned when the CustomerID is required but not provided.
	ErrAggregateSACheckRequestCustomerIDRequiredValidation = govaliderrors.ValidationError{Reason: "field CustomerID is required", Path: "AggregateSACheckRequest.CustomerID", Type: "required"}

	// ErrAggregateSACheckRequestPolicyTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrAggregateSACheckRequestPolicyTypeOneofValidation = govaliderrors.ValidationError{Reason: "field PolicyType must be one of PLI RPLI", Path: "AggregateSACheckRequest.PolicyType", Type: "oneof"}

	// ErrAggregateSACheckRequestProposedSAGTValidation is the error returned when the value of the field is less than the 0.
	ErrAggregateSACheckRequestProposedSAGTValidation = govaliderrors.ValidationError{Reason: "field ProposedSA must be greater than 0", Path: "AggregateSACheckRequest.ProposedSA", Type: "gt"}

	// ErrAggregateSACheckRequestProposedSARequiredValidation is returned when the ProposedSA is required but not provided.
	ErrAggregateSACheckRequestProposedSARequiredValidation = govaliderrors.ValidationError{Reason: "field ProposedSA is required", Path: "AggregateSACheckRequest.ProposedSA", Type: "required"}
)

func ValidateAggregateSACheckRequest(t *AggregateSACheckRequest) error {
	if t == nil {
		return ErrNilAggregateSACheckRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.CustomerID == 0 {
		err := ErrAggregateSACheckRequestCustomerIDRequiredValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if t.PolicyType != "" && !(t.PolicyType == "PLI" || t.PolicyType == "RPLI") {
		err := ErrAggregateSACheckRequestPolicyTypeOneofValidation
		err.Value = t.PolicyType
		errs = append(errs, err)
	}

	if !(t.ProposedSA > 0) {
		err := ErrAggregateSACheckRequestProposedSAGTValidation
		err.Value = t.ProposedSA
		errs = append(errs, err)
	}

	if t.ProposedSA == 0.0 {
		err := ErrAggregateSACheckRequestProposedSARequiredValidation
		err.Value = t.ProposedSA
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*AggregateSACheckRequest)(nil)

func (t *AggregateSACheckRequest) Validate() error {
	return ValidateAggregateSACheckRequest(t)
}
