// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilMissingDocumentResolveRequest is returned when the MissingDocumentResolveRequest is nil.
	ErrNilMissingDocumentResolveRequest = errors.New("input MissingDocumentResolveRequest is nil")

	// ErrMissingDocumentResolveRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrMissingDocumentResolveRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "MissingDocumentResolveRequest.ProposalID", Type: "required"}

	// ErrMissingDocumentResolveRequestMissingDocIDRequiredValidation is returned when the MissingDocID is required but not provided.
	ErrMissingDocumentResolveRequestMissingDocIDRequiredValidation = govaliderrors.ValidationError{Reason: "field MissingDocID is required", Path: "MissingDocumentResolveRequest.MissingDocID", Type: "required"}

	// ErrMissingDocumentResolveRequestStatusOneofValidation is the error returned when the field is not one of the allowed values.
	ErrMissingDocumentResolveRequestStatusOneofValidation = govaliderrors.ValidationError{Reason: "field Status must be one of UPLOADED WAIVED", Path: "MissingDocumentResolveRequest.Status", Type: "oneof"}

	// ErrMissingDocumentResolveRequestStatusRequiredValidation is returned when the Status is required but not provided.
	ErrMissingDocumentResolveRequestStatusRequiredValidation = govaliderrors.ValidationError{Reason: "field Status is required", Path: "MissingDocumentResolveRequest.Status", Type: "required"}

	// ErrMissingDocumentResolveRequestResolvedByRequiredValidation is returned when the ResolvedBy is required but not provided.
	ErrMissingDocumentResolveRequestResolvedByRequiredValidation = govaliderrors.ValidationError{Reason: "field ResolvedBy is required", Path: "MissingDocumentResolveRequest.ResolvedBy", Type: "required"}
)

func ValidateMissingDocumentResolveRequest(t *MissingDocumentResolveRequest) error {
	if t == nil {
		return ErrNilMissingDocumentResolveRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrMissingDocumentResolveRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if t.MissingDocID == 0 {
		err := ErrMissingDocumentResolveRequestMissingDocIDRequiredValidation
		err.Value = t.MissingDocID
		errs = append(errs, err)
	}

	if !(t.Status == "UPLOADED" || t.Status == "WAIVED") {
		err := ErrMissingDocumentResolveRequestStatusOneofValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if t.Status == "" {
		err := ErrMissingDocumentResolveRequestStatusRequiredValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if t.ResolvedBy == 0 {
		err := ErrMissingDocumentResolveRequestResolvedByRequiredValidation
		err.Value = t.ResolvedBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*MissingDocumentResolveRequest)(nil)

func (t *MissingDocumentResolveRequest) Validate() error {
	return ValidateMissingDocumentResolveRequest(t)
}
