// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilSubmitForQCRequest is returned when the SubmitForQCRequest is nil.
	ErrNilSubmitForQCRequest = errors.New("input SubmitForQCRequest is nil")

	// ErrSubmitForQCRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrSubmitForQCRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "SubmitForQCRequest.ProposalID", Type: "required"}

	// ErrSubmitForQCRequestDataEntryByRequiredValidation is returned when the DataEntryBy is required but not provided.
	ErrSubmitForQCRequestDataEntryByRequiredValidation = govaliderrors.ValidationError{Reason: "field DataEntryBy is required", Path: "SubmitForQCRequest.DataEntryBy", Type: "required"}
)

func ValidateSubmitForQCRequest(t *SubmitForQCRequest) error {
	if t == nil {
		return ErrNilSubmitForQCRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrSubmitForQCRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if t.DataEntryBy == 0 {
		err := ErrSubmitForQCRequestDataEntryByRequiredValidation
		err.Value = t.DataEntryBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*SubmitForQCRequest)(nil)

func (t *SubmitForQCRequest) Validate() error {
	return ValidateSubmitForQCRequest(t)
}
