// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilDateInfo is returned when the DateInfo is nil.
	ErrNilDateInfo = errors.New("input DateInfo is nil")

	// ErrDateInfoDeclarationDateDateValidation is the error returned when the field is not a valid date (dd/mm/yy).
	ErrDateInfoDeclarationDateDateValidation = govaliderrors.ValidationError{Reason: "field DeclarationDate must be a valid date (dd/mm/yy)", Path: "DateInfo.DeclarationDate", Type: "date"}

	// ErrDateInfoDeclarationDateRequiredValidation is returned when the DeclarationDate is required but not provided.
	ErrDateInfoDeclarationDateRequiredValidation = govaliderrors.ValidationError{Reason: "field DeclarationDate is required", Path: "DateInfo.DeclarationDate", Type: "required"}

	// ErrDateInfoReceiptDateDateValidation is the error returned when the field is not a valid date (dd/mm/yy).
	ErrDateInfoReceiptDateDateValidation = govaliderrors.ValidationError{Reason: "field ReceiptDate must be a valid date (dd/mm/yy)", Path: "DateInfo.ReceiptDate", Type: "date"}

	// ErrDateInfoReceiptDateRequiredValidation is returned when the ReceiptDate is required but not provided.
	ErrDateInfoReceiptDateRequiredValidation = govaliderrors.ValidationError{Reason: "field ReceiptDate is required", Path: "DateInfo.ReceiptDate", Type: "required"}

	// ErrDateInfoIndexingDateDateValidation is the error returned when the field is not a valid date (dd/mm/yy).
	ErrDateInfoIndexingDateDateValidation = govaliderrors.ValidationError{Reason: "field IndexingDate must be a valid date (dd/mm/yy)", Path: "DateInfo.IndexingDate", Type: "date"}

	// ErrDateInfoIndexingDateRequiredValidation is returned when the IndexingDate is required but not provided.
	ErrDateInfoIndexingDateRequiredValidation = govaliderrors.ValidationError{Reason: "field IndexingDate is required", Path: "DateInfo.IndexingDate", Type: "required"}

	// ErrDateInfoProposalDateDateValidation is the error returned when the field is not a valid date (dd/mm/yy).
	ErrDateInfoProposalDateDateValidation = govaliderrors.ValidationError{Reason: "field ProposalDate must be a valid date (dd/mm/yy)", Path: "DateInfo.ProposalDate", Type: "date"}

	// ErrDateInfoProposalDateRequiredValidation is returned when the ProposalDate is required but not provided.
	ErrDateInfoProposalDateRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalDate is required", Path: "DateInfo.ProposalDate", Type: "required"}
)

func ValidateDateInfo(t *DateInfo) error {
	if t == nil {
		return ErrNilDateInfo
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsValidDateDDMMYY(t.DeclarationDate) {
		err := ErrDateInfoDeclarationDateDateValidation
		err.Value = t.DeclarationDate
		errs = append(errs, err)
	}

	if t.DeclarationDate == "" {
		err := ErrDateInfoDeclarationDateRequiredValidation
		err.Value = t.DeclarationDate
		errs = append(errs, err)
	}

	if !validationhelper.IsValidDateDDMMYY(t.ReceiptDate) {
		err := ErrDateInfoReceiptDateDateValidation
		err.Value = t.ReceiptDate
		errs = append(errs, err)
	}

	if t.ReceiptDate == "" {
		err := ErrDateInfoReceiptDateRequiredValidation
		err.Value = t.ReceiptDate
		errs = append(errs, err)
	}

	if !validationhelper.IsValidDateDDMMYY(t.IndexingDate) {
		err := ErrDateInfoIndexingDateDateValidation
		err.Value = t.IndexingDate
		errs = append(errs, err)
	}

	if t.IndexingDate == "" {
		err := ErrDateInfoIndexingDateRequiredValidation
		err.Value = t.IndexingDate
		errs = append(errs, err)
	}

	if !validationhelper.IsValidDateDDMMYY(t.ProposalDate) {
		err := ErrDateInfoProposalDateDateValidation
		err.Value = t.ProposalDate
		errs = append(errs, err)
	}

	if t.ProposalDate == "" {
		err := ErrDateInfoProposalDateRequiredValidation
		err.Value = t.ProposalDate
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*DateInfo)(nil)

func (t *DateInfo) Validate() error {
	return ValidateDateInfo(t)
}
