// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilCustomerAddressInput is returned when the CustomerAddressInput is nil.
	ErrNilCustomerAddressInput = errors.New("input CustomerAddressInput is nil")

	// ErrCustomerAddressInputActionRequiredValidation is returned when the Action is required but not provided.
	ErrCustomerAddressInputActionRequiredValidation = govaliderrors.ValidationError{Reason: "field Action is required", Path: "CustomerAddressInput.Action", Type: "required"}

	// ErrCustomerAddressInputCustomerIDRequiredValidation is returned when the CustomerID is required but not provided.
	ErrCustomerAddressInputCustomerIDRequiredValidation = govaliderrors.ValidationError{Reason: "field CustomerID is required", Path: "CustomerAddressInput.CustomerID", Type: "required"}
)

func ValidateCustomerAddressInput(t *CustomerAddressInput) error {
	if t == nil {
		return ErrNilCustomerAddressInput
	}

	var errs govaliderrors.ValidationErrors

	if t.Action == "" {
		err := ErrCustomerAddressInputActionRequiredValidation
		err.Value = t.Action
		errs = append(errs, err)
	}

	if t.CustomerID == "" {
		err := ErrCustomerAddressInputCustomerIDRequiredValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CustomerAddressInput)(nil)

func (t *CustomerAddressInput) Validate() error {
	return ValidateCustomerAddressInput(t)
}
