// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilAdditionalInfoInput is returned when the AdditionalInfoInput is nil.
	ErrNilAdditionalInfoInput = errors.New("input AdditionalInfoInput is nil")

	// ErrAdditionalInfoInputMarksOfId1MaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrAdditionalInfoInputMarksOfId1MaxLengthValidation = govaliderrors.ValidationError{Reason: "field MarksOfId1 must have a maximum length of 100", Path: "AdditionalInfoInput.MarksOfId1", Type: "maxlength"}

	// ErrAdditionalInfoInputMarksOfId2MaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrAdditionalInfoInputMarksOfId2MaxLengthValidation = govaliderrors.ValidationError{Reason: "field MarksOfId2 must have a maximum length of 100", Path: "AdditionalInfoInput.MarksOfId2", Type: "maxlength"}

	// ErrAdditionalInfoInputExpectedMonthOfDeliveryMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 20.
	ErrAdditionalInfoInputExpectedMonthOfDeliveryMaxLengthValidation = govaliderrors.ValidationError{Reason: "field ExpectedMonthOfDelivery must have a maximum length of 20", Path: "AdditionalInfoInput.ExpectedMonthOfDelivery", Type: "maxlength"}

	// ErrAdditionalInfoInputMothersNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrAdditionalInfoInputMothersNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field MothersName must have a maximum length of 100", Path: "AdditionalInfoInput.MothersName", Type: "maxlength"}

	// ErrAdditionalInfoInputParentsPolicyNumberMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrAdditionalInfoInputParentsPolicyNumberMaxLengthValidation = govaliderrors.ValidationError{Reason: "field ParentsPolicyNumber must have a maximum length of 50", Path: "AdditionalInfoInput.ParentsPolicyNumber", Type: "maxlength"}

	// ErrAdditionalInfoInputAgeProofTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrAdditionalInfoInputAgeProofTypeOneofValidation = govaliderrors.ValidationError{Reason: "field AgeProofType must be one of BIRTH_CERTIFICATE SCHOOL_CERTIFICATE PASSPORT AADHAAR", Path: "AdditionalInfoInput.AgeProofType", Type: "oneof"}

	// ErrAdditionalInfoInputPolicyTakenUnderOneofValidation is the error returned when the field is not one of the allowed values.
	ErrAdditionalInfoInputPolicyTakenUnderOneofValidation = govaliderrors.ValidationError{Reason: "field PolicyTakenUnder must be one of HUF MWPA", Path: "AdditionalInfoInput.PolicyTakenUnder", Type: "oneof"}
)

func ValidateAdditionalInfoInput(t *AdditionalInfoInput) error {
	if t == nil {
		return ErrNilAdditionalInfoInput
	}

	var errs govaliderrors.ValidationErrors

	if t.MarksOfId1 != "" && utf8.RuneCountInString(t.MarksOfId1) > 100 {
		err := ErrAdditionalInfoInputMarksOfId1MaxLengthValidation
		err.Value = t.MarksOfId1
		errs = append(errs, err)
	}

	if t.MarksOfId2 != "" && utf8.RuneCountInString(t.MarksOfId2) > 100 {
		err := ErrAdditionalInfoInputMarksOfId2MaxLengthValidation
		err.Value = t.MarksOfId2
		errs = append(errs, err)
	}

	if t.ExpectedMonthOfDelivery != "" && utf8.RuneCountInString(t.ExpectedMonthOfDelivery) > 20 {
		err := ErrAdditionalInfoInputExpectedMonthOfDeliveryMaxLengthValidation
		err.Value = t.ExpectedMonthOfDelivery
		errs = append(errs, err)
	}

	if t.MothersName != "" && utf8.RuneCountInString(t.MothersName) > 100 {
		err := ErrAdditionalInfoInputMothersNameMaxLengthValidation
		err.Value = t.MothersName
		errs = append(errs, err)
	}

	if t.ParentsPolicyNumber != "" && utf8.RuneCountInString(t.ParentsPolicyNumber) > 50 {
		err := ErrAdditionalInfoInputParentsPolicyNumberMaxLengthValidation
		err.Value = t.ParentsPolicyNumber
		errs = append(errs, err)
	}

	if t.AgeProofType != "" && !(t.AgeProofType == "BIRTH_CERTIFICATE" || t.AgeProofType == "SCHOOL_CERTIFICATE" || t.AgeProofType == "PASSPORT" || t.AgeProofType == "AADHAAR") {
		err := ErrAdditionalInfoInputAgeProofTypeOneofValidation
		err.Value = t.AgeProofType
		errs = append(errs, err)
	}

	if t.PolicyTakenUnder != "" && !(t.PolicyTakenUnder == "HUF" || t.PolicyTakenUnder == "MWPA") {
		err := ErrAdditionalInfoInputPolicyTakenUnderOneofValidation
		err.Value = t.PolicyTakenUnder
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*AdditionalInfoInput)(nil)

func (t *AdditionalInfoInput) Validate() error {
	return ValidateAdditionalInfoInput(t)
}
