// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilNomineeDTO is returned when the NomineeDTO is nil.
	ErrNilNomineeDTO = errors.New("input NomineeDTO is nil")

	// ErrNomineeDTOSalutationRequiredValidation is returned when the Salutation is required but not provided.
	ErrNomineeDTOSalutationRequiredValidation = govaliderrors.ValidationError{Reason: "field Salutation is required", Path: "NomineeDTO.Salutation", Type: "required"}

	// ErrNomineeDTOFirstNameRequiredValidation is returned when the FirstName is required but not provided.
	ErrNomineeDTOFirstNameRequiredValidation = govaliderrors.ValidationError{Reason: "field FirstName is required", Path: "NomineeDTO.FirstName", Type: "required"}

	// ErrNomineeDTOLastNameRequiredValidation is returned when the LastName is required but not provided.
	ErrNomineeDTOLastNameRequiredValidation = govaliderrors.ValidationError{Reason: "field LastName is required", Path: "NomineeDTO.LastName", Type: "required"}

	// ErrNomineeDTOGenderOneofValidation is the error returned when the field is not one of the allowed values.
	ErrNomineeDTOGenderOneofValidation = govaliderrors.ValidationError{Reason: "field Gender must be one of M F O", Path: "NomineeDTO.Gender", Type: "oneof"}

	// ErrNomineeDTOGenderRequiredValidation is returned when the Gender is required but not provided.
	ErrNomineeDTOGenderRequiredValidation = govaliderrors.ValidationError{Reason: "field Gender is required", Path: "NomineeDTO.Gender", Type: "required"}

	// ErrNomineeDTODateOfBirthDateValidation is the error returned when the field is not a valid date (dd/mm/yy).
	ErrNomineeDTODateOfBirthDateValidation = govaliderrors.ValidationError{Reason: "field DateOfBirth must be a valid date (dd/mm/yy)", Path: "NomineeDTO.DateOfBirth", Type: "date"}

	// ErrNomineeDTODateOfBirthRequiredValidation is returned when the DateOfBirth is required but not provided.
	ErrNomineeDTODateOfBirthRequiredValidation = govaliderrors.ValidationError{Reason: "field DateOfBirth is required", Path: "NomineeDTO.DateOfBirth", Type: "required"}

	// ErrNomineeDTORelationshipRequiredValidation is returned when the Relationship is required but not provided.
	ErrNomineeDTORelationshipRequiredValidation = govaliderrors.ValidationError{Reason: "field Relationship is required", Path: "NomineeDTO.Relationship", Type: "required"}

	// ErrNomineeDTOSharePercentageGTValidation is the error returned when the value of the field is less than the 0.
	ErrNomineeDTOSharePercentageGTValidation = govaliderrors.ValidationError{Reason: "field SharePercentage must be greater than 0", Path: "NomineeDTO.SharePercentage", Type: "gt"}

	// ErrNomineeDTOSharePercentageLTEValidation is the error returned when the value of the field is greater than 100.
	ErrNomineeDTOSharePercentageLTEValidation = govaliderrors.ValidationError{Reason: "field SharePercentage must be less than or equal to 100", Path: "NomineeDTO.SharePercentage", Type: "lte"}

	// ErrNomineeDTOSharePercentageRequiredValidation is returned when the SharePercentage is required but not provided.
	ErrNomineeDTOSharePercentageRequiredValidation = govaliderrors.ValidationError{Reason: "field SharePercentage is required", Path: "NomineeDTO.SharePercentage", Type: "required"}
)

func ValidateNomineeDTO(t *NomineeDTO) error {
	if t == nil {
		return ErrNilNomineeDTO
	}

	var errs govaliderrors.ValidationErrors

	if t.Salutation == "" {
		err := ErrNomineeDTOSalutationRequiredValidation
		err.Value = t.Salutation
		errs = append(errs, err)
	}

	if t.FirstName == "" {
		err := ErrNomineeDTOFirstNameRequiredValidation
		err.Value = t.FirstName
		errs = append(errs, err)
	}

	if t.LastName == "" {
		err := ErrNomineeDTOLastNameRequiredValidation
		err.Value = t.LastName
		errs = append(errs, err)
	}

	if !(t.Gender == "M" || t.Gender == "F" || t.Gender == "O") {
		err := ErrNomineeDTOGenderOneofValidation
		err.Value = t.Gender
		errs = append(errs, err)
	}

	if t.Gender == "" {
		err := ErrNomineeDTOGenderRequiredValidation
		err.Value = t.Gender
		errs = append(errs, err)
	}

	if !validationhelper.IsValidDateDDMMYY(t.DateOfBirth) {
		err := ErrNomineeDTODateOfBirthDateValidation
		err.Value = t.DateOfBirth
		errs = append(errs, err)
	}

	if t.DateOfBirth == "" {
		err := ErrNomineeDTODateOfBirthRequiredValidation
		err.Value = t.DateOfBirth
		errs = append(errs, err)
	}

	if t.Relationship == "" {
		err := ErrNomineeDTORelationshipRequiredValidation
		err.Value = t.Relationship
		errs = append(errs, err)
	}

	if !(t.SharePercentage > 0) {
		err := ErrNomineeDTOSharePercentageGTValidation
		err.Value = t.SharePercentage
		errs = append(errs, err)
	}

	if !(t.SharePercentage <= 100) {
		err := ErrNomineeDTOSharePercentageLTEValidation
		err.Value = t.SharePercentage
		errs = append(errs, err)
	}

	if t.SharePercentage == 0.0 {
		err := ErrNomineeDTOSharePercentageRequiredValidation
		err.Value = t.SharePercentage
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*NomineeDTO)(nil)

func (t *NomineeDTO) Validate() error {
	return ValidateNomineeDTO(t)
}
