// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilInsuredDetailsRequest is returned when the InsuredDetailsRequest is nil.
	ErrNilInsuredDetailsRequest = errors.New("input InsuredDetailsRequest is nil")

	// ErrInsuredDetailsRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrInsuredDetailsRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "InsuredDetailsRequest.ProposalID", Type: "required"}

	// ErrInsuredDetailsRequestCustomerIDRequiredValidation is returned when the CustomerID is required but not provided.
	ErrInsuredDetailsRequestCustomerIDRequiredValidation = govaliderrors.ValidationError{Reason: "field CustomerID is required", Path: "InsuredDetailsRequest.CustomerID", Type: "required"}

	// ErrInsuredDetailsRequestSalutationRequiredValidation is returned when the Salutation is required but not provided.
	ErrInsuredDetailsRequestSalutationRequiredValidation = govaliderrors.ValidationError{Reason: "field Salutation is required", Path: "InsuredDetailsRequest.Salutation", Type: "required"}

	// ErrInsuredDetailsRequestFirstNameRequiredValidation is returned when the FirstName is required but not provided.
	ErrInsuredDetailsRequestFirstNameRequiredValidation = govaliderrors.ValidationError{Reason: "field FirstName is required", Path: "InsuredDetailsRequest.FirstName", Type: "required"}

	// ErrInsuredDetailsRequestLastNameRequiredValidation is returned when the LastName is required but not provided.
	ErrInsuredDetailsRequestLastNameRequiredValidation = govaliderrors.ValidationError{Reason: "field LastName is required", Path: "InsuredDetailsRequest.LastName", Type: "required"}

	// ErrInsuredDetailsRequestGenderOneofValidation is the error returned when the field is not one of the allowed values.
	ErrInsuredDetailsRequestGenderOneofValidation = govaliderrors.ValidationError{Reason: "field Gender must be one of MALE FEMALE OTHER ALL", Path: "InsuredDetailsRequest.Gender", Type: "oneof"}

	// ErrInsuredDetailsRequestGenderRequiredValidation is returned when the Gender is required but not provided.
	ErrInsuredDetailsRequestGenderRequiredValidation = govaliderrors.ValidationError{Reason: "field Gender is required", Path: "InsuredDetailsRequest.Gender", Type: "required"}

	// ErrInsuredDetailsRequestDateOfBirthRequiredValidation is returned when the DateOfBirth is required but not provided.
	ErrInsuredDetailsRequestDateOfBirthRequiredValidation = govaliderrors.ValidationError{Reason: "field DateOfBirth is required", Path: "InsuredDetailsRequest.DateOfBirth", Type: "required"}

	// ErrInsuredDetailsRequestAddressLine1RequiredValidation is returned when the AddressLine1 is required but not provided.
	ErrInsuredDetailsRequestAddressLine1RequiredValidation = govaliderrors.ValidationError{Reason: "field AddressLine1 is required", Path: "InsuredDetailsRequest.AddressLine1", Type: "required"}

	// ErrInsuredDetailsRequestCityRequiredValidation is returned when the City is required but not provided.
	ErrInsuredDetailsRequestCityRequiredValidation = govaliderrors.ValidationError{Reason: "field City is required", Path: "InsuredDetailsRequest.City", Type: "required"}

	// ErrInsuredDetailsRequestStateRequiredValidation is returned when the State is required but not provided.
	ErrInsuredDetailsRequestStateRequiredValidation = govaliderrors.ValidationError{Reason: "field State is required", Path: "InsuredDetailsRequest.State", Type: "required"}

	// ErrInsuredDetailsRequestPinCodeRequiredValidation is returned when the PinCode is required but not provided.
	ErrInsuredDetailsRequestPinCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field PinCode is required", Path: "InsuredDetailsRequest.PinCode", Type: "required"}

	// ErrInsuredDetailsRequestMobileRequiredValidation is returned when the Mobile is required but not provided.
	ErrInsuredDetailsRequestMobileRequiredValidation = govaliderrors.ValidationError{Reason: "field Mobile is required", Path: "InsuredDetailsRequest.Mobile", Type: "required"}

	// ErrInsuredDetailsRequestEmailEmailValidation is the error returned when the field is not a valid email address.
	ErrInsuredDetailsRequestEmailEmailValidation = govaliderrors.ValidationError{Reason: "field Email must be a valid email address", Path: "InsuredDetailsRequest.Email", Type: "email"}
)

func ValidateInsuredDetailsRequest(t *InsuredDetailsRequest) error {
	if t == nil {
		return ErrNilInsuredDetailsRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrInsuredDetailsRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if t.CustomerID == 0 {
		err := ErrInsuredDetailsRequestCustomerIDRequiredValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if t.Salutation == "" {
		err := ErrInsuredDetailsRequestSalutationRequiredValidation
		err.Value = t.Salutation
		errs = append(errs, err)
	}

	if t.FirstName == "" {
		err := ErrInsuredDetailsRequestFirstNameRequiredValidation
		err.Value = t.FirstName
		errs = append(errs, err)
	}

	if t.LastName == "" {
		err := ErrInsuredDetailsRequestLastNameRequiredValidation
		err.Value = t.LastName
		errs = append(errs, err)
	}

	if !(t.Gender == "MALE" || t.Gender == "FEMALE" || t.Gender == "OTHER" || t.Gender == "ALL") {
		err := ErrInsuredDetailsRequestGenderOneofValidation
		err.Value = t.Gender
		errs = append(errs, err)
	}

	if t.Gender == "" {
		err := ErrInsuredDetailsRequestGenderRequiredValidation
		err.Value = t.Gender
		errs = append(errs, err)
	}

	if t.DateOfBirth == "" {
		err := ErrInsuredDetailsRequestDateOfBirthRequiredValidation
		err.Value = t.DateOfBirth
		errs = append(errs, err)
	}

	if t.AddressLine1 == "" {
		err := ErrInsuredDetailsRequestAddressLine1RequiredValidation
		err.Value = t.AddressLine1
		errs = append(errs, err)
	}

	if t.City == "" {
		err := ErrInsuredDetailsRequestCityRequiredValidation
		err.Value = t.City
		errs = append(errs, err)
	}

	if t.State == "" {
		err := ErrInsuredDetailsRequestStateRequiredValidation
		err.Value = t.State
		errs = append(errs, err)
	}

	if t.PinCode == "" {
		err := ErrInsuredDetailsRequestPinCodeRequiredValidation
		err.Value = t.PinCode
		errs = append(errs, err)
	}

	if t.Mobile == "" {
		err := ErrInsuredDetailsRequestMobileRequiredValidation
		err.Value = t.Mobile
		errs = append(errs, err)
	}

	if t.Email != "" && !validationhelper.IsValidEmail(t.Email) {
		err := ErrInsuredDetailsRequestEmailEmailValidation
		err.Value = t.Email
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*InsuredDetailsRequest)(nil)

func (t *InsuredDetailsRequest) Validate() error {
	return ValidateInsuredDetailsRequest(t)
}
