// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilPolicyDetailsRequest is returned when the PolicyDetailsRequest is nil.
	ErrNilPolicyDetailsRequest = errors.New("input PolicyDetailsRequest is nil")

	// ErrPolicyDetailsRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrPolicyDetailsRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "PolicyDetailsRequest.ProposalID", Type: "required"}

	// ErrPolicyDetailsRequestSumAssuredGTValidation is the error returned when the value of the field is less than the 0.
	ErrPolicyDetailsRequestSumAssuredGTValidation = govaliderrors.ValidationError{Reason: "field SumAssured must be greater than 0", Path: "PolicyDetailsRequest.SumAssured", Type: "gt"}

	// ErrPolicyDetailsRequestSumAssuredRequiredValidation is returned when the SumAssured is required but not provided.
	ErrPolicyDetailsRequestSumAssuredRequiredValidation = govaliderrors.ValidationError{Reason: "field SumAssured is required", Path: "PolicyDetailsRequest.SumAssured", Type: "required"}

	// ErrPolicyDetailsRequestPolicyTermGTValidation is the error returned when the value of the field is less than the 0.
	ErrPolicyDetailsRequestPolicyTermGTValidation = govaliderrors.ValidationError{Reason: "field PolicyTerm must be greater than 0", Path: "PolicyDetailsRequest.PolicyTerm", Type: "gt"}

	// ErrPolicyDetailsRequestPolicyTermRequiredValidation is returned when the PolicyTerm is required but not provided.
	ErrPolicyDetailsRequestPolicyTermRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyTerm is required", Path: "PolicyDetailsRequest.PolicyTerm", Type: "required"}

	// ErrPolicyDetailsRequestPremiumFrequencyRequiredValidation is returned when the PremiumFrequency is required but not provided.
	ErrPolicyDetailsRequestPremiumFrequencyRequiredValidation = govaliderrors.ValidationError{Reason: "field PremiumFrequency is required", Path: "PolicyDetailsRequest.PremiumFrequency", Type: "required"}

	// ErrPolicyDetailsRequestSubsequentPaymentModeRequiredValidation is returned when the SubsequentPaymentMode is required but not provided.
	ErrPolicyDetailsRequestSubsequentPaymentModeRequiredValidation = govaliderrors.ValidationError{Reason: "field SubsequentPaymentMode is required", Path: "PolicyDetailsRequest.SubsequentPaymentMode", Type: "required"}

	// ErrPolicyDetailsRequestAgeProofTypeRequiredValidation is returned when the AgeProofType is required but not provided.
	ErrPolicyDetailsRequestAgeProofTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field AgeProofType is required", Path: "PolicyDetailsRequest.AgeProofType", Type: "required"}
)

func ValidatePolicyDetailsRequest(t *PolicyDetailsRequest) error {
	if t == nil {
		return ErrNilPolicyDetailsRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrPolicyDetailsRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if !(t.SumAssured > 0) {
		err := ErrPolicyDetailsRequestSumAssuredGTValidation
		err.Value = t.SumAssured
		errs = append(errs, err)
	}

	if t.SumAssured == 0.0 {
		err := ErrPolicyDetailsRequestSumAssuredRequiredValidation
		err.Value = t.SumAssured
		errs = append(errs, err)
	}

	if !(t.PolicyTerm > 0) {
		err := ErrPolicyDetailsRequestPolicyTermGTValidation
		err.Value = t.PolicyTerm
		errs = append(errs, err)
	}

	if t.PolicyTerm == 0 {
		err := ErrPolicyDetailsRequestPolicyTermRequiredValidation
		err.Value = t.PolicyTerm
		errs = append(errs, err)
	}

	if t.PremiumFrequency == "" {
		err := ErrPolicyDetailsRequestPremiumFrequencyRequiredValidation
		err.Value = t.PremiumFrequency
		errs = append(errs, err)
	}

	if t.SubsequentPaymentMode == "" {
		err := ErrPolicyDetailsRequestSubsequentPaymentModeRequiredValidation
		err.Value = t.SubsequentPaymentMode
		errs = append(errs, err)
	}

	if t.AgeProofType == "" {
		err := ErrPolicyDetailsRequestAgeProofTypeRequiredValidation
		err.Value = t.AgeProofType
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*PolicyDetailsRequest)(nil)

func (t *PolicyDetailsRequest) Validate() error {
	return ValidatePolicyDetailsRequest(t)
}
