// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilMetadataRequest is returned when the MetadataRequest is nil.
	ErrNilMetadataRequest = errors.New("input MetadataRequest is nil")

	// ErrMetadataRequestPageGTEValidation is the error returned when the value of the field is less than 1.
	ErrMetadataRequestPageGTEValidation = govaliderrors.ValidationError{Reason: "field Page must be greater than or equal to 1", Path: "MetadataRequest.Page", Type: "gte"}

	// ErrMetadataRequestLimitGTEValidation is the error returned when the value of the field is less than 1.
	ErrMetadataRequestLimitGTEValidation = govaliderrors.ValidationError{Reason: "field Limit must be greater than or equal to 1", Path: "MetadataRequest.Limit", Type: "gte"}

	// ErrMetadataRequestLimitLTEValidation is the error returned when the value of the field is greater than 100.
	ErrMetadataRequestLimitLTEValidation = govaliderrors.ValidationError{Reason: "field Limit must be less than or equal to 100", Path: "MetadataRequest.Limit", Type: "lte"}
)

func ValidateMetadataRequest(t *MetadataRequest) error {
	if t == nil {
		return ErrNilMetadataRequest
	}

	var errs govaliderrors.ValidationErrors

	if !(t.Page >= 1) {
		err := ErrMetadataRequestPageGTEValidation
		err.Value = t.Page
		errs = append(errs, err)
	}

	if !(t.Limit >= 1) {
		err := ErrMetadataRequestLimitGTEValidation
		err.Value = t.Limit
		errs = append(errs, err)
	}

	if !(t.Limit <= 100) {
		err := ErrMetadataRequestLimitLTEValidation
		err.Value = t.Limit
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*MetadataRequest)(nil)

func (t *MetadataRequest) Validate() error {
	return ValidateMetadataRequest(t)
}
