// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilPincodeValidationRequest is returned when the PincodeValidationRequest is nil.
	ErrNilPincodeValidationRequest = errors.New("input PincodeValidationRequest is nil")

	// ErrPincodeValidationRequestPincodeRequiredValidation is returned when the Pincode is required but not provided.
	ErrPincodeValidationRequestPincodeRequiredValidation = govaliderrors.ValidationError{Reason: "field Pincode is required", Path: "PincodeValidationRequest.Pincode", Type: "required"}
)

func ValidatePincodeValidationRequest(t *PincodeValidationRequest) error {
	if t == nil {
		return ErrNilPincodeValidationRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.Pincode == "" {
		err := ErrPincodeValidationRequestPincodeRequiredValidation
		err.Value = t.Pincode
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*PincodeValidationRequest)(nil)

func (t *PincodeValidationRequest) Validate() error {
	return ValidatePincodeValidationRequest(t)
}
