// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilWorkflowIDUri is returned when the WorkflowIDUri is nil.
	ErrNilWorkflowIDUri = errors.New("input WorkflowIDUri is nil")

	// ErrWorkflowIDUriWorkflowIDRequiredValidation is returned when the WorkflowID is required but not provided.
	ErrWorkflowIDUriWorkflowIDRequiredValidation = govaliderrors.ValidationError{Reason: "field WorkflowID is required", Path: "WorkflowIDUri.WorkflowID", Type: "required"}
)

func ValidateWorkflowIDUri(t *WorkflowIDUri) error {
	if t == nil {
		return ErrNilWorkflowIDUri
	}

	var errs govaliderrors.ValidationErrors

	if t.WorkflowID == "" {
		err := ErrWorkflowIDUriWorkflowIDRequiredValidation
		err.Value = t.WorkflowID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*WorkflowIDUri)(nil)

func (t *WorkflowIDUri) Validate() error {
	return ValidateWorkflowIDUri(t)
}
