// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilQuoteConvertRequest is returned when the QuoteConvertRequest is nil.
	ErrNilQuoteConvertRequest = errors.New("input QuoteConvertRequest is nil")

	// ErrQuoteConvertRequestQuoteRefNumberRequiredValidation is returned when the QuoteRefNumber is required but not provided.
	ErrQuoteConvertRequestQuoteRefNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field QuoteRefNumber is required", Path: "QuoteConvertRequest.QuoteRefNumber", Type: "required"}

	// ErrQuoteConvertRequestCustomerIDRequiredValidation is returned when the CustomerID is required but not provided.
	ErrQuoteConvertRequestCustomerIDRequiredValidation = govaliderrors.ValidationError{Reason: "field CustomerID is required", Path: "QuoteConvertRequest.CustomerID", Type: "required"}

	// ErrQuoteConvertRequestCreatedByRequiredValidation is returned when the CreatedBy is required but not provided.
	ErrQuoteConvertRequestCreatedByRequiredValidation = govaliderrors.ValidationError{Reason: "field CreatedBy is required", Path: "QuoteConvertRequest.CreatedBy", Type: "required"}
)

func ValidateQuoteConvertRequest(t *QuoteConvertRequest) error {
	if t == nil {
		return ErrNilQuoteConvertRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.QuoteRefNumber == "" {
		err := ErrQuoteConvertRequestQuoteRefNumberRequiredValidation
		err.Value = t.QuoteRefNumber
		errs = append(errs, err)
	}

	if t.CustomerID == 0 {
		err := ErrQuoteConvertRequestCustomerIDRequiredValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if t.CreatedBy == 0 {
		err := ErrQuoteConvertRequestCreatedByRequiredValidation
		err.Value = t.CreatedBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*QuoteConvertRequest)(nil)

func (t *QuoteConvertRequest) Validate() error {
	return ValidateQuoteConvertRequest(t)
}
