// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilPreferenceInput is returned when the PreferenceInput is nil.
	ErrNilPreferenceInput = errors.New("input PreferenceInput is nil")

	// ErrPreferenceInputKeyMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrPreferenceInputKeyMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Key must have a maximum length of 50", Path: "PreferenceInput.Key", Type: "maxlength"}

	// ErrPreferenceInputKeyMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrPreferenceInputKeyMinLengthValidation = govaliderrors.ValidationError{Reason: "field Key must have a minimum length of 1", Path: "PreferenceInput.Key", Type: "minlength"}

	// ErrPreferenceInputKeyRequiredValidation is returned when the Key is required but not provided.
	ErrPreferenceInputKeyRequiredValidation = govaliderrors.ValidationError{Reason: "field Key is required", Path: "PreferenceInput.Key", Type: "required"}

	// ErrPreferenceInputValueMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 200.
	ErrPreferenceInputValueMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Value must have a maximum length of 200", Path: "PreferenceInput.Value", Type: "maxlength"}

	// ErrPreferenceInputValueMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrPreferenceInputValueMinLengthValidation = govaliderrors.ValidationError{Reason: "field Value must have a minimum length of 1", Path: "PreferenceInput.Value", Type: "minlength"}

	// ErrPreferenceInputValueRequiredValidation is returned when the Value is required but not provided.
	ErrPreferenceInputValueRequiredValidation = govaliderrors.ValidationError{Reason: "field Value is required", Path: "PreferenceInput.Value", Type: "required"}
)

func ValidatePreferenceInput(t *PreferenceInput) error {
	if t == nil {
		return ErrNilPreferenceInput
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.Key) > 50 {
		err := ErrPreferenceInputKeyMaxLengthValidation
		err.Value = t.Key
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.Key) < 1 {
		err := ErrPreferenceInputKeyMinLengthValidation
		err.Value = t.Key
		errs = append(errs, err)
	}

	if t.Key == "" {
		err := ErrPreferenceInputKeyRequiredValidation
		err.Value = t.Key
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.Value) > 200 {
		err := ErrPreferenceInputValueMaxLengthValidation
		err.Value = t.Value
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.Value) < 1 {
		err := ErrPreferenceInputValueMinLengthValidation
		err.Value = t.Value
		errs = append(errs, err)
	}

	if t.Value == "" {
		err := ErrPreferenceInputValueRequiredValidation
		err.Value = t.Value
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*PreferenceInput)(nil)

func (t *PreferenceInput) Validate() error {
	return ValidatePreferenceInput(t)
}
