// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilGetQuoteRequestParams is returned when the GetQuoteRequestParams is nil.
	ErrNilGetQuoteRequestParams = errors.New("input GetQuoteRequestParams is nil")

	// ErrGetQuoteRequestParamsQuoteIDRequiredValidation is returned when the QuoteID is required but not provided.
	ErrGetQuoteRequestParamsQuoteIDRequiredValidation = govaliderrors.ValidationError{Reason: "field QuoteID is required", Path: "GetQuoteRequestParams.QuoteID", Type: "required"}
)

func ValidateGetQuoteRequestParams(t *GetQuoteRequestParams) error {
	if t == nil {
		return ErrNilGetQuoteRequestParams
	}

	var errs govaliderrors.ValidationErrors

	if t.QuoteID == 0 {
		err := ErrGetQuoteRequestParamsQuoteIDRequiredValidation
		err.Value = t.QuoteID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*GetQuoteRequestParams)(nil)

func (t *GetQuoteRequestParams) Validate() error {
	return ValidateGetQuoteRequestParams(t)
}
