// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilGetProductsRequest is returned when the GetProductsRequest is nil.
	ErrNilGetProductsRequest = errors.New("input GetProductsRequest is nil")

	// ErrGetProductsRequestPolicyTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrGetProductsRequestPolicyTypeOneofValidation = govaliderrors.ValidationError{Reason: "field PolicyType must be one of PLI RPLI", Path: "GetProductsRequest.PolicyType", Type: "oneof"}
)

func ValidateGetProductsRequest(t *GetProductsRequest) error {
	if t == nil {
		return ErrNilGetProductsRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.PolicyType != "" && !(t.PolicyType == "PLI" || t.PolicyType == "RPLI") {
		err := ErrGetProductsRequestPolicyTypeOneofValidation
		err.Value = t.PolicyType
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*GetProductsRequest)(nil)

func (t *GetProductsRequest) Validate() error {
	return ValidateGetProductsRequest(t)
}
