// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilGetProposalQueueRequest is returned when the GetProposalQueueRequest is nil.
	ErrNilGetProposalQueueRequest = errors.New("input GetProposalQueueRequest is nil")
)

func ValidateGetProposalQueueRequest(t *GetProposalQueueRequest) error {
	if t == nil {
		return ErrNilGetProposalQueueRequest
	}

	var errs govaliderrors.ValidationErrors

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*GetProposalQueueRequest)(nil)

func (t *GetProposalQueueRequest) Validate() error {
	return ValidateGetProposalQueueRequest(t)
}
