// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilProposerInfo is returned when the ProposerInfo is nil.
	ErrNilProposerInfo = errors.New("input ProposerInfo is nil")

	// ErrProposerInfoNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 200.
	ErrProposerInfoNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Name must have a maximum length of 200", Path: "ProposerInfo.Name", Type: "maxlength"}

	// ErrProposerInfoNameRequiredValidation is returned when the Name is required but not provided.
	ErrProposerInfoNameRequiredValidation = govaliderrors.ValidationError{Reason: "field Name is required", Path: "ProposerInfo.Name", Type: "required"}

	// ErrProposerInfoDOBDateValidation is the error returned when the field is not a valid date (dd/mm/yy).
	ErrProposerInfoDOBDateValidation = govaliderrors.ValidationError{Reason: "field DOB must be a valid date (dd/mm/yy)", Path: "ProposerInfo.DOB", Type: "date"}

	// ErrProposerInfoDOBRequiredValidation is returned when the DOB is required but not provided.
	ErrProposerInfoDOBRequiredValidation = govaliderrors.ValidationError{Reason: "field DOB is required", Path: "ProposerInfo.DOB", Type: "required"}

	// ErrProposerInfoGenderOneofValidation is the error returned when the field is not one of the allowed values.
	ErrProposerInfoGenderOneofValidation = govaliderrors.ValidationError{Reason: "field Gender must be one of MALE FEMALE OTHER", Path: "ProposerInfo.Gender", Type: "oneof"}

	// ErrProposerInfoGenderRequiredValidation is returned when the Gender is required but not provided.
	ErrProposerInfoGenderRequiredValidation = govaliderrors.ValidationError{Reason: "field Gender is required", Path: "ProposerInfo.Gender", Type: "required"}

	// ErrProposerInfoMobileRequiredValidation is returned when the Mobile is required but not provided.
	ErrProposerInfoMobileRequiredValidation = govaliderrors.ValidationError{Reason: "field Mobile is required", Path: "ProposerInfo.Mobile", Type: "required"}

	// ErrProposerInfoEmailEmailValidation is the error returned when the field is not a valid email address.
	ErrProposerInfoEmailEmailValidation = govaliderrors.ValidationError{Reason: "field Email must be a valid email address", Path: "ProposerInfo.Email", Type: "email"}

	// ErrProposerInfoEmailMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrProposerInfoEmailMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Email must have a maximum length of 100", Path: "ProposerInfo.Email", Type: "maxlength"}
)

func ValidateProposerInfo(t *ProposerInfo) error {
	if t == nil {
		return ErrNilProposerInfo
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.Name) > 200 {
		err := ErrProposerInfoNameMaxLengthValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if t.Name == "" {
		err := ErrProposerInfoNameRequiredValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if !validationhelper.IsValidDateDDMMYY(t.DOB) {
		err := ErrProposerInfoDOBDateValidation
		err.Value = t.DOB
		errs = append(errs, err)
	}

	if t.DOB == "" {
		err := ErrProposerInfoDOBRequiredValidation
		err.Value = t.DOB
		errs = append(errs, err)
	}

	if !(t.Gender == "MALE" || t.Gender == "FEMALE" || t.Gender == "OTHER") {
		err := ErrProposerInfoGenderOneofValidation
		err.Value = t.Gender
		errs = append(errs, err)
	}

	if t.Gender == "" {
		err := ErrProposerInfoGenderRequiredValidation
		err.Value = t.Gender
		errs = append(errs, err)
	}

	if t.Mobile == "" {
		err := ErrProposerInfoMobileRequiredValidation
		err.Value = t.Mobile
		errs = append(errs, err)
	}

	if t.Email != "" && !validationhelper.IsValidEmail(t.Email) {
		err := ErrProposerInfoEmailEmailValidation
		err.Value = t.Email
		errs = append(errs, err)
	}

	if t.Email != "" && utf8.RuneCountInString(t.Email) > 100 {
		err := ErrProposerInfoEmailMaxLengthValidation
		err.Value = t.Email
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ProposerInfo)(nil)

func (t *ProposerInfo) Validate() error {
	return ValidateProposerInfo(t)
}
