// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilDocumentIDUri is returned when the DocumentIDUri is nil.
	ErrNilDocumentIDUri = errors.New("input DocumentIDUri is nil")

	// ErrDocumentIDUriProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrDocumentIDUriProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "DocumentIDUri.ProposalID", Type: "required"}

	// ErrDocumentIDUriDocumentIDRequiredValidation is returned when the DocumentID is required but not provided.
	ErrDocumentIDUriDocumentIDRequiredValidation = govaliderrors.ValidationError{Reason: "field DocumentID is required", Path: "DocumentIDUri.DocumentID", Type: "required"}
)

func ValidateDocumentIDUri(t *DocumentIDUri) error {
	if t == nil {
		return ErrNilDocumentIDUri
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrDocumentIDUriProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if t.DocumentID == 0 {
		err := ErrDocumentIDUriDocumentIDRequiredValidation
		err.Value = t.DocumentID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*DocumentIDUri)(nil)

func (t *DocumentIDUri) Validate() error {
	return ValidateDocumentIDUri(t)
}
