// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilPremiumInfo is returned when the PremiumInfo is nil.
	ErrNilPremiumInfo = errors.New("input PremiumInfo is nil")

	// ErrPremiumInfoBasePremiumGTValidation is the error returned when the value of the field is less than the 0.
	ErrPremiumInfoBasePremiumGTValidation = govaliderrors.ValidationError{Reason: "field BasePremium must be greater than 0", Path: "PremiumInfo.BasePremium", Type: "gt"}

	// ErrPremiumInfoBasePremiumRequiredValidation is returned when the BasePremium is required but not provided.
	ErrPremiumInfoBasePremiumRequiredValidation = govaliderrors.ValidationError{Reason: "field BasePremium is required", Path: "PremiumInfo.BasePremium", Type: "required"}

	// ErrPremiumInfoNetPremiumGTValidation is the error returned when the value of the field is less than the 0.
	ErrPremiumInfoNetPremiumGTValidation = govaliderrors.ValidationError{Reason: "field NetPremium must be greater than 0", Path: "PremiumInfo.NetPremium", Type: "gt"}

	// ErrPremiumInfoNetPremiumRequiredValidation is returned when the NetPremium is required but not provided.
	ErrPremiumInfoNetPremiumRequiredValidation = govaliderrors.ValidationError{Reason: "field NetPremium is required", Path: "PremiumInfo.NetPremium", Type: "required"}

	// ErrPremiumInfoTotalPayableGTValidation is the error returned when the value of the field is less than the 0.
	ErrPremiumInfoTotalPayableGTValidation = govaliderrors.ValidationError{Reason: "field TotalPayable must be greater than 0", Path: "PremiumInfo.TotalPayable", Type: "gt"}

	// ErrPremiumInfoTotalPayableRequiredValidation is returned when the TotalPayable is required but not provided.
	ErrPremiumInfoTotalPayableRequiredValidation = govaliderrors.ValidationError{Reason: "field TotalPayable is required", Path: "PremiumInfo.TotalPayable", Type: "required"}
)

func ValidatePremiumInfo(t *PremiumInfo) error {
	if t == nil {
		return ErrNilPremiumInfo
	}

	var errs govaliderrors.ValidationErrors

	if !(t.BasePremium > 0) {
		err := ErrPremiumInfoBasePremiumGTValidation
		err.Value = t.BasePremium
		errs = append(errs, err)
	}

	if t.BasePremium == 0.0 {
		err := ErrPremiumInfoBasePremiumRequiredValidation
		err.Value = t.BasePremium
		errs = append(errs, err)
	}

	if !(t.NetPremium > 0) {
		err := ErrPremiumInfoNetPremiumGTValidation
		err.Value = t.NetPremium
		errs = append(errs, err)
	}

	if t.NetPremium == 0.0 {
		err := ErrPremiumInfoNetPremiumRequiredValidation
		err.Value = t.NetPremium
		errs = append(errs, err)
	}

	if !(t.TotalPayable > 0) {
		err := ErrPremiumInfoTotalPayableGTValidation
		err.Value = t.TotalPayable
		errs = append(errs, err)
	}

	if t.TotalPayable == 0.0 {
		err := ErrPremiumInfoTotalPayableRequiredValidation
		err.Value = t.TotalPayable
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*PremiumInfo)(nil)

func (t *PremiumInfo) Validate() error {
	return ValidatePremiumInfo(t)
}
