// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilFLCQueueRequest is returned when the FLCQueueRequest is nil.
	ErrNilFLCQueueRequest = errors.New("input FLCQueueRequest is nil")

	// ErrFLCQueueRequestStatusOneofValidation is the error returned when the field is not one of the allowed values.
	ErrFLCQueueRequestStatusOneofValidation = govaliderrors.ValidationError{Reason: "field Status must be one of pending approved rejected", Path: "FLCQueueRequest.Status", Type: "oneof"}
)

func ValidateFLCQueueRequest(t *FLCQueueRequest) error {
	if t == nil {
		return ErrNilFLCQueueRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.Status != "" && !(t.Status == "pending" || t.Status == "approved" || t.Status == "rejected") {
		err := ErrFLCQueueRequestStatusOneofValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*FLCQueueRequest)(nil)

func (t *FLCQueueRequest) Validate() error {
	return ValidateFLCQueueRequest(t)
}
