// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilApproverApproveRequest is returned when the ApproverApproveRequest is nil.
	ErrNilApproverApproveRequest = errors.New("input ApproverApproveRequest is nil")

	// ErrApproverApproveRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrApproverApproveRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "ApproverApproveRequest.ProposalID", Type: "required"}

	// ErrApproverApproveRequestApproverIDRequiredValidation is returned when the ApproverID is required but not provided.
	ErrApproverApproveRequestApproverIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApproverID is required", Path: "ApproverApproveRequest.ApproverID", Type: "required"}
)

func ValidateApproverApproveRequest(t *ApproverApproveRequest) error {
	if t == nil {
		return ErrNilApproverApproveRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrApproverApproveRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if t.ApproverID == "" {
		err := ErrApproverApproveRequestApproverIDRequiredValidation
		err.Value = t.ApproverID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ApproverApproveRequest)(nil)

func (t *ApproverApproveRequest) Validate() error {
	return ValidateApproverApproveRequest(t)
}
