// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilQRReturnRequest is returned when the QRReturnRequest is nil.
	ErrNilQRReturnRequest = errors.New("input QRReturnRequest is nil")

	// ErrQRReturnRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrQRReturnRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "QRReturnRequest.ProposalID", Type: "required"}

	// ErrQRReturnRequestReviewerIDRequiredValidation is returned when the ReviewerID is required but not provided.
	ErrQRReturnRequestReviewerIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ReviewerID is required", Path: "QRReturnRequest.ReviewerID", Type: "required"}

	// ErrQRReturnRequestCommentsRequiredValidation is returned when the Comments is required but not provided.
	ErrQRReturnRequestCommentsRequiredValidation = govaliderrors.ValidationError{Reason: "field Comments is required", Path: "QRReturnRequest.Comments", Type: "required"}
)

func ValidateQRReturnRequest(t *QRReturnRequest) error {
	if t == nil {
		return ErrNilQRReturnRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrQRReturnRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if t.ReviewerID == "" {
		err := ErrQRReturnRequestReviewerIDRequiredValidation
		err.Value = t.ReviewerID
		errs = append(errs, err)
	}

	if t.Comments == "" {
		err := ErrQRReturnRequestCommentsRequiredValidation
		err.Value = t.Comments
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*QRReturnRequest)(nil)

func (t *QRReturnRequest) Validate() error {
	return ValidateQRReturnRequest(t)
}
