// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilIFSCValidationRequest is returned when the IFSCValidationRequest is nil.
	ErrNilIFSCValidationRequest = errors.New("input IFSCValidationRequest is nil")

	// ErrIFSCValidationRequestIFSCCodeRequiredValidation is returned when the IFSCCode is required but not provided.
	ErrIFSCValidationRequestIFSCCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field IFSCCode is required", Path: "IFSCValidationRequest.IFSCCode", Type: "required"}
)

func ValidateIFSCValidationRequest(t *IFSCValidationRequest) error {
	if t == nil {
		return ErrNilIFSCValidationRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.IFSCCode == "" {
		err := ErrIFSCValidationRequestIFSCCodeRequiredValidation
		err.Value = t.IFSCCode
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*IFSCValidationRequest)(nil)

func (t *IFSCValidationRequest) Validate() error {
	return ValidateIFSCValidationRequest(t)
}
