// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilStartDataEntryRequest is returned when the StartDataEntryRequest is nil.
	ErrNilStartDataEntryRequest = errors.New("input StartDataEntryRequest is nil")

	// ErrStartDataEntryRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrStartDataEntryRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "StartDataEntryRequest.ProposalID", Type: "required"}

	// ErrStartDataEntryRequestAssignedToRequiredValidation is returned when the AssignedTo is required but not provided.
	ErrStartDataEntryRequestAssignedToRequiredValidation = govaliderrors.ValidationError{Reason: "field AssignedTo is required", Path: "StartDataEntryRequest.AssignedTo", Type: "required"}
)

func ValidateStartDataEntryRequest(t *StartDataEntryRequest) error {
	if t == nil {
		return ErrNilStartDataEntryRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrStartDataEntryRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if t.AssignedTo == 0 {
		err := ErrStartDataEntryRequestAssignedToRequiredValidation
		err.Value = t.AssignedTo
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*StartDataEntryRequest)(nil)

func (t *StartDataEntryRequest) Validate() error {
	return ValidateStartDataEntryRequest(t)
}
