// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilProposalIDUri is returned when the ProposalIDUri is nil.
	ErrNilProposalIDUri = errors.New("input ProposalIDUri is nil")

	// ErrProposalIDUriProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrProposalIDUriProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "ProposalIDUri.ProposalID", Type: "required"}
)

func ValidateProposalIDUri(t *ProposalIDUri) error {
	if t == nil {
		return ErrNilProposalIDUri
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrProposalIDUriProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ProposalIDUri)(nil)

func (t *ProposalIDUri) Validate() error {
	return ValidateProposalIDUri(t)
}
