// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilQuoteCalculateRequest is returned when the QuoteCalculateRequest is nil.
	ErrNilQuoteCalculateRequest = errors.New("input QuoteCalculateRequest is nil")

	// ErrQuoteCalculateRequestProductCodeRequiredValidation is returned when the ProductCode is required but not provided.
	ErrQuoteCalculateRequestProductCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field ProductCode is required", Path: "QuoteCalculateRequest.ProductCode", Type: "required"}

	// ErrQuoteCalculateRequestDateOfBirthRequiredValidation is returned when the DateOfBirth is required but not provided.
	ErrQuoteCalculateRequestDateOfBirthRequiredValidation = govaliderrors.ValidationError{Reason: "field DateOfBirth is required", Path: "QuoteCalculateRequest.DateOfBirth", Type: "required"}

	// ErrQuoteCalculateRequestDateOfCalculationRequiredValidation is returned when the DateOfCalculation is required but not provided.
	ErrQuoteCalculateRequestDateOfCalculationRequiredValidation = govaliderrors.ValidationError{Reason: "field DateOfCalculation is required", Path: "QuoteCalculateRequest.DateOfCalculation", Type: "required"}

	// ErrQuoteCalculateRequestGenderRequiredValidation is returned when the Gender is required but not provided.
	ErrQuoteCalculateRequestGenderRequiredValidation = govaliderrors.ValidationError{Reason: "field Gender is required", Path: "QuoteCalculateRequest.Gender", Type: "required"}

	// ErrQuoteCalculateRequestPeriodicityRequiredValidation is returned when the Periodicity is required but not provided.
	ErrQuoteCalculateRequestPeriodicityRequiredValidation = govaliderrors.ValidationError{Reason: "field Periodicity is required", Path: "QuoteCalculateRequest.Periodicity", Type: "required"}

	// ErrQuoteCalculateRequestSumAssuredGTValidation is the error returned when the value of the field is less than the 0.
	ErrQuoteCalculateRequestSumAssuredGTValidation = govaliderrors.ValidationError{Reason: "field SumAssured must be greater than 0", Path: "QuoteCalculateRequest.SumAssured", Type: "gt"}

	// ErrQuoteCalculateRequestSumAssuredRequiredValidation is returned when the SumAssured is required but not provided.
	ErrQuoteCalculateRequestSumAssuredRequiredValidation = govaliderrors.ValidationError{Reason: "field SumAssured is required", Path: "QuoteCalculateRequest.SumAssured", Type: "required"}
)

func ValidateQuoteCalculateRequest(t *QuoteCalculateRequest) error {
	if t == nil {
		return ErrNilQuoteCalculateRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProductCode == "" {
		err := ErrQuoteCalculateRequestProductCodeRequiredValidation
		err.Value = t.ProductCode
		errs = append(errs, err)
	}

	if t.DateOfBirth == "" {
		err := ErrQuoteCalculateRequestDateOfBirthRequiredValidation
		err.Value = t.DateOfBirth
		errs = append(errs, err)
	}

	if t.DateOfCalculation == "" {
		err := ErrQuoteCalculateRequestDateOfCalculationRequiredValidation
		err.Value = t.DateOfCalculation
		errs = append(errs, err)
	}

	if t.Gender == "" {
		err := ErrQuoteCalculateRequestGenderRequiredValidation
		err.Value = t.Gender
		errs = append(errs, err)
	}

	if t.Periodicity == "" {
		err := ErrQuoteCalculateRequestPeriodicityRequiredValidation
		err.Value = t.Periodicity
		errs = append(errs, err)
	}

	if !(t.SumAssured > 0) {
		err := ErrQuoteCalculateRequestSumAssuredGTValidation
		err.Value = t.SumAssured
		errs = append(errs, err)
	}

	if t.SumAssured == 0 {
		err := ErrQuoteCalculateRequestSumAssuredRequiredValidation
		err.Value = t.SumAssured
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*QuoteCalculateRequest)(nil)

func (t *QuoteCalculateRequest) Validate() error {
	return ValidateQuoteCalculateRequest(t)
}
