// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilMWPATrusteeRequest is returned when the MWPATrusteeRequest is nil.
	ErrNilMWPATrusteeRequest = errors.New("input MWPATrusteeRequest is nil")

	// ErrMWPATrusteeRequestTrustTypeRequiredValidation is returned when the TrustType is required but not provided.
	ErrMWPATrusteeRequestTrustTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field TrustType is required", Path: "MWPATrusteeRequest.TrustType", Type: "required"}

	// ErrMWPATrusteeRequestTrusteeNameRequiredValidation is returned when the TrusteeName is required but not provided.
	ErrMWPATrusteeRequestTrusteeNameRequiredValidation = govaliderrors.ValidationError{Reason: "field TrusteeName is required", Path: "MWPATrusteeRequest.TrusteeName", Type: "required"}
)

func ValidateMWPATrusteeRequest(t *MWPATrusteeRequest) error {
	if t == nil {
		return ErrNilMWPATrusteeRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TrustType == "" {
		err := ErrMWPATrusteeRequestTrustTypeRequiredValidation
		err.Value = t.TrustType
		errs = append(errs, err)
	}

	if t.TrusteeName == "" {
		err := ErrMWPATrusteeRequestTrusteeNameRequiredValidation
		err.Value = t.TrusteeName
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*MWPATrusteeRequest)(nil)

func (t *MWPATrusteeRequest) Validate() error {
	return ValidateMWPATrusteeRequest(t)
}
