// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilAgentDetailsRequest is returned when the AgentDetailsRequest is nil.
	ErrNilAgentDetailsRequest = errors.New("input AgentDetailsRequest is nil")

	// ErrAgentDetailsRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrAgentDetailsRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "AgentDetailsRequest.ProposalID", Type: "required"}

	// ErrAgentDetailsRequestAgentIDRequiredValidation is returned when the AgentID is required but not provided.
	ErrAgentDetailsRequestAgentIDRequiredValidation = govaliderrors.ValidationError{Reason: "field AgentID is required", Path: "AgentDetailsRequest.AgentID", Type: "required"}
)

func ValidateAgentDetailsRequest(t *AgentDetailsRequest) error {
	if t == nil {
		return ErrNilAgentDetailsRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrAgentDetailsRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if t.AgentID == "" {
		err := ErrAgentDetailsRequestAgentIDRequiredValidation
		err.Value = t.AgentID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*AgentDetailsRequest)(nil)

func (t *AgentDetailsRequest) Validate() error {
	return ValidateAgentDetailsRequest(t)
}
