// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilNomineesRequest is returned when the NomineesRequest is nil.
	ErrNilNomineesRequest = errors.New("input NomineesRequest is nil")

	// ErrNomineesRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrNomineesRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "NomineesRequest.ProposalID", Type: "required"}

	// ErrNomineesRequestNomineesMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrNomineesRequestNomineesMinItemsValidation = govaliderrors.ValidationError{Reason: "field Nominees must have a minimum of 1 items", Path: "NomineesRequest.Nominees", Type: "minitems"}

	// ErrNomineesRequestNomineesRequiredValidation is returned when the Nominees is required but not provided.
	ErrNomineesRequestNomineesRequiredValidation = govaliderrors.ValidationError{Reason: "field Nominees is required", Path: "NomineesRequest.Nominees", Type: "required"}
)

func ValidateNomineesRequest(t *NomineesRequest) error {
	if t == nil {
		return ErrNilNomineesRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrNomineesRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if len(t.Nominees) < 1 {
		err := ErrNomineesRequestNomineesMinItemsValidation
		err.Value = t.Nominees
		errs = append(errs, err)
	}

	if t.Nominees == nil {
		err := ErrNomineesRequestNomineesRequiredValidation
		err.Value = t.Nominees
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*NomineesRequest)(nil)

func (t *NomineesRequest) Validate() error {
	return ValidateNomineesRequest(t)
}
