// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilGetQuoteRefRequestParams is returned when the GetQuoteRefRequestParams is nil.
	ErrNilGetQuoteRefRequestParams = errors.New("input GetQuoteRefRequestParams is nil")

	// ErrGetQuoteRefRequestParamsQuoteRefNumberRequiredValidation is returned when the QuoteRefNumber is required but not provided.
	ErrGetQuoteRefRequestParamsQuoteRefNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field QuoteRefNumber is required", Path: "GetQuoteRefRequestParams.QuoteRefNumber", Type: "required"}
)

func ValidateGetQuoteRefRequestParams(t *GetQuoteRefRequestParams) error {
	if t == nil {
		return ErrNilGetQuoteRefRequestParams
	}

	var errs govaliderrors.ValidationErrors

	if t.QuoteRefNumber == "" {
		err := ErrGetQuoteRefRequestParamsQuoteRefNumberRequiredValidation
		err.Value = t.QuoteRefNumber
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*GetQuoteRefRequestParams)(nil)

func (t *GetQuoteRefRequestParams) Validate() error {
	return ValidateGetQuoteRefRequestParams(t)
}
