// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilAadhaarFormatRequest is returned when the AadhaarFormatRequest is nil.
	ErrNilAadhaarFormatRequest = errors.New("input AadhaarFormatRequest is nil")

	// ErrAadhaarFormatRequestAadhaarNumberRequiredValidation is returned when the AadhaarNumber is required but not provided.
	ErrAadhaarFormatRequestAadhaarNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field AadhaarNumber is required", Path: "AadhaarFormatRequest.AadhaarNumber", Type: "required"}
)

func ValidateAadhaarFormatRequest(t *AadhaarFormatRequest) error {
	if t == nil {
		return ErrNilAadhaarFormatRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.AadhaarNumber == "" {
		err := ErrAadhaarFormatRequestAadhaarNumberRequiredValidation
		err.Value = t.AadhaarNumber
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*AadhaarFormatRequest)(nil)

func (t *AadhaarFormatRequest) Validate() error {
	return ValidateAadhaarFormatRequest(t)
}
