// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilProposalNumberUri is returned when the ProposalNumberUri is nil.
	ErrNilProposalNumberUri = errors.New("input ProposalNumberUri is nil")

	// ErrProposalNumberUriProposalNumberRequiredValidation is returned when the ProposalNumber is required but not provided.
	ErrProposalNumberUriProposalNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalNumber is required", Path: "ProposalNumberUri.ProposalNumber", Type: "required"}
)

func ValidateProposalNumberUri(t *ProposalNumberUri) error {
	if t == nil {
		return ErrNilProposalNumberUri
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalNumber == "" {
		err := ErrProposalNumberUriProposalNumberRequiredValidation
		err.Value = t.ProposalNumber
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ProposalNumberUri)(nil)

func (t *ProposalNumberUri) Validate() error {
	return ValidateProposalNumberUri(t)
}
