// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilCustomerIdentityInput is returned when the CustomerIdentityInput is nil.
	ErrNilCustomerIdentityInput = errors.New("input CustomerIdentityInput is nil")

	// ErrCustomerIdentityInputFirstNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrCustomerIdentityInputFirstNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field FirstName must have a maximum length of 100", Path: "CustomerIdentityInput.FirstName", Type: "maxlength"}

	// ErrCustomerIdentityInputFirstNameMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrCustomerIdentityInputFirstNameMinLengthValidation = govaliderrors.ValidationError{Reason: "field FirstName must have a minimum length of 1", Path: "CustomerIdentityInput.FirstName", Type: "minlength"}

	// ErrCustomerIdentityInputFirstNameRequiredValidation is returned when the FirstName is required but not provided.
	ErrCustomerIdentityInputFirstNameRequiredValidation = govaliderrors.ValidationError{Reason: "field FirstName is required", Path: "CustomerIdentityInput.FirstName", Type: "required"}

	// ErrCustomerIdentityInputMiddleNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrCustomerIdentityInputMiddleNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field MiddleName must have a maximum length of 100", Path: "CustomerIdentityInput.MiddleName", Type: "maxlength"}

	// ErrCustomerIdentityInputLastNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrCustomerIdentityInputLastNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field LastName must have a maximum length of 100", Path: "CustomerIdentityInput.LastName", Type: "maxlength"}

	// ErrCustomerIdentityInputLastNameMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrCustomerIdentityInputLastNameMinLengthValidation = govaliderrors.ValidationError{Reason: "field LastName must have a minimum length of 1", Path: "CustomerIdentityInput.LastName", Type: "minlength"}

	// ErrCustomerIdentityInputLastNameRequiredValidation is returned when the LastName is required but not provided.
	ErrCustomerIdentityInputLastNameRequiredValidation = govaliderrors.ValidationError{Reason: "field LastName is required", Path: "CustomerIdentityInput.LastName", Type: "required"}

	// ErrCustomerIdentityInputDOBRequiredValidation is returned when the DOB is required but not provided.
	ErrCustomerIdentityInputDOBRequiredValidation = govaliderrors.ValidationError{Reason: "field DOB is required", Path: "CustomerIdentityInput.DOB", Type: "required"}

	// ErrCustomerIdentityInputGenderOneofValidation is the error returned when the field is not one of the allowed values.
	ErrCustomerIdentityInputGenderOneofValidation = govaliderrors.ValidationError{Reason: "field Gender must be one of MALE FEMALE OTHER", Path: "CustomerIdentityInput.Gender", Type: "oneof"}

	// ErrCustomerIdentityInputGenderRequiredValidation is returned when the Gender is required but not provided.
	ErrCustomerIdentityInputGenderRequiredValidation = govaliderrors.ValidationError{Reason: "field Gender is required", Path: "CustomerIdentityInput.Gender", Type: "required"}

	// ErrCustomerIdentityInputNationalityMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrCustomerIdentityInputNationalityMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Nationality must have a maximum length of 50", Path: "CustomerIdentityInput.Nationality", Type: "maxlength"}

	// ErrCustomerIdentityInputNationalityMinLengthValidation is the error returned when the length of the field is less than the minimum of 2.
	ErrCustomerIdentityInputNationalityMinLengthValidation = govaliderrors.ValidationError{Reason: "field Nationality must have a minimum length of 2", Path: "CustomerIdentityInput.Nationality", Type: "minlength"}

	// ErrCustomerIdentityInputCountryOfResidenceMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrCustomerIdentityInputCountryOfResidenceMaxLengthValidation = govaliderrors.ValidationError{Reason: "field CountryOfResidence must have a maximum length of 50", Path: "CustomerIdentityInput.CountryOfResidence", Type: "maxlength"}

	// ErrCustomerIdentityInputCountryOfResidenceMinLengthValidation is the error returned when the length of the field is less than the minimum of 2.
	ErrCustomerIdentityInputCountryOfResidenceMinLengthValidation = govaliderrors.ValidationError{Reason: "field CountryOfResidence must have a minimum length of 2", Path: "CustomerIdentityInput.CountryOfResidence", Type: "minlength"}

	// ErrCustomerIdentityInputMaritalStatusOneofValidation is the error returned when the field is not one of the allowed values.
	ErrCustomerIdentityInputMaritalStatusOneofValidation = govaliderrors.ValidationError{Reason: "field MaritalStatus must be one of SINGLE MARRIED DIVORCED WIDOWED", Path: "CustomerIdentityInput.MaritalStatus", Type: "oneof"}

	// ErrCustomerIdentityInputSalutationOneofValidation is the error returned when the field is not one of the allowed values.
	ErrCustomerIdentityInputSalutationOneofValidation = govaliderrors.ValidationError{Reason: "field Salutation must be one of MR MRS MS DR", Path: "CustomerIdentityInput.Salutation", Type: "oneof"}

	// ErrCustomerIdentityInputFatherNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 200.
	ErrCustomerIdentityInputFatherNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field FatherName must have a maximum length of 200", Path: "CustomerIdentityInput.FatherName", Type: "maxlength"}

	// ErrCustomerIdentityInputHusbandNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 200.
	ErrCustomerIdentityInputHusbandNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field HusbandName must have a maximum length of 200", Path: "CustomerIdentityInput.HusbandName", Type: "maxlength"}

	// ErrCustomerIdentityInputInsuredProposerSameRequiredValidation is returned when the InsuredProposerSame is required but not provided.
	ErrCustomerIdentityInputInsuredProposerSameRequiredValidation = govaliderrors.ValidationError{Reason: "field InsuredProposerSame is required", Path: "CustomerIdentityInput.InsuredProposerSame", Type: "required"}
)

func ValidateCustomerIdentityInput(t *CustomerIdentityInput) error {
	if t == nil {
		return ErrNilCustomerIdentityInput
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.FirstName) > 100 {
		err := ErrCustomerIdentityInputFirstNameMaxLengthValidation
		err.Value = t.FirstName
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.FirstName) < 1 {
		err := ErrCustomerIdentityInputFirstNameMinLengthValidation
		err.Value = t.FirstName
		errs = append(errs, err)
	}

	if t.FirstName == "" {
		err := ErrCustomerIdentityInputFirstNameRequiredValidation
		err.Value = t.FirstName
		errs = append(errs, err)
	}

	if t.MiddleName != "" && utf8.RuneCountInString(t.MiddleName) > 100 {
		err := ErrCustomerIdentityInputMiddleNameMaxLengthValidation
		err.Value = t.MiddleName
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.LastName) > 100 {
		err := ErrCustomerIdentityInputLastNameMaxLengthValidation
		err.Value = t.LastName
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.LastName) < 1 {
		err := ErrCustomerIdentityInputLastNameMinLengthValidation
		err.Value = t.LastName
		errs = append(errs, err)
	}

	if t.LastName == "" {
		err := ErrCustomerIdentityInputLastNameRequiredValidation
		err.Value = t.LastName
		errs = append(errs, err)
	}

	if t.DOB == "" {
		err := ErrCustomerIdentityInputDOBRequiredValidation
		err.Value = t.DOB
		errs = append(errs, err)
	}

	if !(t.Gender == "MALE" || t.Gender == "FEMALE" || t.Gender == "OTHER") {
		err := ErrCustomerIdentityInputGenderOneofValidation
		err.Value = t.Gender
		errs = append(errs, err)
	}

	if t.Gender == "" {
		err := ErrCustomerIdentityInputGenderRequiredValidation
		err.Value = t.Gender
		errs = append(errs, err)
	}

	if t.Nationality != "" && utf8.RuneCountInString(t.Nationality) > 50 {
		err := ErrCustomerIdentityInputNationalityMaxLengthValidation
		err.Value = t.Nationality
		errs = append(errs, err)
	}

	if t.Nationality != "" && utf8.RuneCountInString(t.Nationality) < 2 {
		err := ErrCustomerIdentityInputNationalityMinLengthValidation
		err.Value = t.Nationality
		errs = append(errs, err)
	}

	if t.CountryOfResidence != "" && utf8.RuneCountInString(t.CountryOfResidence) > 50 {
		err := ErrCustomerIdentityInputCountryOfResidenceMaxLengthValidation
		err.Value = t.CountryOfResidence
		errs = append(errs, err)
	}

	if t.CountryOfResidence != "" && utf8.RuneCountInString(t.CountryOfResidence) < 2 {
		err := ErrCustomerIdentityInputCountryOfResidenceMinLengthValidation
		err.Value = t.CountryOfResidence
		errs = append(errs, err)
	}

	if t.MaritalStatus != "" && !(t.MaritalStatus == "SINGLE" || t.MaritalStatus == "MARRIED" || t.MaritalStatus == "DIVORCED" || t.MaritalStatus == "WIDOWED") {
		err := ErrCustomerIdentityInputMaritalStatusOneofValidation
		err.Value = t.MaritalStatus
		errs = append(errs, err)
	}

	if t.Salutation != "" && !(t.Salutation == "MR" || t.Salutation == "MRS" || t.Salutation == "MS" || t.Salutation == "DR") {
		err := ErrCustomerIdentityInputSalutationOneofValidation
		err.Value = t.Salutation
		errs = append(errs, err)
	}

	if t.FatherName != "" && utf8.RuneCountInString(t.FatherName) > 200 {
		err := ErrCustomerIdentityInputFatherNameMaxLengthValidation
		err.Value = t.FatherName
		errs = append(errs, err)
	}

	if t.HusbandName != "" && utf8.RuneCountInString(t.HusbandName) > 200 {
		err := ErrCustomerIdentityInputHusbandNameMaxLengthValidation
		err.Value = t.HusbandName
		errs = append(errs, err)
	}

	if t.InsuredProposerSame == false {
		err := ErrCustomerIdentityInputInsuredProposerSameRequiredValidation
		err.Value = t.InsuredProposerSame
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CustomerIdentityInput)(nil)

func (t *CustomerIdentityInput) Validate() error {
	return ValidateCustomerIdentityInput(t)
}
