// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilDedupInput is returned when the DedupInput is nil.
	ErrNilDedupInput = errors.New("input DedupInput is nil")
)

func ValidateDedupInput(t *DedupInput) error {
	if t == nil {
		return ErrNilDedupInput
	}

	var errs govaliderrors.ValidationErrors

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*DedupInput)(nil)

func (t *DedupInput) Validate() error {
	return ValidateDedupInput(t)
}
