// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilGSTCalculationRequest is returned when the GSTCalculationRequest is nil.
	ErrNilGSTCalculationRequest = errors.New("input GSTCalculationRequest is nil")

	// ErrGSTCalculationRequestBaseAmountGTValidation is the error returned when the value of the field is less than the 0.
	ErrGSTCalculationRequestBaseAmountGTValidation = govaliderrors.ValidationError{Reason: "field BaseAmount must be greater than 0", Path: "GSTCalculationRequest.BaseAmount", Type: "gt"}

	// ErrGSTCalculationRequestBaseAmountRequiredValidation is returned when the BaseAmount is required but not provided.
	ErrGSTCalculationRequestBaseAmountRequiredValidation = govaliderrors.ValidationError{Reason: "field BaseAmount is required", Path: "GSTCalculationRequest.BaseAmount", Type: "required"}

	// ErrGSTCalculationRequestInsuredStateRequiredValidation is returned when the InsuredState is required but not provided.
	ErrGSTCalculationRequestInsuredStateRequiredValidation = govaliderrors.ValidationError{Reason: "field InsuredState is required", Path: "GSTCalculationRequest.InsuredState", Type: "required"}
)

func ValidateGSTCalculationRequest(t *GSTCalculationRequest) error {
	if t == nil {
		return ErrNilGSTCalculationRequest
	}

	var errs govaliderrors.ValidationErrors

	if !(t.BaseAmount > 0) {
		err := ErrGSTCalculationRequestBaseAmountGTValidation
		err.Value = t.BaseAmount
		errs = append(errs, err)
	}

	if t.BaseAmount == 0.0 {
		err := ErrGSTCalculationRequestBaseAmountRequiredValidation
		err.Value = t.BaseAmount
		errs = append(errs, err)
	}

	if t.InsuredState == "" {
		err := ErrGSTCalculationRequestInsuredStateRequiredValidation
		err.Value = t.InsuredState
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*GSTCalculationRequest)(nil)

func (t *GSTCalculationRequest) Validate() error {
	return ValidateGSTCalculationRequest(t)
}
