// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilCustomerContactInput is returned when the CustomerContactInput is nil.
	ErrNilCustomerContactInput = errors.New("input CustomerContactInput is nil")

	// ErrCustomerContactInputActionRequiredValidation is returned when the Action is required but not provided.
	ErrCustomerContactInputActionRequiredValidation = govaliderrors.ValidationError{Reason: "field Action is required", Path: "CustomerContactInput.Action", Type: "required"}

	// ErrCustomerContactInputCustomerIDRequiredValidation is returned when the CustomerID is required but not provided.
	ErrCustomerContactInputCustomerIDRequiredValidation = govaliderrors.ValidationError{Reason: "field CustomerID is required", Path: "CustomerContactInput.CustomerID", Type: "required"}
)

func ValidateCustomerContactInput(t *CustomerContactInput) error {
	if t == nil {
		return ErrNilCustomerContactInput
	}

	var errs govaliderrors.ValidationErrors

	if t.Action == "" {
		err := ErrCustomerContactInputActionRequiredValidation
		err.Value = t.Action
		errs = append(errs, err)
	}

	if t.CustomerID == "" {
		err := ErrCustomerContactInputCustomerIDRequiredValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CustomerContactInput)(nil)

func (t *CustomerContactInput) Validate() error {
	return ValidateCustomerContactInput(t)
}
