// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilFLCApproveRequest is returned when the FLCApproveRequest is nil.
	ErrNilFLCApproveRequest = errors.New("input FLCApproveRequest is nil")

	// ErrFLCApproveRequestProposalIDRequiredValidation is returned when the ProposalID is required but not provided.
	ErrFLCApproveRequestProposalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProposalID is required", Path: "FLCApproveRequest.ProposalID", Type: "required"}

	// ErrFLCApproveRequestApproverIDRequiredValidation is returned when the ApproverID is required but not provided.
	ErrFLCApproveRequestApproverIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApproverID is required", Path: "FLCApproveRequest.ApproverID", Type: "required"}
)

func ValidateFLCApproveRequest(t *FLCApproveRequest) error {
	if t == nil {
		return ErrNilFLCApproveRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProposalID == 0 {
		err := ErrFLCApproveRequestProposalIDRequiredValidation
		err.Value = t.ProposalID
		errs = append(errs, err)
	}

	if t.ApproverID == "" {
		err := ErrFLCApproveRequestApproverIDRequiredValidation
		err.Value = t.ApproverID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*FLCApproveRequest)(nil)

func (t *FLCApproveRequest) Validate() error {
	return ValidateFLCApproveRequest(t)
}
