// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilDocumentRefsInput is returned when the DocumentRefsInput is nil.
	ErrNilDocumentRefsInput = errors.New("input DocumentRefsInput is nil")

	// ErrDocumentRefsInputAadhaarMaskedLengthValidation is the error returned when the length of the field is not exactly 12.
	ErrDocumentRefsInputAadhaarMaskedLengthValidation = govaliderrors.ValidationError{Reason: "field AadhaarMasked length must be exactly 12", Path: "DocumentRefsInput.AadhaarMasked", Type: "length"}

	// ErrDocumentRefsInputPANNumberLengthValidation is the error returned when the length of the field is not exactly 10.
	ErrDocumentRefsInputPANNumberLengthValidation = govaliderrors.ValidationError{Reason: "field PANNumber length must be exactly 10", Path: "DocumentRefsInput.PANNumber", Type: "length"}

	// ErrDocumentRefsInputEIAIDMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrDocumentRefsInputEIAIDMaxLengthValidation = govaliderrors.ValidationError{Reason: "field EIAID must have a maximum length of 50", Path: "DocumentRefsInput.EIAID", Type: "maxlength"}

	// ErrDocumentRefsInputEIAIDMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrDocumentRefsInputEIAIDMinLengthValidation = govaliderrors.ValidationError{Reason: "field EIAID must have a minimum length of 1", Path: "DocumentRefsInput.EIAID", Type: "minlength"}

	// ErrDocumentRefsInputCKYCNumberMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrDocumentRefsInputCKYCNumberMaxLengthValidation = govaliderrors.ValidationError{Reason: "field CKYCNumber must have a maximum length of 50", Path: "DocumentRefsInput.CKYCNumber", Type: "maxlength"}

	// ErrDocumentRefsInputCKYCNumberMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrDocumentRefsInputCKYCNumberMinLengthValidation = govaliderrors.ValidationError{Reason: "field CKYCNumber must have a minimum length of 1", Path: "DocumentRefsInput.CKYCNumber", Type: "minlength"}

	// ErrDocumentRefsInputGCIFIdMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrDocumentRefsInputGCIFIdMaxLengthValidation = govaliderrors.ValidationError{Reason: "field GCIFId must have a maximum length of 50", Path: "DocumentRefsInput.GCIFId", Type: "maxlength"}

	// ErrDocumentRefsInputGCIFIdMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrDocumentRefsInputGCIFIdMinLengthValidation = govaliderrors.ValidationError{Reason: "field GCIFId must have a minimum length of 1", Path: "DocumentRefsInput.GCIFId", Type: "minlength"}
)

func ValidateDocumentRefsInput(t *DocumentRefsInput) error {
	if t == nil {
		return ErrNilDocumentRefsInput
	}

	var errs govaliderrors.ValidationErrors

	if t.AadhaarMasked != "" && utf8.RuneCountInString(t.AadhaarMasked) != 12 {
		err := ErrDocumentRefsInputAadhaarMaskedLengthValidation
		err.Value = t.AadhaarMasked
		errs = append(errs, err)
	}

	if t.PANNumber != "" && utf8.RuneCountInString(t.PANNumber) != 10 {
		err := ErrDocumentRefsInputPANNumberLengthValidation
		err.Value = t.PANNumber
		errs = append(errs, err)
	}

	if t.EIAID != "" && utf8.RuneCountInString(t.EIAID) > 50 {
		err := ErrDocumentRefsInputEIAIDMaxLengthValidation
		err.Value = t.EIAID
		errs = append(errs, err)
	}

	if t.EIAID != "" && utf8.RuneCountInString(t.EIAID) < 1 {
		err := ErrDocumentRefsInputEIAIDMinLengthValidation
		err.Value = t.EIAID
		errs = append(errs, err)
	}

	if t.CKYCNumber != "" && utf8.RuneCountInString(t.CKYCNumber) > 50 {
		err := ErrDocumentRefsInputCKYCNumberMaxLengthValidation
		err.Value = t.CKYCNumber
		errs = append(errs, err)
	}

	if t.CKYCNumber != "" && utf8.RuneCountInString(t.CKYCNumber) < 1 {
		err := ErrDocumentRefsInputCKYCNumberMinLengthValidation
		err.Value = t.CKYCNumber
		errs = append(errs, err)
	}

	if t.GCIFId != "" && utf8.RuneCountInString(t.GCIFId) > 50 {
		err := ErrDocumentRefsInputGCIFIdMaxLengthValidation
		err.Value = t.GCIFId
		errs = append(errs, err)
	}

	if t.GCIFId != "" && utf8.RuneCountInString(t.GCIFId) < 1 {
		err := ErrDocumentRefsInputGCIFIdMinLengthValidation
		err.Value = t.GCIFId
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*DocumentRefsInput)(nil)

func (t *DocumentRefsInput) Validate() error {
	return ValidateDocumentRefsInput(t)
}
