// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilNomineeShareEntry is returned when the NomineeShareEntry is nil.
	ErrNilNomineeShareEntry = errors.New("input NomineeShareEntry is nil")

	// ErrNomineeShareEntryShareGTValidation is the error returned when the value of the field is less than the 0.
	ErrNomineeShareEntryShareGTValidation = govaliderrors.ValidationError{Reason: "field Share must be greater than 0", Path: "NomineeShareEntry.Share", Type: "gt"}

	// ErrNomineeShareEntryShareLTEValidation is the error returned when the value of the field is greater than 100.
	ErrNomineeShareEntryShareLTEValidation = govaliderrors.ValidationError{Reason: "field Share must be less than or equal to 100", Path: "NomineeShareEntry.Share", Type: "lte"}

	// ErrNomineeShareEntryShareRequiredValidation is returned when the Share is required but not provided.
	ErrNomineeShareEntryShareRequiredValidation = govaliderrors.ValidationError{Reason: "field Share is required", Path: "NomineeShareEntry.Share", Type: "required"}
)

func ValidateNomineeShareEntry(t *NomineeShareEntry) error {
	if t == nil {
		return ErrNilNomineeShareEntry
	}

	var errs govaliderrors.ValidationErrors

	if !(t.Share > 0) {
		err := ErrNomineeShareEntryShareGTValidation
		err.Value = t.Share
		errs = append(errs, err)
	}

	if !(t.Share <= 100) {
		err := ErrNomineeShareEntryShareLTEValidation
		err.Value = t.Share
		errs = append(errs, err)
	}

	if t.Share == 0.0 {
		err := ErrNomineeShareEntryShareRequiredValidation
		err.Value = t.Share
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*NomineeShareEntry)(nil)

func (t *NomineeShareEntry) Validate() error {
	return ValidateNomineeShareEntry(t)
}
