// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilBankAccountInput is returned when the BankAccountInput is nil.
	ErrNilBankAccountInput = errors.New("input BankAccountInput is nil")

	// ErrBankAccountInputAccountNumberMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 18.
	ErrBankAccountInputAccountNumberMaxLengthValidation = govaliderrors.ValidationError{Reason: "field AccountNumber must have a maximum length of 18", Path: "BankAccountInput.AccountNumber", Type: "maxlength"}

	// ErrBankAccountInputAccountNumberMinLengthValidation is the error returned when the length of the field is less than the minimum of 9.
	ErrBankAccountInputAccountNumberMinLengthValidation = govaliderrors.ValidationError{Reason: "field AccountNumber must have a minimum length of 9", Path: "BankAccountInput.AccountNumber", Type: "minlength"}

	// ErrBankAccountInputAccountNumberRequiredValidation is returned when the AccountNumber is required but not provided.
	ErrBankAccountInputAccountNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field AccountNumber is required", Path: "BankAccountInput.AccountNumber", Type: "required"}

	// ErrBankAccountInputIFSCCodeLengthValidation is the error returned when the length of the field is not exactly 11.
	ErrBankAccountInputIFSCCodeLengthValidation = govaliderrors.ValidationError{Reason: "field IFSCCode length must be exactly 11", Path: "BankAccountInput.IFSCCode", Type: "length"}

	// ErrBankAccountInputIFSCCodeRequiredValidation is returned when the IFSCCode is required but not provided.
	ErrBankAccountInputIFSCCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field IFSCCode is required", Path: "BankAccountInput.IFSCCode", Type: "required"}

	// ErrBankAccountInputBankNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrBankAccountInputBankNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field BankName must have a maximum length of 100", Path: "BankAccountInput.BankName", Type: "maxlength"}

	// ErrBankAccountInputBankNameMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrBankAccountInputBankNameMinLengthValidation = govaliderrors.ValidationError{Reason: "field BankName must have a minimum length of 1", Path: "BankAccountInput.BankName", Type: "minlength"}

	// ErrBankAccountInputBankNameRequiredValidation is returned when the BankName is required but not provided.
	ErrBankAccountInputBankNameRequiredValidation = govaliderrors.ValidationError{Reason: "field BankName is required", Path: "BankAccountInput.BankName", Type: "required"}

	// ErrBankAccountInputBranchNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrBankAccountInputBranchNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field BranchName must have a maximum length of 100", Path: "BankAccountInput.BranchName", Type: "maxlength"}

	// ErrBankAccountInputAccountTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrBankAccountInputAccountTypeOneofValidation = govaliderrors.ValidationError{Reason: "field AccountType must be one of SAVINGS CURRENT SALARY NRE NRO", Path: "BankAccountInput.AccountType", Type: "oneof"}

	// ErrBankAccountInputAccountTypeRequiredValidation is returned when the AccountType is required but not provided.
	ErrBankAccountInputAccountTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field AccountType is required", Path: "BankAccountInput.AccountType", Type: "required"}

	// ErrBankAccountInputPurposeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrBankAccountInputPurposeOneofValidation = govaliderrors.ValidationError{Reason: "field Purpose must be one of PREMIUM_PAYMENT CLAIM_SETTLEMENT REFUND", Path: "BankAccountInput.Purpose", Type: "oneof"}

	// ErrBankAccountInputPurposeRequiredValidation is returned when the Purpose is required but not provided.
	ErrBankAccountInputPurposeRequiredValidation = govaliderrors.ValidationError{Reason: "field Purpose is required", Path: "BankAccountInput.Purpose", Type: "required"}

	// ErrBankAccountInputIsPrimaryRequiredValidation is returned when the IsPrimary is required but not provided.
	ErrBankAccountInputIsPrimaryRequiredValidation = govaliderrors.ValidationError{Reason: "field IsPrimary is required", Path: "BankAccountInput.IsPrimary", Type: "required"}
)

func ValidateBankAccountInput(t *BankAccountInput) error {
	if t == nil {
		return ErrNilBankAccountInput
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.AccountNumber) > 18 {
		err := ErrBankAccountInputAccountNumberMaxLengthValidation
		err.Value = t.AccountNumber
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.AccountNumber) < 9 {
		err := ErrBankAccountInputAccountNumberMinLengthValidation
		err.Value = t.AccountNumber
		errs = append(errs, err)
	}

	if t.AccountNumber == "" {
		err := ErrBankAccountInputAccountNumberRequiredValidation
		err.Value = t.AccountNumber
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.IFSCCode) != 11 {
		err := ErrBankAccountInputIFSCCodeLengthValidation
		err.Value = t.IFSCCode
		errs = append(errs, err)
	}

	if t.IFSCCode == "" {
		err := ErrBankAccountInputIFSCCodeRequiredValidation
		err.Value = t.IFSCCode
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.BankName) > 100 {
		err := ErrBankAccountInputBankNameMaxLengthValidation
		err.Value = t.BankName
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.BankName) < 1 {
		err := ErrBankAccountInputBankNameMinLengthValidation
		err.Value = t.BankName
		errs = append(errs, err)
	}

	if t.BankName == "" {
		err := ErrBankAccountInputBankNameRequiredValidation
		err.Value = t.BankName
		errs = append(errs, err)
	}

	if t.BranchName != "" && utf8.RuneCountInString(t.BranchName) > 100 {
		err := ErrBankAccountInputBranchNameMaxLengthValidation
		err.Value = t.BranchName
		errs = append(errs, err)
	}

	if !(t.AccountType == "SAVINGS" || t.AccountType == "CURRENT" || t.AccountType == "SALARY" || t.AccountType == "NRE" || t.AccountType == "NRO") {
		err := ErrBankAccountInputAccountTypeOneofValidation
		err.Value = t.AccountType
		errs = append(errs, err)
	}

	if t.AccountType == "" {
		err := ErrBankAccountInputAccountTypeRequiredValidation
		err.Value = t.AccountType
		errs = append(errs, err)
	}

	if !(t.Purpose == "PREMIUM_PAYMENT" || t.Purpose == "CLAIM_SETTLEMENT" || t.Purpose == "REFUND") {
		err := ErrBankAccountInputPurposeOneofValidation
		err.Value = t.Purpose
		errs = append(errs, err)
	}

	if t.Purpose == "" {
		err := ErrBankAccountInputPurposeRequiredValidation
		err.Value = t.Purpose
		errs = append(errs, err)
	}

	if t.IsPrimary == false {
		err := ErrBankAccountInputIsPrimaryRequiredValidation
		err.Value = t.IsPrimary
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*BankAccountInput)(nil)

func (t *BankAccountInput) Validate() error {
	return ValidateBankAccountInput(t)
}
