package workflow

import (
	"context"
	"fmt"
	"time"

	"plirevival/core/domain"
	repo "plirevival/repo/postgres"

	"github.com/google/uuid"
	log "gitlab.cept.gov.in/it-2.0-common/api-log"
)

// Activities for Revival Workflow

// Activities holds repository dependencies
type Activities struct {
	revivalRepo *repo.RevivalRepository
	policyRepo  *repo.PolicyRepository
	paymentRepo *repo.PaymentRepository
}

// NewActivities creates a new activities instance
func NewActivities(revivalRepo *repo.RevivalRepository, policyRepo *repo.PolicyRepository, paymentRepo *repo.PaymentRepository) *Activities {
	return &Activities{
		revivalRepo: revivalRepo,
		policyRepo:  policyRepo,
		paymentRepo: paymentRepo,
	}
}

// RevivalRequestInput for CreateRevivalRequestActivity
// type RevivalRequestInput struct {
// 	TicketID      string    `json:"ticket_id"`
// 	PolicyNumber  string    `json:"policy_number"`
// 	RequestType   string    `json:"request_type"`
// 	CurrentStatus string    `json:"current_status"`
// 	IndexedBy     string    `json:"indexed_by"`
// 	IndexedDate   time.Time `json:"indexed_date"`
// 	WorkflowID    string    `json:"workflow_id"`
// 	RunID         string    `json:"run_id"`
// }

// FirstCollectionInput represents input for first collection workflow
type FirstCollectionInput struct {
	RequestID         string
	PolicyNumber      string
	PremiumAmount     float64
	InstallmentAmount float64
	PaymentMode       string
	TotalAmount       float64
	ChequeNumber      *string
	BankName          *string
	ChequeDate        *time.Time
	ChequeAmount      *float64
	PremiumSGST       float64
	PremiumCGST       float64
	InstallmentSGST   float64
	InstallmentCGST   float64
}

// CreateRevivalRequestActivity creates the revival request in database with workflow IDs
// This is the FIRST activity in the workflow-first pattern
// Idempotent: Safe to retry (uses ON CONFLICT on ticket_id)
// Returns: request_id (UUID generated by database)
// Note: MissingDocumentsList is NOT stored at indexing - sent by data entry/QC/approver only
func (a *Activities) CreateRevivalRequestActivity(ctx context.Context, input RevivalRequestInput) (string, error) {
	// Prepare document field (empty string if not provided)
	// Note: MissingDocumentsList not stored at indexing
	var docs *string
	if input.Documents != "" {
		docs = &input.Documents
	}

	// Map workflow input to domain model
	revivalReq := domain.RevivalRequest{
		TicketID:      input.TicketID,
		PolicyNumber:  input.PolicyNumber,
		RequestType:   input.RequestType,
		CurrentStatus: input.CurrentStatus,
		IndexedDate:   &input.IndexedDate,
		IndexedBy:     &input.IndexedBy,
		WorkflowID:    &input.WorkflowID,
		RunID:         &input.RunID,

		// Documents from indexing (MissingDocumentsList not stored here)
		Documents: docs,

		// Initialize with defaults
		NumberOfInstallments:   0,
		RevivalAmount:          0.0,
		InstallmentAmount:      0.0,
		TotalTaxOnUnpaid:       0.0,
		FirstCollectionDone:    false,
		BlockingNewCollections: true,
		InstallmentsPaid:       0,
	}

	// Create revival request in database (idempotent with ON CONFLICT)
	created, err := a.revivalRepo.CreateRevivalRequest(ctx, revivalReq)
	if err != nil {
		return "", fmt.Errorf("failed to create revival request: %w", err)
	}

	// Handle pointer return
	if created == nil {
		return "", fmt.Errorf("created revival request is nil")
	}

	return created.RequestID, nil
}

// UpdateRevivalStatusActivity updates the current_status field in database
// Also creates a status change history record
func (a *Activities) UpdateRevivalStatusActivity(ctx context.Context, requestID string, newStatus string) error {
	// Use "SYSTEM" as changedBy since this is automated via workflow
	err := a.revivalRepo.UpdateRevivalRequestStatus(ctx, requestID, newStatus, "SYSTEM")
	if err != nil {
		return fmt.Errorf("failed to update revival status: %w", err)
	}

	return nil
}

// PolicyValidationResult returned by ValidatePolicyActivity
// Contains maturity date to cache in workflow state (reduces DB hits for IR_4 validation)
type PolicyValidationResult struct {
	MaturityDate time.Time `json:"maturity_date"`
}

// ValidatePolicyActivity validates policy for revival and returns maturity date
// OPTIMIZED: Single DB query (batch) for policy + config + ongoing revival count
// Returns maturity date to cache in workflow state for IR_4 validation
func (a *Activities) ValidatePolicyActivity(ctx context.Context, policyNumber string) (PolicyValidationResult, error) {
	// Single batched query: GetPolicyByNumber + CheckOngoingRevival + GetMaxRevivalsAllowed
	// Reduces 3 DB round trips to 1
	validation, err := a.policyRepo.ValidatePolicyForRevival(ctx, policyNumber)
	if err != nil {
		return PolicyValidationResult{}, fmt.Errorf("policy validation failed: %w", err)
	}

	// Check if policy is in AL (lapsed) status
	if validation.Policy.PolicyStatus != "AL" {
		return PolicyValidationResult{}, fmt.Errorf("policy is not in lapsed status, current status: %s", validation.Policy.PolicyStatus)
	}

	// Check for ongoing revival requests
	if validation.OngoingRevivalCount > 0 {
		return PolicyValidationResult{}, fmt.Errorf("ongoing revival request exists for policy")
	}

	// Check max revivals allowed
	if validation.Policy.RevivalCount >= validation.MaxRevivalsAllowed {
		return PolicyValidationResult{}, fmt.Errorf("max revivals (%d) exceeded for policy", validation.MaxRevivalsAllowed)
	}

	// Return maturity date to cache in workflow state
	return PolicyValidationResult{
		MaturityDate: validation.Policy.MaturityDate,
	}, nil
}

// ValidateDualCollectionActivity validates dual collection request (IR_36)
func (a *Activities) ValidateDualCollectionActivity(ctx context.Context, input FirstCollectionInput) error {
	// Validate Premium + Installment + GST = Total Amount (IR_36)
	totalAmount := input.PremiumAmount + input.InstallmentAmount + input.InstallmentCGST + input.InstallmentSGST + input.PremiumCGST + input.PremiumSGST

	// Use tolerance-based comparison for floating point (0.01 tolerance for currency)
	tolerance := 0.01
	diff := totalAmount - input.TotalAmount
	if diff < -tolerance || diff > tolerance {
		return fmt.Errorf("amount mismatch: premium (%.2f) + installment (%.2f) + GST (%.2f) = %.2f, expected %.2f (diff: %.4f)",
			input.PremiumAmount, input.InstallmentAmount,
			input.PremiumSGST+input.PremiumCGST+input.InstallmentSGST+input.InstallmentCGST,
			totalAmount, input.TotalAmount, diff)
	}

	// Validate payment mode is valid
	validModes := map[string]bool{"CASH": true, "CHEQUE": true, "NEFT": true, "RTGS": true, "UPI": true, "CARD": true}
	if !validModes[input.PaymentMode] {
		return fmt.Errorf("invalid payment mode: %s", input.PaymentMode)
	}

	// Validate collection date is not in future
	if input.ChequeDate != nil && input.ChequeDate.After(time.Now()) {
		return fmt.Errorf("cheque date cannot be in future")
	}

	return nil
}

// ProcessDualPaymentActivity processes dual payment (premium + installment)
func (a *Activities) ProcessDualPaymentActivity(ctx context.Context, input FirstCollectionInput, status string) error {
	// Generate batch ID as UUID for database compatibility
	batchID := uuid.New().String()

	// Map status to enum values: PENDING, COMPLETED, FAILED, CANCELLED
	dbStatus := "PENDING"
	if status == "PAID" || status == "CLEARED" || status == "COMPLETED" {
		dbStatus = "COMPLETED"
	} else if status == "FAILED" {
		dbStatus = "FAILED"
	} else if status == "CANCELLED" {
		dbStatus = "CANCELLED"
	}

	// Create premium payment transaction
	premiumTaxAmount := input.PremiumSGST + input.PremiumCGST
	premiumPayment := domain.PaymentTransaction{
		RequestID:      input.RequestID,
		PolicyNumber:   input.PolicyNumber,
		CollectionDate: time.Now(),
		PaymentMode:    input.PaymentMode,
		Amount:         input.PremiumAmount,
		TaxAmount:      premiumTaxAmount,
		TotalAmount:    input.PremiumAmount + premiumTaxAmount,
		PaymentStatus:  dbStatus,
		CollectedBy:    &[]string{""}[0], // Will be set from auth context
	}

	// Create installment payment transaction
	installmentTaxAmount := input.InstallmentSGST + input.InstallmentCGST
	installmentPayment := domain.PaymentTransaction{
		RequestID:      input.RequestID,
		PolicyNumber:   input.PolicyNumber,
		CollectionDate: time.Now(),
		PaymentMode:    input.PaymentMode,
		Amount:         input.InstallmentAmount,
		TaxAmount:      installmentTaxAmount,
		TotalAmount:    input.InstallmentAmount + installmentTaxAmount,
		PaymentStatus:  dbStatus,
		CollectedBy:    &[]string{""}[0], // Will be set from auth context
	}

	// Create dual payment records in batch (IR_36)
	err := a.paymentRepo.CreateDualPaymentRecords(ctx, premiumPayment, installmentPayment, batchID)
	if err != nil {
		return fmt.Errorf("failed to create dual payment records: %w", err)
	}

	// Update revival request status if payment is complete
	if status == "PAID" || status == "CLEARED" {
		err = a.revivalRepo.UpdateRevivalRequestForFirstCollection(ctx, input.RequestID)
		if err != nil {
			return fmt.Errorf("failed to update revival request for first collection: %w", err)
		}
	}

	return nil
}

// CreateChequeRecordActivity creates cheque tracking record
func (a *Activities) CreateChequeRecordActivity(ctx context.Context, input FirstCollectionInput) (string, error) {
	// Only create if cheque mode
	if input.PaymentMode != "CHEQUE" || input.ChequeNumber == nil {
		return "", fmt.Errorf("cheque details required for cheque mode")
	}

	chequeID := fmt.Sprintf("CHEQUE%s", time.Now().Format("20060102150405"))

	// Create cheque clearing status record
	chequeStatus := domain.ChequeClearingStatus{
		ChequeID:        chequeID,
		RequestID:       input.RequestID,
		PolicyNumber:    input.PolicyNumber,
		ChequeNumber:    *input.ChequeNumber,
		BankName:        *input.BankName,
		ChequeDate:      *input.ChequeDate,
		Amount:          *input.ChequeAmount,
		ClearanceStatus: "PENDING",
	}

	err := a.paymentRepo.CreateChequeClearingRecord(ctx, chequeStatus)
	if err != nil {
		return "", fmt.Errorf("failed to create cheque record: %w", err)
	}

	return chequeID, nil
}

// ProcessInstallmentActivity processes subsequent installment payment
func (a *Activities) ProcessInstallmentActivity(ctx context.Context, requestID string, installmentNumber int, amount float64, paymentMode, status string, collectionDate time.Time) error {
	log.Info(nil, "🎯 ProcessInstallmentActivity STARTED",
		"request_id", requestID,
		"installment_number", installmentNumber,
		"amount", amount,
		"payment_mode", paymentMode,
		"status", status,
		"collection_date", collectionDate)

	// Get revival request
	revivalReq, err := a.revivalRepo.GetRevivalRequestByID(ctx, requestID)
	if err != nil {
		log.Error(nil, "❌ Failed to get revival request in activity", "error", err)
		return fmt.Errorf("failed to get revival request: %w", err)
	}

	// Validate installment number
	if installmentNumber < 2 || installmentNumber > revivalReq.NumberOfInstallments {
		return fmt.Errorf("invalid installment number: %d, total installments: %d",
			installmentNumber, revivalReq.NumberOfInstallments)
	}

	// Create installment schedule record
	scheduleID := fmt.Sprintf("SCHED%s", time.Now().Format("20060102150405"))

	// Calculate due date (IR_11: 1st of each month)
	// This would be calculated based on installment number
	now := time.Now()
	dueDate := time.Date(now.Year(), now.Month()+time.Month(installmentNumber-1), 1, 0, 0, 0, now.Nanosecond(), now.Location())

	// Create installment schedule record in database
	isPaid := status == "PAID" || status == "CLEARED"
	err = a.revivalRepo.CreateInstallmentSchedule(
		ctx, scheduleID, requestID, revivalReq.PolicyNumber,
		installmentNumber, amount, 0, amount, dueDate, isPaid,
	)
	if err != nil {
		return fmt.Errorf("failed to create installment schedule: %w", err)
	}

	// Update revival request if payment is complete
	if status == "PAID" || status == "CLEARED" {
		log.Info(nil, "💰 Processing PAID installment", "installment_number", installmentNumber)

		// Increment installmentsPaid in revival request
		log.Info(nil, "⬆️ Incrementing installments_paid", "request_id", requestID)
		err = a.revivalRepo.IncrementInstallmentsPaid(ctx, requestID)
		if err != nil {
			log.Error(nil, "❌ Failed to increment installments paid", "error", err)
			return fmt.Errorf("failed to increment installments paid: %w", err)
		}
		log.Info(nil, "✅ Successfully incremented installments_paid")

		installmentPayment := domain.PaymentTransaction{
			RequestID:         requestID,
			PolicyNumber:      revivalReq.PolicyNumber,
			InstallmentNumber: &installmentNumber,
			Amount:            amount,
			TaxAmount:         0,
			TotalAmount:       amount,
			PaymentMode:       paymentMode,
			PaymentStatus:     "COMPLETED",
			CollectionDate:    collectionDate,
			CollectedBy:       &[]string{""}[0], // TODO: set from auth context
		}

		log.Info(nil, "💳 Creating payment record in database",
			"request_id", requestID,
			"installment_number", installmentNumber,
			"amount", amount,
			"collection_date", collectionDate)

		paymentID, err := a.paymentRepo.CreateInstallmentPayment(ctx, installmentPayment)
		if err != nil {
			log.Error(nil, "❌ Failed to create payment record", "error", err)
			return fmt.Errorf("failed to create installment payment transaction: %w", err)
		}

		log.Info(nil, "✅ Payment record created successfully", "payment_id", paymentID)

		// Check if all installments paid, set status to COMPLETED
		revivalReq, err := a.revivalRepo.GetRevivalRequestByID(ctx, requestID)
		if err != nil {
			return fmt.Errorf("failed to get revival request: %w", err)
		}

		totalPaid := float64(revivalReq.InstallmentsPaid) * revivalReq.InstallmentAmount

		completed := false

		if revivalReq.AdjustedRevivalAmount == 0 {
			if revivalReq.InstallmentsPaid >= revivalReq.NumberOfInstallments {
				completed = true
			}
		} else {
			// Re-revival: amount-based completion
			if totalPaid >= revivalReq.AdjustedRevivalAmount {
				completed = true
			}
		}

		if completed {
			// All installments paid - mark as COMPLETED
			err = a.revivalRepo.UpdateRevivalRequestForCompletion(ctx, requestID)
			if err != nil {
				return fmt.Errorf("failed to complete revival request: %w", err)
			}

			// Update policy status to IF (In Force)
			err = a.policyRepo.UpdatePolicyStatus(ctx, revivalReq.PolicyNumber, "IF")
			if err != nil {
				return fmt.Errorf("failed to update policy status: %w", err)
			}

			// Increment revival count
			now := time.Now()
			err = a.policyRepo.IncrementRevivalCount(ctx, revivalReq.PolicyNumber, &now)
			if err != nil {
				return fmt.Errorf("failed to increment revival count: %w", err)
			}
		}
	}

	return nil
}

// HandleDefaultActivity handles installment default (moves to suspense, reverts to AL, terminates workflow)
// This is called when an installment due date passes without payment (IR_9: Zero grace period)
// Process:
// 1. Create suspense entry for premium (first collection)
// 2. Create suspense entry for each paid installment
// 3. Create termination record in database
// 4. Revert policy status to AL (lapsed)
// 5. Update revival request status to DEFAULTED
func (a *Activities) HandleDefaultActivity(ctx context.Context, requestID string, installmentNumber int) error {
	// Get revival request
	revivalReq, err := a.revivalRepo.GetRevivalRequestByID(ctx, requestID)
	if err != nil {
		return fmt.Errorf("failed to get revival request: %w", err)
	}

	collectedPremium, err := a.paymentRepo.GetTotalPremiumPaid(ctx, requestID)
	if err != nil {
		return fmt.Errorf("failed to fetch collected premium: %w", err)
	}

	systemUser := "SYSTEM"
	totalSuspenseAmount := 0.0

	// 1. Move all collected amounts to suspense (IR_28)
	// Create suspense entry for premium amount (first collection)
	premiumSuspenseID := uuid.New().String()
	premiumSuspense := domain.SuspenseAccount{
		SuspenseID:          premiumSuspenseID,
		PolicyNumber:        revivalReq.PolicyNumber,
		RequestID:           &requestID,
		SuspenseType:        "REVIVAL_PREMIUM",
		SuspenseAccountType: "REVIVAL_SUSPENSE",
		Amount:              collectedPremium, // Premium amount from first collection
		IsReversed:          false,
		CreatedAt:           time.Now(),
		CreatedBy:           &systemUser,
		UpdatedAt:           time.Now(),
		Reason:              "Payment not made in due time",
	}

	err = a.paymentRepo.CreateSuspenseEntry(ctx, premiumSuspense)
	if err != nil {
		return fmt.Errorf("failed to create premium suspense entry: %w", err)
	}
	totalSuspenseAmount += revivalReq.RevivalAmount

	// 2. Create suspense entry for each collected installment (including first installment from dual collection)
	// First installment was part of first collection, subsequent paid are installments 2+
	installmentsPaidCount := revivalReq.InstallmentsPaid
	for i := 1; i <= installmentsPaidCount; i++ {
		installmentSuspenseID := uuid.New().String()
		installmentSuspense := domain.SuspenseAccount{
			SuspenseID:   installmentSuspenseID,
			PolicyNumber: revivalReq.PolicyNumber,
			RequestID:    &requestID,
			//SuspenseType: fmt.Sprintf("REVIVAL_INSTALLMENT_%d", i),
			SuspenseType:        "REVIVAL_INSTALLMENT",
			SuspenseAccountType: "REVIVAL_SUSPENSE",
			Amount:              revivalReq.InstallmentAmount,
			IsReversed:          false,
			CreatedAt:           time.Now(),
			CreatedBy:           &systemUser,
			UpdatedAt:           time.Now(),
		}

		err = a.paymentRepo.CreateSuspenseEntry(ctx, installmentSuspense)
		if err != nil {
			return fmt.Errorf("failed to create installment %d suspense entry: %w", i, err)
		}
		totalSuspenseAmount += revivalReq.InstallmentAmount
	}

	// 3. Create termination record
	terminationID := uuid.New().String()
	termination := domain.RevivalTermination{
		TerminationID:     terminationID,
		RequestID:         requestID,
		TicketID:          revivalReq.TicketID,
		PolicyNumber:      revivalReq.PolicyNumber,
		TerminationReason: fmt.Sprintf("Installment %d payment not received by due date (IR_9: Zero grace period)", installmentNumber),
		TerminationType:   "DEFAULT",
		InstallmentNumber: installmentNumber,
		SuspenseCreated:   true,
		SuspenseAmount:    totalSuspenseAmount,
		TerminatedAt:      time.Now(),
		TerminatedBy:      &systemUser,
		CreatedAt:         time.Now(),
	}

	err = a.revivalRepo.CreateRevivalTermination(ctx, &termination)
	if err != nil {
		return fmt.Errorf("failed to create revival termination record: %w", err)
	}

	// 4. Revert policy status to AL (lapsed)
	err = a.policyRepo.UpdatePolicyStatus(ctx, revivalReq.PolicyNumber, "AL")
	if err != nil {
		return fmt.Errorf("failed to revert policy status to AL: %w", err)
	}

	// 5. Update revival request status to DEFAULTED
	err = a.revivalRepo.UpdateRevivalRequestStatus(ctx, requestID, "DEFAULTED", "SYSTEM")
	if err != nil {
		return fmt.Errorf("failed to update revival request status to DEFAULTED: %w", err)
	}

	return nil
}

// TerminateRevivalActivity terminates revival request (60-day SLA expiry)
func (a *Activities) TerminateRevivalActivity(ctx context.Context, requestID, reason string) error {
	// Get revival request
	_, err := a.revivalRepo.GetRevivalRequestByID(ctx, requestID)
	if err != nil {
		return fmt.Errorf("failed to get revival request: %w", err)
	}

	// Update revival request status to TERMINATED
	err = a.revivalRepo.UpdateRevivalRequestForTermination(ctx, requestID)
	if err != nil {
		return fmt.Errorf("failed to update revival request for termination: %w", err)
	}

	// Note: Would need to revert policy status and handle suspense reversals
	_ = reason

	return nil
}

// GenerateLetterActivity generates letters (acceptance, rejection, memo)
func (a *Activities) GenerateLetterActivity(ctx context.Context, letterType, requestID, policyNumber string) (string, error) {
	// Generate letter ID
	letterID := fmt.Sprintf("LETTER%s", time.Now().Format("20060102150405"))

	// This would call Document System API to generate PDF
	// Store letter_id in database
	// Send notification to policyholder

	// Note: In production, would integrate with Document System
	_ = policyNumber
	_ = letterType

	return letterID, nil
}

// SendNotificationActivity sends notifications (SMS/Email)
func (a *Activities) SendNotificationActivity(ctx context.Context, recipient, message, channel string) error {
	// Call Notification System API
	_ = recipient
	_ = message
	_ = channel

	// This would integrate with notification service
	// Example: notifService.Send(ctx, recipient, message, channel)

	return nil
}

// UpdateDataEntryActivity updates revival request with data entry details
// Used in signal-first pattern: handler sends signal, workflow updates DB via activity
// Idempotent: Safe to retry
// Takes full DataEntryRequest to ensure all fields are captured
func (a *Activities) UpdateDataEntryActivity(ctx context.Context, requestID string, req DataEntryInput) error {
	err := a.revivalRepo.UpdateRevivalRequestForDataEntry(
		ctx,
		requestID,
		req.DataEnteredBy,
		req.RevivalType,
		req.NumberOfInstallments,
		req.RevivalAmount,
		req.InstallmentAmount,
		req.SGST,
		req.CGST,
		req.Interest,
		req.Documents,
		req.MissingDocuments,
		req.MedicalExaminerCode,
		req.MedicalExaminerName,
	)
	if err != nil {
		return fmt.Errorf("failed to update data entry: %w", err)
	}
	return nil
}

// DataEntryInput contains all data entry fields for the activity
type DataEntryInput struct {
	DataEnteredBy        string    `json:"data_entered_by"`
	RevivalType          string    `json:"revival_type"`
	NumberOfInstallments int       `json:"number_of_installments"`
	RevivalAmount        float64   `json:"revival_amount"`
	InstallmentAmount    float64   `json:"installment_amount"`
	DataEntryTimestamp   time.Time `json:"data_entry_timestamp"`
	MissingDocuments     string    `json:"missing_documents"` // JSON string
	Documents            string    `json:"documents"`         // JSON string
	SGST                 float64   `json:"sgst"`
	CGST                 float64   `json:"cgst"`
	Interest             float64   `json:"interest"`
	MedicalExaminerCode  string    `json:"medical_examiner_code"`
	MedicalExaminerName  string    `json:"medical_examiner_name"`
}

// UpdateQCActivity updates revival request with quality check details
// Used in signal-first pattern: handler sends signal, workflow updates DB via activity
// Idempotent: Safe to retry
func (a *Activities) UpdateQCActivity(ctx context.Context, requestID, qcPerformedBy, qcComments string, qcPassed bool, missingDocuments string) error {
	err := a.revivalRepo.UpdateRevivalRequestForQC(ctx, requestID, qcPerformedBy, qcComments, qcPassed, missingDocuments)
	if err != nil {
		return fmt.Errorf("failed to update QC: %w", err)
	}
	return nil
}

// UpdateApprovalActivity updates revival request with approval details
// Used in signal-first pattern: handler sends signal, workflow updates DB via activity
// Idempotent: Safe to retry
func (a *Activities) UpdateApprovalActivity(ctx context.Context, ticketID, approvedBy, comments string, slaStartDate, slaEndDate time.Time) error {
	err := a.revivalRepo.UpdateRevivalRequestForApproval(ctx, ticketID, approvedBy, comments, slaStartDate, slaEndDate)
	if err != nil {
		return fmt.Errorf("failed to update approval: %w", err)
	}
	return nil
}

// ValidateMaturityDateConstraintActivity validates IR_4 compliance
// Checks if last installment due date falls before maturity date
// Returns error if constraint violated (used for Temporal timer validation)
// OPTIMIZED: Accepts maturity date directly to avoid DB read - maturity date cached in workflow state
func (a *Activities) ValidateMaturityDateConstraintActivity(
	ctx context.Context,
	maturityDate time.Time, // Passed from workflow state - no DB read needed
	numberOfInstallments int,
	firstDueDate time.Time,
) error {
	// Calculate last installment due date
	// First installment: firstDueDate
	// Subsequent installments: 1st of next months (IR_11)
	lastDueDate := firstDueDate.AddDate(0, numberOfInstallments-1, 0)

	// For 2+ installments, adjust to 1st of the month
	if numberOfInstallments > 1 {
		lastDueDate = time.Date(
			lastDueDate.Year(),
			lastDueDate.Month(),
			1, 0, 0, 0, 0,
			lastDueDate.Location(),
		)
	}

	// Check IR_4 constraint: last installment must not fall after maturity
	if lastDueDate.After(maturityDate) {
		return fmt.Errorf(
			"IR_4 violation: last installment due (%s) falls after maturity date (%s)",
			lastDueDate.Format("2006-01-02"),
			maturityDate.Format("2006-01-02"),
		)
	}

	// Check IR_4 constraint: last installment must not fall in maturity month
	if lastDueDate.Year() == maturityDate.Year() &&
		lastDueDate.Month() == maturityDate.Month() {
		return fmt.Errorf(
			"IR_4 violation: last installment due (%s) falls in maturity month (%s)",
			lastDueDate.Format("2006-01-02"),
			maturityDate.Format("2006-01"),
		)
	}

	return nil
}

// TerminateAndReturnToIndexerActivity terminates workflow and updates status
// This happens when maturity date constraint violated or documents invalid
// Updates status to RETURNED_TO_INDEXER for indexer inbox
func (a *Activities) TerminateAndReturnToIndexerActivity(
	ctx context.Context,
	requestID string,
	reason string,
	stage string,
) error {
	// Update revival request status to RETURNED_TO_INDEXER
	err := a.revivalRepo.UpdateRevivalRequestStatus(
		ctx,
		requestID,
		"RETURNED_TO_INDEXER",
		"SYSTEM",
	)
	if err != nil {
		return fmt.Errorf("failed to update status: %w", err)
	}

	// Note: In production, would create indexer inbox entry
	// and send notification to indexer
	// For now, logging the termination
	_ = reason
	_ = stage

	return nil
}

// SuspenseAdjustmentResult contains the result of suspense adjustment check
type SuspenseAdjustmentResult struct {
	HasSuspense           bool    `json:"has_suspense"`
	TotalSuspenseAmount   float64 `json:"total_suspense_amount"`
	OriginalRevivalAmount float64 `json:"original_revival_amount"`
	AdjustedRevivalAmount float64 `json:"adjusted_revival_amount"`
	SuspenseEntriesCount  int     `json:"suspense_entries_count"`
}

// CheckAndAdjustSuspenseActivity checks for existing suspense and adjusts revival amount
// This is called during data entry for re-revival scenarios
// Process:
// 1. Check if policy has any non-reversed suspense entries
// 2. If suspense exists, calculate total suspense amount
// 3. Adjust revival amount = original_revival_amount - total_suspense
// 4. Mark all suspense entries as reversed (adjusted against new revival)
// 5. Update revival request with adjustment information
// 6. Return adjustment result for workflow decision-making
func (a *Activities) CheckAndAdjustSuspenseActivity(ctx context.Context, requestID, policyNumber string, originalRevivalAmount float64) (SuspenseAdjustmentResult, error) {
	result := SuspenseAdjustmentResult{
		HasSuspense:           false,
		TotalSuspenseAmount:   0.0,
		OriginalRevivalAmount: originalRevivalAmount,
		AdjustedRevivalAmount: originalRevivalAmount,
		SuspenseEntriesCount:  0,
	}

	// 1. Check for active suspense entries
	suspenseEntries, err := a.paymentRepo.GetActiveSuspenseByPolicy(ctx, policyNumber)
	if err != nil {
		log.Error(ctx, "Error fetching active suspense entries", err)
		return result, fmt.Errorf("failed to get active suspense: %w", err)
	}

	// If no suspense exists, return early with no adjustment
	if len(suspenseEntries) == 0 {
		return result, nil
	}

	// 2. Calculate total suspense amount
	totalSuspense := 0.0
	for _, entry := range suspenseEntries {
		totalSuspense += entry.Amount
	}

	// 3. Calculate adjusted revival amount
	adjustedAmount := originalRevivalAmount - totalSuspense

	fmt.Println("original amount:", originalRevivalAmount, "total suspense:", totalSuspense, "adjusted amount:", adjustedAmount)

	// Validate adjusted amount is positive
	if adjustedAmount < 0 {
		return result, fmt.Errorf(
			"suspense amount (%.2f) exceeds revival amount (%.2f), adjusted amount would be negative (%.2f)",
			totalSuspense, originalRevivalAmount, adjustedAmount,
		)
	}

	// 4. Mark suspense entries as reversed (adjusted against new revival)
	err = a.paymentRepo.ReverseSuspenseForAdjustment(ctx, policyNumber, requestID, "SYSTEM")
	if err != nil {
		return result, fmt.Errorf("failed to reverse suspense entries: %w", err)
	}

	// 5. Update revival request with adjustment information
	err = a.revivalRepo.UpdateRevivalRequestWithSuspenseAdjustment(ctx, requestID, totalSuspense, adjustedAmount)
	if err != nil {
		return result, fmt.Errorf("failed to update revival request with suspense adjustment: %w", err)
	}

	// 6. Return adjustment result
	result.HasSuspense = true
	result.TotalSuspenseAmount = totalSuspense
	result.AdjustedRevivalAmount = adjustedAmount
	result.SuspenseEntriesCount = len(suspenseEntries)

	return result, nil
}

// When all installments paid, set status to COMPLETED
func (a *Activities) FinalizeRevivalAfterFirstCollection(ctx context.Context, requestID string) error {
	// Get revival request
	revivalReq, err := a.revivalRepo.GetRevivalRequestByID(ctx, requestID)
	if err != nil {
		return fmt.Errorf("failed to get revival request: %w", err)
	}

	// 1. Mark revival COMPLETED
	err = a.revivalRepo.UpdateRevivalRequestForCompletion(ctx, requestID)
	if err != nil {
		return fmt.Errorf("failed to complete revival request: %w", err)
	}

	// 2. Update policy status to IF
	err = a.policyRepo.UpdatePolicyStatus(ctx, revivalReq.PolicyNumber, "IF")
	if err != nil {
		return fmt.Errorf("failed to update policy status: %w", err)
	}

	// 3. Increment revival count
	now := time.Now()
	err = a.policyRepo.IncrementRevivalCount(ctx, revivalReq.PolicyNumber, &now)
	if err != nil {
		return fmt.Errorf("failed to increment revival count: %w", err)
	}

	return nil
}

func (a *Activities) UpdateWorkflowStateActivity(
	ctx context.Context,
	requestID string,
	status string,
	slaStart, slaEnd time.Time,
) error {
	return a.revivalRepo.UpdateWorkflowState(ctx, requestID, status, slaStart, slaEnd)
}
