// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilReserveRequestRequest is returned when the ReserveRequestRequest is nil.
	ErrNilReserveRequestRequest = errors.New("input ReserveRequestRequest is nil")

	// ErrReserveRequestRequestTaskIDRequiredValidation is returned when the TaskID is required but not provided.
	ErrReserveRequestRequestTaskIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TaskID is required", Path: "ReserveRequestRequest.TaskID", Type: "required"}
)

func ValidateReserveRequestRequest(t *ReserveRequestRequest) error {
	if t == nil {
		return ErrNilReserveRequestRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TaskID == "" {
		err := ErrReserveRequestRequestTaskIDRequiredValidation
		err.Value = t.TaskID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ReserveRequestRequest)(nil)

func (t *ReserveRequestRequest) Validate() error {
	return ValidateReserveRequestRequest(t)
}
