// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilCreateForcedSurrenderRequest is returned when the CreateForcedSurrenderRequest is nil.
	ErrNilCreateForcedSurrenderRequest = errors.New("input CreateForcedSurrenderRequest is nil")

	// ErrCreateForcedSurrenderRequestPolicyIDRequiredValidation is returned when the PolicyID is required but not provided.
	ErrCreateForcedSurrenderRequestPolicyIDRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyID is required", Path: "CreateForcedSurrenderRequest.PolicyID", Type: "required"}
)

func ValidateCreateForcedSurrenderRequest(t *CreateForcedSurrenderRequest) error {
	if t == nil {
		return ErrNilCreateForcedSurrenderRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.PolicyID == "" {
		err := ErrCreateForcedSurrenderRequestPolicyIDRequiredValidation
		err.Value = t.PolicyID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CreateForcedSurrenderRequest)(nil)

func (t *CreateForcedSurrenderRequest) Validate() error {
	return ValidateCreateForcedSurrenderRequest(t)
}
