// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilIndexSurrenderRequest is returned when the IndexSurrenderRequest is nil.
	ErrNilIndexSurrenderRequest = errors.New("input IndexSurrenderRequest is nil")

	// ErrIndexSurrenderRequestPolicyNumberRequiredValidation is returned when the PolicyNumber is required but not provided.
	ErrIndexSurrenderRequestPolicyNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyNumber is required", Path: "IndexSurrenderRequest.PolicyNumber", Type: "required"}
)

func ValidateIndexSurrenderRequest(t *IndexSurrenderRequest) error {
	if t == nil {
		return ErrNilIndexSurrenderRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.PolicyNumber == "" {
		err := ErrIndexSurrenderRequestPolicyNumberRequiredValidation
		err.Value = t.PolicyNumber
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*IndexSurrenderRequest)(nil)

func (t *IndexSurrenderRequest) Validate() error {
	return ValidateIndexSurrenderRequest(t)
}
