// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilApproveSurrenderRequest is returned when the ApproveSurrenderRequest is nil.
	ErrNilApproveSurrenderRequest = errors.New("input ApproveSurrenderRequest is nil")

	// ErrApproveSurrenderRequestSurrenderRequestIDRequiredValidation is returned when the SurrenderRequestID is required but not provided.
	ErrApproveSurrenderRequestSurrenderRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SurrenderRequestID is required", Path: "ApproveSurrenderRequest.SurrenderRequestID", Type: "required"}

	// ErrApproveSurrenderRequestCommentsMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 500.
	ErrApproveSurrenderRequestCommentsMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Comments must have a maximum length of 500", Path: "ApproveSurrenderRequest.Comments", Type: "maxlength"}

	// ErrApproveSurrenderRequestCommentsMinLengthValidation is the error returned when the length of the field is less than the minimum of 10.
	ErrApproveSurrenderRequestCommentsMinLengthValidation = govaliderrors.ValidationError{Reason: "field Comments must have a minimum length of 10", Path: "ApproveSurrenderRequest.Comments", Type: "minlength"}

	// ErrApproveSurrenderRequestCommentsRequiredValidation is returned when the Comments is required but not provided.
	ErrApproveSurrenderRequestCommentsRequiredValidation = govaliderrors.ValidationError{Reason: "field Comments is required", Path: "ApproveSurrenderRequest.Comments", Type: "required"}

	// ErrApproveSurrenderRequestApproverIDRequiredValidation is returned when the ApproverID is required but not provided.
	ErrApproveSurrenderRequestApproverIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApproverID is required", Path: "ApproveSurrenderRequest.ApproverID", Type: "required"}

	// ErrApproveSurrenderRequestApproverUserIDRequiredValidation is returned when the ApproverUserID is required but not provided.
	ErrApproveSurrenderRequestApproverUserIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApproverUserID is required", Path: "ApproveSurrenderRequest.ApproverUserID", Type: "required"}

	// ErrApproveSurrenderRequestApprovalCommentsMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 500.
	ErrApproveSurrenderRequestApprovalCommentsMaxLengthValidation = govaliderrors.ValidationError{Reason: "field ApprovalComments must have a maximum length of 500", Path: "ApproveSurrenderRequest.ApprovalComments", Type: "maxlength"}

	// ErrApproveSurrenderRequestApprovalCommentsMinLengthValidation is the error returned when the length of the field is less than the minimum of 10.
	ErrApproveSurrenderRequestApprovalCommentsMinLengthValidation = govaliderrors.ValidationError{Reason: "field ApprovalComments must have a minimum length of 10", Path: "ApproveSurrenderRequest.ApprovalComments", Type: "minlength"}

	// ErrApproveSurrenderRequestApprovalCommentsRequiredValidation is returned when the ApprovalComments is required but not provided.
	ErrApproveSurrenderRequestApprovalCommentsRequiredValidation = govaliderrors.ValidationError{Reason: "field ApprovalComments is required", Path: "ApproveSurrenderRequest.ApprovalComments", Type: "required"}
)

func ValidateApproveSurrenderRequest(t *ApproveSurrenderRequest) error {
	if t == nil {
		return ErrNilApproveSurrenderRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.SurrenderRequestID == "" {
		err := ErrApproveSurrenderRequestSurrenderRequestIDRequiredValidation
		err.Value = t.SurrenderRequestID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.Comments) > 500 {
		err := ErrApproveSurrenderRequestCommentsMaxLengthValidation
		err.Value = t.Comments
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.Comments) < 10 {
		err := ErrApproveSurrenderRequestCommentsMinLengthValidation
		err.Value = t.Comments
		errs = append(errs, err)
	}

	if t.Comments == "" {
		err := ErrApproveSurrenderRequestCommentsRequiredValidation
		err.Value = t.Comments
		errs = append(errs, err)
	}

	if t.ApproverID == "" {
		err := ErrApproveSurrenderRequestApproverIDRequiredValidation
		err.Value = t.ApproverID
		errs = append(errs, err)
	}

	if t.ApproverUserID == "" {
		err := ErrApproveSurrenderRequestApproverUserIDRequiredValidation
		err.Value = t.ApproverUserID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.ApprovalComments) > 500 {
		err := ErrApproveSurrenderRequestApprovalCommentsMaxLengthValidation
		err.Value = t.ApprovalComments
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.ApprovalComments) < 10 {
		err := ErrApproveSurrenderRequestApprovalCommentsMinLengthValidation
		err.Value = t.ApprovalComments
		errs = append(errs, err)
	}

	if t.ApprovalComments == "" {
		err := ErrApproveSurrenderRequestApprovalCommentsRequiredValidation
		err.Value = t.ApprovalComments
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ApproveSurrenderRequest)(nil)

func (t *ApproveSurrenderRequest) Validate() error {
	return ValidateApproveSurrenderRequest(t)
}
