// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilTriggerReminderRequest is returned when the TriggerReminderRequest is nil.
	ErrNilTriggerReminderRequest = errors.New("input TriggerReminderRequest is nil")

	// ErrTriggerReminderRequestPolicyIDRequiredValidation is returned when the PolicyID is required but not provided.
	ErrTriggerReminderRequestPolicyIDRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyID is required", Path: "TriggerReminderRequest.PolicyID", Type: "required"}

	// ErrTriggerReminderRequestReminderLevelOneofValidation is the error returned when the field is not one of the allowed values.
	ErrTriggerReminderRequestReminderLevelOneofValidation = govaliderrors.ValidationError{Reason: "field ReminderLevel must be one of FIRST SECOND THIRD", Path: "TriggerReminderRequest.ReminderLevel", Type: "oneof"}

	// ErrTriggerReminderRequestReminderLevelRequiredValidation is returned when the ReminderLevel is required but not provided.
	ErrTriggerReminderRequestReminderLevelRequiredValidation = govaliderrors.ValidationError{Reason: "field ReminderLevel is required", Path: "TriggerReminderRequest.ReminderLevel", Type: "required"}
)

func ValidateTriggerReminderRequest(t *TriggerReminderRequest) error {
	if t == nil {
		return ErrNilTriggerReminderRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.PolicyID == "" {
		err := ErrTriggerReminderRequestPolicyIDRequiredValidation
		err.Value = t.PolicyID
		errs = append(errs, err)
	}

	if !(t.ReminderLevel == "FIRST" || t.ReminderLevel == "SECOND" || t.ReminderLevel == "THIRD") {
		err := ErrTriggerReminderRequestReminderLevelOneofValidation
		err.Value = t.ReminderLevel
		errs = append(errs, err)
	}

	if t.ReminderLevel == "" {
		err := ErrTriggerReminderRequestReminderLevelRequiredValidation
		err.Value = t.ReminderLevel
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*TriggerReminderRequest)(nil)

func (t *TriggerReminderRequest) Validate() error {
	return ValidateTriggerReminderRequest(t)
}
