// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilScheduleBatchRequest is returned when the ScheduleBatchRequest is nil.
	ErrNilScheduleBatchRequest = errors.New("input ScheduleBatchRequest is nil")

	// ErrScheduleBatchRequestProcessTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrScheduleBatchRequestProcessTypeOneofValidation = govaliderrors.ValidationError{Reason: "field ProcessType must be one of MONTHLY_EVALUATION REMINDER_BATCH AUTO_COMPLETION", Path: "ScheduleBatchRequest.ProcessType", Type: "oneof"}

	// ErrScheduleBatchRequestProcessTypeRequiredValidation is returned when the ProcessType is required but not provided.
	ErrScheduleBatchRequestProcessTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field ProcessType is required", Path: "ScheduleBatchRequest.ProcessType", Type: "required"}

	// ErrScheduleBatchRequestScheduledAtRequiredValidation is returned when the ScheduledAt is required but not provided.
	ErrScheduleBatchRequestScheduledAtRequiredValidation = govaliderrors.ValidationError{Reason: "field ScheduledAt is required", Path: "ScheduleBatchRequest.ScheduledAt", Type: "required"}
)

func ValidateScheduleBatchRequest(t *ScheduleBatchRequest) error {
	if t == nil {
		return ErrNilScheduleBatchRequest
	}

	var errs govaliderrors.ValidationErrors

	if !(t.ProcessType == "MONTHLY_EVALUATION" || t.ProcessType == "REMINDER_BATCH" || t.ProcessType == "AUTO_COMPLETION") {
		err := ErrScheduleBatchRequestProcessTypeOneofValidation
		err.Value = t.ProcessType
		errs = append(errs, err)
	}

	if t.ProcessType == "" {
		err := ErrScheduleBatchRequestProcessTypeRequiredValidation
		err.Value = t.ProcessType
		errs = append(errs, err)
	}

	if t.ScheduledAt == "" {
		err := ErrScheduleBatchRequestScheduledAtRequiredValidation
		err.Value = t.ScheduledAt
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ScheduleBatchRequest)(nil)

func (t *ScheduleBatchRequest) Validate() error {
	return ValidateScheduleBatchRequest(t)
}
