// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilRecordPaymentRequest is returned when the RecordPaymentRequest is nil.
	ErrNilRecordPaymentRequest = errors.New("input RecordPaymentRequest is nil")

	// ErrRecordPaymentRequestPaymentWindowIDRequiredValidation is returned when the PaymentWindowID is required but not provided.
	ErrRecordPaymentRequestPaymentWindowIDRequiredValidation = govaliderrors.ValidationError{Reason: "field PaymentWindowID is required", Path: "RecordPaymentRequest.PaymentWindowID", Type: "required"}

	// ErrRecordPaymentRequestAmountGTValidation is the error returned when the value of the field is less than the 0.
	ErrRecordPaymentRequestAmountGTValidation = govaliderrors.ValidationError{Reason: "field Amount must be greater than 0", Path: "RecordPaymentRequest.Amount", Type: "gt"}

	// ErrRecordPaymentRequestAmountRequiredValidation is returned when the Amount is required but not provided.
	ErrRecordPaymentRequestAmountRequiredValidation = govaliderrors.ValidationError{Reason: "field Amount is required", Path: "RecordPaymentRequest.Amount", Type: "required"}

	// ErrRecordPaymentRequestPaymentReferenceRequiredValidation is returned when the PaymentReference is required but not provided.
	ErrRecordPaymentRequestPaymentReferenceRequiredValidation = govaliderrors.ValidationError{Reason: "field PaymentReference is required", Path: "RecordPaymentRequest.PaymentReference", Type: "required"}

	// ErrRecordPaymentRequestPaymentDateRequiredValidation is returned when the PaymentDate is required but not provided.
	ErrRecordPaymentRequestPaymentDateRequiredValidation = govaliderrors.ValidationError{Reason: "field PaymentDate is required", Path: "RecordPaymentRequest.PaymentDate", Type: "required"}
)

func ValidateRecordPaymentRequest(t *RecordPaymentRequest) error {
	if t == nil {
		return ErrNilRecordPaymentRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.PaymentWindowID == "" {
		err := ErrRecordPaymentRequestPaymentWindowIDRequiredValidation
		err.Value = t.PaymentWindowID
		errs = append(errs, err)
	}

	if !(t.Amount > 0) {
		err := ErrRecordPaymentRequestAmountGTValidation
		err.Value = t.Amount
		errs = append(errs, err)
	}

	if t.Amount == 0.0 {
		err := ErrRecordPaymentRequestAmountRequiredValidation
		err.Value = t.Amount
		errs = append(errs, err)
	}

	if t.PaymentReference == "" {
		err := ErrRecordPaymentRequestPaymentReferenceRequiredValidation
		err.Value = t.PaymentReference
		errs = append(errs, err)
	}

	if t.PaymentDate == "" {
		err := ErrRecordPaymentRequestPaymentDateRequiredValidation
		err.Value = t.PaymentDate
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*RecordPaymentRequest)(nil)

func (t *RecordPaymentRequest) Validate() error {
	return ValidateRecordPaymentRequest(t)
}
