// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilSendReminderRequest is returned when the SendReminderRequest is nil.
	ErrNilSendReminderRequest = errors.New("input SendReminderRequest is nil")

	// ErrSendReminderRequestPolicyIDRequiredValidation is returned when the PolicyID is required but not provided.
	ErrSendReminderRequestPolicyIDRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyID is required", Path: "SendReminderRequest.PolicyID", Type: "required"}

	// ErrSendReminderRequestUnpaidMonthsRequiredValidation is returned when the UnpaidMonths is required but not provided.
	ErrSendReminderRequestUnpaidMonthsRequiredValidation = govaliderrors.ValidationError{Reason: "field UnpaidMonths is required", Path: "SendReminderRequest.UnpaidMonths", Type: "required"}
)

func ValidateSendReminderRequest(t *SendReminderRequest) error {
	if t == nil {
		return ErrNilSendReminderRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.PolicyID == "" {
		err := ErrSendReminderRequestPolicyIDRequiredValidation
		err.Value = t.PolicyID
		errs = append(errs, err)
	}

	if t.UnpaidMonths == 0 {
		err := ErrSendReminderRequestUnpaidMonthsRequiredValidation
		err.Value = t.UnpaidMonths
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*SendReminderRequest)(nil)

func (t *SendReminderRequest) Validate() error {
	return ValidateSendReminderRequest(t)
}
