// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilReserveTaskRequest is returned when the ReserveTaskRequest is nil.
	ErrNilReserveTaskRequest = errors.New("input ReserveTaskRequest is nil")

	// ErrReserveTaskRequestTaskIDRequiredValidation is returned when the TaskID is required but not provided.
	ErrReserveTaskRequestTaskIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TaskID is required", Path: "ReserveTaskRequest.TaskID", Type: "required"}

	// ErrReserveTaskRequestUserIDRequiredValidation is returned when the UserID is required but not provided.
	ErrReserveTaskRequestUserIDRequiredValidation = govaliderrors.ValidationError{Reason: "field UserID is required", Path: "ReserveTaskRequest.UserID", Type: "required"}
)

func ValidateReserveTaskRequest(t *ReserveTaskRequest) error {
	if t == nil {
		return ErrNilReserveTaskRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TaskID == "" {
		err := ErrReserveTaskRequestTaskIDRequiredValidation
		err.Value = t.TaskID
		errs = append(errs, err)
	}

	if t.UserID == "" {
		err := ErrReserveTaskRequestUserIDRequiredValidation
		err.Value = t.UserID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ReserveTaskRequest)(nil)

func (t *ReserveTaskRequest) Validate() error {
	return ValidateReserveTaskRequest(t)
}
