// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilDocumentStatusParams is returned when the DocumentStatusParams is nil.
	ErrNilDocumentStatusParams = errors.New("input DocumentStatusParams is nil")

	// ErrDocumentStatusParamsSurrenderRequestIDRequiredValidation is returned when the SurrenderRequestID is required but not provided.
	ErrDocumentStatusParamsSurrenderRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SurrenderRequestID is required", Path: "DocumentStatusParams.SurrenderRequestID", Type: "required"}
)

func ValidateDocumentStatusParams(t *DocumentStatusParams) error {
	if t == nil {
		return ErrNilDocumentStatusParams
	}

	var errs govaliderrors.ValidationErrors

	if t.SurrenderRequestID == "" {
		err := ErrDocumentStatusParamsSurrenderRequestIDRequiredValidation
		err.Value = t.SurrenderRequestID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*DocumentStatusParams)(nil)

func (t *DocumentStatusParams) Validate() error {
	return ValidateDocumentStatusParams(t)
}
