// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilConfirmSurrenderRequest is returned when the ConfirmSurrenderRequest is nil.
	ErrNilConfirmSurrenderRequest = errors.New("input ConfirmSurrenderRequest is nil")

	// ErrConfirmSurrenderRequestPolicyIDRequiredValidation is returned when the PolicyID is required but not provided.
	ErrConfirmSurrenderRequestPolicyIDRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyID is required", Path: "ConfirmSurrenderRequest.PolicyID", Type: "required"}

	// ErrConfirmSurrenderRequestDisbursementMethodOneofValidation is the error returned when the field is not one of the allowed values.
	ErrConfirmSurrenderRequestDisbursementMethodOneofValidation = govaliderrors.ValidationError{Reason: "field DisbursementMethod must be one of CASH CHEQUE", Path: "ConfirmSurrenderRequest.DisbursementMethod", Type: "oneof"}

	// ErrConfirmSurrenderRequestDisbursementMethodRequiredValidation is returned when the DisbursementMethod is required but not provided.
	ErrConfirmSurrenderRequestDisbursementMethodRequiredValidation = govaliderrors.ValidationError{Reason: "field DisbursementMethod is required", Path: "ConfirmSurrenderRequest.DisbursementMethod", Type: "required"}
)

func ValidateConfirmSurrenderRequest(t *ConfirmSurrenderRequest) error {
	if t == nil {
		return ErrNilConfirmSurrenderRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.PolicyID == "" {
		err := ErrConfirmSurrenderRequestPolicyIDRequiredValidation
		err.Value = t.PolicyID
		errs = append(errs, err)
	}

	if !(t.DisbursementMethod == "CASH" || t.DisbursementMethod == "CHEQUE") {
		err := ErrConfirmSurrenderRequestDisbursementMethodOneofValidation
		err.Value = t.DisbursementMethod
		errs = append(errs, err)
	}

	if t.DisbursementMethod == "" {
		err := ErrConfirmSurrenderRequestDisbursementMethodRequiredValidation
		err.Value = t.DisbursementMethod
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ConfirmSurrenderRequest)(nil)

func (t *ConfirmSurrenderRequest) Validate() error {
	return ValidateConfirmSurrenderRequest(t)
}
