// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilCalculateSurrenderRequest is returned when the CalculateSurrenderRequest is nil.
	ErrNilCalculateSurrenderRequest = errors.New("input CalculateSurrenderRequest is nil")

	// ErrCalculateSurrenderRequestPolicyIDRequiredValidation is returned when the PolicyID is required but not provided.
	ErrCalculateSurrenderRequestPolicyIDRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyID is required", Path: "CalculateSurrenderRequest.PolicyID", Type: "required"}
)

func ValidateCalculateSurrenderRequest(t *CalculateSurrenderRequest) error {
	if t == nil {
		return ErrNilCalculateSurrenderRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.PolicyID == "" {
		err := ErrCalculateSurrenderRequestPolicyIDRequiredValidation
		err.Value = t.PolicyID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CalculateSurrenderRequest)(nil)

func (t *CalculateSurrenderRequest) Validate() error {
	return ValidateCalculateSurrenderRequest(t)
}
