// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilRejectSurrenderRequest is returned when the RejectSurrenderRequest is nil.
	ErrNilRejectSurrenderRequest = errors.New("input RejectSurrenderRequest is nil")

	// ErrRejectSurrenderRequestSurrenderRequestIDRequiredValidation is returned when the SurrenderRequestID is required but not provided.
	ErrRejectSurrenderRequestSurrenderRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SurrenderRequestID is required", Path: "RejectSurrenderRequest.SurrenderRequestID", Type: "required"}

	// ErrRejectSurrenderRequestApproverUserIDRequiredValidation is returned when the ApproverUserID is required but not provided.
	ErrRejectSurrenderRequestApproverUserIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApproverUserID is required", Path: "RejectSurrenderRequest.ApproverUserID", Type: "required"}

	// ErrRejectSurrenderRequestRejectionReasonMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 500.
	ErrRejectSurrenderRequestRejectionReasonMaxLengthValidation = govaliderrors.ValidationError{Reason: "field RejectionReason must have a maximum length of 500", Path: "RejectSurrenderRequest.RejectionReason", Type: "maxlength"}

	// ErrRejectSurrenderRequestRejectionReasonMinLengthValidation is the error returned when the length of the field is less than the minimum of 10.
	ErrRejectSurrenderRequestRejectionReasonMinLengthValidation = govaliderrors.ValidationError{Reason: "field RejectionReason must have a minimum length of 10", Path: "RejectSurrenderRequest.RejectionReason", Type: "minlength"}

	// ErrRejectSurrenderRequestRejectionReasonRequiredValidation is returned when the RejectionReason is required but not provided.
	ErrRejectSurrenderRequestRejectionReasonRequiredValidation = govaliderrors.ValidationError{Reason: "field RejectionReason is required", Path: "RejectSurrenderRequest.RejectionReason", Type: "required"}

	// ErrRejectSurrenderRequestApproverIDRequiredValidation is returned when the ApproverID is required but not provided.
	ErrRejectSurrenderRequestApproverIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApproverID is required", Path: "RejectSurrenderRequest.ApproverID", Type: "required"}

	// ErrRejectSurrenderRequestRejectorUserIDRequiredValidation is returned when the RejectorUserID is required but not provided.
	ErrRejectSurrenderRequestRejectorUserIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RejectorUserID is required", Path: "RejectSurrenderRequest.RejectorUserID", Type: "required"}
)

func ValidateRejectSurrenderRequest(t *RejectSurrenderRequest) error {
	if t == nil {
		return ErrNilRejectSurrenderRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.SurrenderRequestID == "" {
		err := ErrRejectSurrenderRequestSurrenderRequestIDRequiredValidation
		err.Value = t.SurrenderRequestID
		errs = append(errs, err)
	}

	if t.ApproverUserID == "" {
		err := ErrRejectSurrenderRequestApproverUserIDRequiredValidation
		err.Value = t.ApproverUserID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.RejectionReason) > 500 {
		err := ErrRejectSurrenderRequestRejectionReasonMaxLengthValidation
		err.Value = t.RejectionReason
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.RejectionReason) < 10 {
		err := ErrRejectSurrenderRequestRejectionReasonMinLengthValidation
		err.Value = t.RejectionReason
		errs = append(errs, err)
	}

	if t.RejectionReason == "" {
		err := ErrRejectSurrenderRequestRejectionReasonRequiredValidation
		err.Value = t.RejectionReason
		errs = append(errs, err)
	}

	if t.ApproverID == "" {
		err := ErrRejectSurrenderRequestApproverIDRequiredValidation
		err.Value = t.ApproverID
		errs = append(errs, err)
	}

	if t.RejectorUserID == "" {
		err := ErrRejectSurrenderRequestRejectorUserIDRequiredValidation
		err.Value = t.RejectorUserID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*RejectSurrenderRequest)(nil)

func (t *RejectSurrenderRequest) Validate() error {
	return ValidateRejectSurrenderRequest(t)
}
