// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilCreatePaymentWindowRequest is returned when the CreatePaymentWindowRequest is nil.
	ErrNilCreatePaymentWindowRequest = errors.New("input CreatePaymentWindowRequest is nil")

	// ErrCreatePaymentWindowRequestSurrenderRequestIDRequiredValidation is returned when the SurrenderRequestID is required but not provided.
	ErrCreatePaymentWindowRequestSurrenderRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SurrenderRequestID is required", Path: "CreatePaymentWindowRequest.SurrenderRequestID", Type: "required"}

	// ErrCreatePaymentWindowRequestReminderIDRequiredValidation is returned when the ReminderID is required but not provided.
	ErrCreatePaymentWindowRequestReminderIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ReminderID is required", Path: "CreatePaymentWindowRequest.ReminderID", Type: "required"}

	// ErrCreatePaymentWindowRequestWindowStartDateRequiredValidation is returned when the WindowStartDate is required but not provided.
	ErrCreatePaymentWindowRequestWindowStartDateRequiredValidation = govaliderrors.ValidationError{Reason: "field WindowStartDate is required", Path: "CreatePaymentWindowRequest.WindowStartDate", Type: "required"}

	// ErrCreatePaymentWindowRequestWindowEndDateRequiredValidation is returned when the WindowEndDate is required but not provided.
	ErrCreatePaymentWindowRequestWindowEndDateRequiredValidation = govaliderrors.ValidationError{Reason: "field WindowEndDate is required", Path: "CreatePaymentWindowRequest.WindowEndDate", Type: "required"}
)

func ValidateCreatePaymentWindowRequest(t *CreatePaymentWindowRequest) error {
	if t == nil {
		return ErrNilCreatePaymentWindowRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.SurrenderRequestID == "" {
		err := ErrCreatePaymentWindowRequestSurrenderRequestIDRequiredValidation
		err.Value = t.SurrenderRequestID
		errs = append(errs, err)
	}

	if t.ReminderID == "" {
		err := ErrCreatePaymentWindowRequestReminderIDRequiredValidation
		err.Value = t.ReminderID
		errs = append(errs, err)
	}

	if t.WindowStartDate == "" {
		err := ErrCreatePaymentWindowRequestWindowStartDateRequiredValidation
		err.Value = t.WindowStartDate
		errs = append(errs, err)
	}

	if t.WindowEndDate == "" {
		err := ErrCreatePaymentWindowRequestWindowEndDateRequiredValidation
		err.Value = t.WindowEndDate
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CreatePaymentWindowRequest)(nil)

func (t *CreatePaymentWindowRequest) Validate() error {
	return ValidateCreatePaymentWindowRequest(t)
}
