// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilRecalculateRequest is returned when the RecalculateRequest is nil.
	ErrNilRecalculateRequest = errors.New("input RecalculateRequest is nil")

	// ErrRecalculateRequestSurrenderRequestIDRequiredValidation is returned when the SurrenderRequestID is required but not provided.
	ErrRecalculateRequestSurrenderRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SurrenderRequestID is required", Path: "RecalculateRequest.SurrenderRequestID", Type: "required"}

	// ErrRecalculateRequestUserIDRequiredValidation is returned when the UserID is required but not provided.
	ErrRecalculateRequestUserIDRequiredValidation = govaliderrors.ValidationError{Reason: "field UserID is required", Path: "RecalculateRequest.UserID", Type: "required"}

	// ErrRecalculateRequestRecalculationReasonMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 500.
	ErrRecalculateRequestRecalculationReasonMaxLengthValidation = govaliderrors.ValidationError{Reason: "field RecalculationReason must have a maximum length of 500", Path: "RecalculateRequest.RecalculationReason", Type: "maxlength"}

	// ErrRecalculateRequestRecalculationReasonMinLengthValidation is the error returned when the length of the field is less than the minimum of 10.
	ErrRecalculateRequestRecalculationReasonMinLengthValidation = govaliderrors.ValidationError{Reason: "field RecalculationReason must have a minimum length of 10", Path: "RecalculateRequest.RecalculationReason", Type: "minlength"}

	// ErrRecalculateRequestRecalculationReasonRequiredValidation is returned when the RecalculationReason is required but not provided.
	ErrRecalculateRequestRecalculationReasonRequiredValidation = govaliderrors.ValidationError{Reason: "field RecalculationReason is required", Path: "RecalculateRequest.RecalculationReason", Type: "required"}
)

func ValidateRecalculateRequest(t *RecalculateRequest) error {
	if t == nil {
		return ErrNilRecalculateRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.SurrenderRequestID == "" {
		err := ErrRecalculateRequestSurrenderRequestIDRequiredValidation
		err.Value = t.SurrenderRequestID
		errs = append(errs, err)
	}

	if t.UserID == "" {
		err := ErrRecalculateRequestUserIDRequiredValidation
		err.Value = t.UserID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.RecalculationReason) > 500 {
		err := ErrRecalculateRequestRecalculationReasonMaxLengthValidation
		err.Value = t.RecalculationReason
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.RecalculationReason) < 10 {
		err := ErrRecalculateRequestRecalculationReasonMinLengthValidation
		err.Value = t.RecalculationReason
		errs = append(errs, err)
	}

	if t.RecalculationReason == "" {
		err := ErrRecalculateRequestRecalculationReasonRequiredValidation
		err.Value = t.RecalculationReason
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*RecalculateRequest)(nil)

func (t *RecalculateRequest) Validate() error {
	return ValidateRecalculateRequest(t)
}
