// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilUploadDocumentRequest is returned when the UploadDocumentRequest is nil.
	ErrNilUploadDocumentRequest = errors.New("input UploadDocumentRequest is nil")

	// ErrUploadDocumentRequestSurrenderRequestIDRequiredValidation is returned when the SurrenderRequestID is required but not provided.
	ErrUploadDocumentRequestSurrenderRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SurrenderRequestID is required", Path: "UploadDocumentRequest.SurrenderRequestID", Type: "required"}

	// ErrUploadDocumentRequestDocumentTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrUploadDocumentRequestDocumentTypeOneofValidation = govaliderrors.ValidationError{Reason: "field DocumentType must be one of WRITTEN_CONSENT POLICY_BOND PREMIUM_RECEIPT_BOOK PAY_RECOVERY_CERTIFICATE LOAN_RECEIPT_BOOK LOAN_BOND INDEMNITY_BOND ASSIGNMENT_DEED DISCHARGE_RECEIPT", Path: "UploadDocumentRequest.DocumentType", Type: "oneof"}

	// ErrUploadDocumentRequestDocumentTypeRequiredValidation is returned when the DocumentType is required but not provided.
	ErrUploadDocumentRequestDocumentTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field DocumentType is required", Path: "UploadDocumentRequest.DocumentType", Type: "required"}

	// ErrUploadDocumentRequestFileRequiredValidation is returned when the File is required but not provided.
	ErrUploadDocumentRequestFileRequiredValidation = govaliderrors.ValidationError{Reason: "field File is required", Path: "UploadDocumentRequest.File", Type: "required"}
)

func ValidateUploadDocumentRequest(t *UploadDocumentRequest) error {
	if t == nil {
		return ErrNilUploadDocumentRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.SurrenderRequestID == "" {
		err := ErrUploadDocumentRequestSurrenderRequestIDRequiredValidation
		err.Value = t.SurrenderRequestID
		errs = append(errs, err)
	}

	if !(t.DocumentType == "WRITTEN_CONSENT" || t.DocumentType == "POLICY_BOND" || t.DocumentType == "PREMIUM_RECEIPT_BOOK" || t.DocumentType == "PAY_RECOVERY_CERTIFICATE" || t.DocumentType == "LOAN_RECEIPT_BOOK" || t.DocumentType == "LOAN_BOND" || t.DocumentType == "INDEMNITY_BOND" || t.DocumentType == "ASSIGNMENT_DEED" || t.DocumentType == "DISCHARGE_RECEIPT") {
		err := ErrUploadDocumentRequestDocumentTypeOneofValidation
		err.Value = t.DocumentType
		errs = append(errs, err)
	}

	if t.DocumentType == "" {
		err := ErrUploadDocumentRequestDocumentTypeRequiredValidation
		err.Value = t.DocumentType
		errs = append(errs, err)
	}

	if t.File == nil {
		err := ErrUploadDocumentRequestFileRequiredValidation
		err.Value = t.File
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*UploadDocumentRequest)(nil)

func (t *UploadDocumentRequest) Validate() error {
	return ValidateUploadDocumentRequest(t)
}
