// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilEscalateTaskRequest is returned when the EscalateTaskRequest is nil.
	ErrNilEscalateTaskRequest = errors.New("input EscalateTaskRequest is nil")

	// ErrEscalateTaskRequestTaskIDRequiredValidation is returned when the TaskID is required but not provided.
	ErrEscalateTaskRequestTaskIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TaskID is required", Path: "EscalateTaskRequest.TaskID", Type: "required"}

	// ErrEscalateTaskRequestEscalationReasonMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 500.
	ErrEscalateTaskRequestEscalationReasonMaxLengthValidation = govaliderrors.ValidationError{Reason: "field EscalationReason must have a maximum length of 500", Path: "EscalateTaskRequest.EscalationReason", Type: "maxlength"}

	// ErrEscalateTaskRequestEscalationReasonMinLengthValidation is the error returned when the length of the field is less than the minimum of 10.
	ErrEscalateTaskRequestEscalationReasonMinLengthValidation = govaliderrors.ValidationError{Reason: "field EscalationReason must have a minimum length of 10", Path: "EscalateTaskRequest.EscalationReason", Type: "minlength"}

	// ErrEscalateTaskRequestEscalationReasonRequiredValidation is returned when the EscalationReason is required but not provided.
	ErrEscalateTaskRequestEscalationReasonRequiredValidation = govaliderrors.ValidationError{Reason: "field EscalationReason is required", Path: "EscalateTaskRequest.EscalationReason", Type: "required"}

	// ErrEscalateTaskRequestUserIDRequiredValidation is returned when the UserID is required but not provided.
	ErrEscalateTaskRequestUserIDRequiredValidation = govaliderrors.ValidationError{Reason: "field UserID is required", Path: "EscalateTaskRequest.UserID", Type: "required"}

	// ErrEscalateTaskRequestEscalatedByRequiredValidation is returned when the EscalatedBy is required but not provided.
	ErrEscalateTaskRequestEscalatedByRequiredValidation = govaliderrors.ValidationError{Reason: "field EscalatedBy is required", Path: "EscalateTaskRequest.EscalatedBy", Type: "required"}

	// ErrEscalateTaskRequestEscalateToRequiredValidation is returned when the EscalateTo is required but not provided.
	ErrEscalateTaskRequestEscalateToRequiredValidation = govaliderrors.ValidationError{Reason: "field EscalateTo is required", Path: "EscalateTaskRequest.EscalateTo", Type: "required"}
)

func ValidateEscalateTaskRequest(t *EscalateTaskRequest) error {
	if t == nil {
		return ErrNilEscalateTaskRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TaskID == "" {
		err := ErrEscalateTaskRequestTaskIDRequiredValidation
		err.Value = t.TaskID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.EscalationReason) > 500 {
		err := ErrEscalateTaskRequestEscalationReasonMaxLengthValidation
		err.Value = t.EscalationReason
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.EscalationReason) < 10 {
		err := ErrEscalateTaskRequestEscalationReasonMinLengthValidation
		err.Value = t.EscalationReason
		errs = append(errs, err)
	}

	if t.EscalationReason == "" {
		err := ErrEscalateTaskRequestEscalationReasonRequiredValidation
		err.Value = t.EscalationReason
		errs = append(errs, err)
	}

	if t.UserID == "" {
		err := ErrEscalateTaskRequestUserIDRequiredValidation
		err.Value = t.UserID
		errs = append(errs, err)
	}

	if t.EscalatedBy == "" {
		err := ErrEscalateTaskRequestEscalatedByRequiredValidation
		err.Value = t.EscalatedBy
		errs = append(errs, err)
	}

	if t.EscalateTo == "" {
		err := ErrEscalateTaskRequestEscalateToRequiredValidation
		err.Value = t.EscalateTo
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*EscalateTaskRequest)(nil)

func (t *EscalateTaskRequest) Validate() error {
	return ValidateEscalateTaskRequest(t)
}
