// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilEscalateRequestRequest is returned when the EscalateRequestRequest is nil.
	ErrNilEscalateRequestRequest = errors.New("input EscalateRequestRequest is nil")

	// ErrEscalateRequestRequestTaskIDRequiredValidation is returned when the TaskID is required but not provided.
	ErrEscalateRequestRequestTaskIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TaskID is required", Path: "EscalateRequestRequest.TaskID", Type: "required"}

	// ErrEscalateRequestRequestEscalateToRequiredValidation is returned when the EscalateTo is required but not provided.
	ErrEscalateRequestRequestEscalateToRequiredValidation = govaliderrors.ValidationError{Reason: "field EscalateTo is required", Path: "EscalateRequestRequest.EscalateTo", Type: "required"}

	// ErrEscalateRequestRequestEscalationReasonMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 500.
	ErrEscalateRequestRequestEscalationReasonMaxLengthValidation = govaliderrors.ValidationError{Reason: "field EscalationReason must have a maximum length of 500", Path: "EscalateRequestRequest.EscalationReason", Type: "maxlength"}

	// ErrEscalateRequestRequestEscalationReasonMinLengthValidation is the error returned when the length of the field is less than the minimum of 10.
	ErrEscalateRequestRequestEscalationReasonMinLengthValidation = govaliderrors.ValidationError{Reason: "field EscalationReason must have a minimum length of 10", Path: "EscalateRequestRequest.EscalationReason", Type: "minlength"}

	// ErrEscalateRequestRequestEscalationReasonRequiredValidation is returned when the EscalationReason is required but not provided.
	ErrEscalateRequestRequestEscalationReasonRequiredValidation = govaliderrors.ValidationError{Reason: "field EscalationReason is required", Path: "EscalateRequestRequest.EscalationReason", Type: "required"}
)

func ValidateEscalateRequestRequest(t *EscalateRequestRequest) error {
	if t == nil {
		return ErrNilEscalateRequestRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TaskID == "" {
		err := ErrEscalateRequestRequestTaskIDRequiredValidation
		err.Value = t.TaskID
		errs = append(errs, err)
	}

	if t.EscalateTo == "" {
		err := ErrEscalateRequestRequestEscalateToRequiredValidation
		err.Value = t.EscalateTo
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.EscalationReason) > 500 {
		err := ErrEscalateRequestRequestEscalationReasonMaxLengthValidation
		err.Value = t.EscalationReason
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.EscalationReason) < 10 {
		err := ErrEscalateRequestRequestEscalationReasonMinLengthValidation
		err.Value = t.EscalationReason
		errs = append(errs, err)
	}

	if t.EscalationReason == "" {
		err := ErrEscalateRequestRequestEscalationReasonRequiredValidation
		err.Value = t.EscalationReason
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*EscalateRequestRequest)(nil)

func (t *EscalateRequestRequest) Validate() error {
	return ValidateEscalateRequestRequest(t)
}
