// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilForwardToApprovalRequest is returned when the ForwardToApprovalRequest is nil.
	ErrNilForwardToApprovalRequest = errors.New("input ForwardToApprovalRequest is nil")

	// ErrForwardToApprovalRequestSurrenderRequestIDRequiredValidation is returned when the SurrenderRequestID is required but not provided.
	ErrForwardToApprovalRequestSurrenderRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SurrenderRequestID is required", Path: "ForwardToApprovalRequest.SurrenderRequestID", Type: "required"}
)

func ValidateForwardToApprovalRequest(t *ForwardToApprovalRequest) error {
	if t == nil {
		return ErrNilForwardToApprovalRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.SurrenderRequestID == "" {
		err := ErrForwardToApprovalRequestSurrenderRequestIDRequiredValidation
		err.Value = t.SurrenderRequestID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ForwardToApprovalRequest)(nil)

func (t *ForwardToApprovalRequest) Validate() error {
	return ValidateForwardToApprovalRequest(t)
}
