// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilGetDEPendingRequest is returned when the GetDEPendingRequest is nil.
	ErrNilGetDEPendingRequest = errors.New("input GetDEPendingRequest is nil")

	// ErrGetDEPendingRequestOidRequiredValidation is returned when the Oid is required but not provided.
	ErrGetDEPendingRequestOidRequiredValidation = govaliderrors.ValidationError{Reason: "field Oid is required", Path: "GetDEPendingRequest.Oid", Type: "required"}
)

func ValidateGetDEPendingRequest(t *GetDEPendingRequest) error {
	if t == nil {
		return ErrNilGetDEPendingRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.Oid == 0 {
		err := ErrGetDEPendingRequestOidRequiredValidation
		err.Value = t.Oid
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*GetDEPendingRequest)(nil)

func (t *GetDEPendingRequest) Validate() error {
	return ValidateGetDEPendingRequest(t)
}
