// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilRequestDetailParams is returned when the RequestDetailParams is nil.
	ErrNilRequestDetailParams = errors.New("input RequestDetailParams is nil")

	// ErrRequestDetailParamsSurrenderRequestIDRequiredValidation is returned when the SurrenderRequestID is required but not provided.
	ErrRequestDetailParamsSurrenderRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SurrenderRequestID is required", Path: "RequestDetailParams.SurrenderRequestID", Type: "required"}
)

func ValidateRequestDetailParams(t *RequestDetailParams) error {
	if t == nil {
		return ErrNilRequestDetailParams
	}

	var errs govaliderrors.ValidationErrors

	if t.SurrenderRequestID == "" {
		err := ErrRequestDetailParamsSurrenderRequestIDRequiredValidation
		err.Value = t.SurrenderRequestID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*RequestDetailParams)(nil)

func (t *RequestDetailParams) Validate() error {
	return ValidateRequestDetailParams(t)
}
