// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilSubmitForVerificationRequest is returned when the SubmitForVerificationRequest is nil.
	ErrNilSubmitForVerificationRequest = errors.New("input SubmitForVerificationRequest is nil")

	// ErrSubmitForVerificationRequestSurrenderRequestIDRequiredValidation is returned when the SurrenderRequestID is required but not provided.
	ErrSubmitForVerificationRequestSurrenderRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SurrenderRequestID is required", Path: "SubmitForVerificationRequest.SurrenderRequestID", Type: "required"}
)

func ValidateSubmitForVerificationRequest(t *SubmitForVerificationRequest) error {
	if t == nil {
		return ErrNilSubmitForVerificationRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.SurrenderRequestID == "" {
		err := ErrSubmitForVerificationRequestSurrenderRequestIDRequiredValidation
		err.Value = t.SurrenderRequestID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*SubmitForVerificationRequest)(nil)

func (t *SubmitForVerificationRequest) Validate() error {
	return ValidateSubmitForVerificationRequest(t)
}
