// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilEvaluatePolicyRequest is returned when the EvaluatePolicyRequest is nil.
	ErrNilEvaluatePolicyRequest = errors.New("input EvaluatePolicyRequest is nil")

	// ErrEvaluatePolicyRequestPolicyIDRequiredValidation is returned when the PolicyID is required but not provided.
	ErrEvaluatePolicyRequestPolicyIDRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyID is required", Path: "EvaluatePolicyRequest.PolicyID", Type: "required"}
)

func ValidateEvaluatePolicyRequest(t *EvaluatePolicyRequest) error {
	if t == nil {
		return ErrNilEvaluatePolicyRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.PolicyID == "" {
		err := ErrEvaluatePolicyRequestPolicyIDRequiredValidation
		err.Value = t.PolicyID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*EvaluatePolicyRequest)(nil)

func (t *EvaluatePolicyRequest) Validate() error {
	return ValidateEvaluatePolicyRequest(t)
}
