// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilValidateEligibilityRequest is returned when the ValidateEligibilityRequest is nil.
	ErrNilValidateEligibilityRequest = errors.New("input ValidateEligibilityRequest is nil")

	// ErrValidateEligibilityRequestPolicyIDRequiredValidation is returned when the PolicyID is required but not provided.
	ErrValidateEligibilityRequestPolicyIDRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyID is required", Path: "ValidateEligibilityRequest.PolicyID", Type: "required"}
)

func ValidateValidateEligibilityRequest(t *ValidateEligibilityRequest) error {
	if t == nil {
		return ErrNilValidateEligibilityRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.PolicyID == "" {
		err := ErrValidateEligibilityRequestPolicyIDRequiredValidation
		err.Value = t.PolicyID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ValidateEligibilityRequest)(nil)

func (t *ValidateEligibilityRequest) Validate() error {
	return ValidateValidateEligibilityRequest(t)
}
