// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilSubmitDERequest is returned when the SubmitDERequest is nil.
	ErrNilSubmitDERequest = errors.New("input SubmitDERequest is nil")

	// ErrSubmitDERequestSurrender_request_idRequiredValidation is returned when the Surrender_request_id is required but not provided.
	ErrSubmitDERequestSurrender_request_idRequiredValidation = govaliderrors.ValidationError{Reason: "field Surrender_request_id is required", Path: "SubmitDERequest.Surrender_request_id", Type: "required"}
)

func ValidateSubmitDERequest(t *SubmitDERequest) error {
	if t == nil {
		return ErrNilSubmitDERequest
	}

	var errs govaliderrors.ValidationErrors

	if t.Surrender_request_id == "" {
		err := ErrSubmitDERequestSurrender_request_idRequiredValidation
		err.Value = t.Surrender_request_id
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*SubmitDERequest)(nil)

func (t *SubmitDERequest) Validate() error {
	return ValidateSubmitDERequest(t)
}
