// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilAutoCompleteRequest is returned when the AutoCompleteRequest is nil.
	ErrNilAutoCompleteRequest = errors.New("input AutoCompleteRequest is nil")

	// ErrAutoCompleteRequestSurrenderRequestIDRequiredValidation is returned when the SurrenderRequestID is required but not provided.
	ErrAutoCompleteRequestSurrenderRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SurrenderRequestID is required", Path: "AutoCompleteRequest.SurrenderRequestID", Type: "required"}
)

func ValidateAutoCompleteRequest(t *AutoCompleteRequest) error {
	if t == nil {
		return ErrNilAutoCompleteRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.SurrenderRequestID == "" {
		err := ErrAutoCompleteRequestSurrenderRequestIDRequiredValidation
		err.Value = t.SurrenderRequestID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*AutoCompleteRequest)(nil)

func (t *AutoCompleteRequest) Validate() error {
	return ValidateAutoCompleteRequest(t)
}
