// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilSRIDDetailsRequest is returned when the SRIDDetailsRequest is nil.
	ErrNilSRIDDetailsRequest = errors.New("input SRIDDetailsRequest is nil")

	// ErrSRIDDetailsRequestSurrender_request_idRequiredValidation is returned when the Surrender_request_id is required but not provided.
	ErrSRIDDetailsRequestSurrender_request_idRequiredValidation = govaliderrors.ValidationError{Reason: "field Surrender_request_id is required", Path: "SRIDDetailsRequest.Surrender_request_id", Type: "required"}
)

func ValidateSRIDDetailsRequest(t *SRIDDetailsRequest) error {
	if t == nil {
		return ErrNilSRIDDetailsRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.Surrender_request_id == "" {
		err := ErrSRIDDetailsRequestSurrender_request_idRequiredValidation
		err.Value = t.Surrender_request_id
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*SRIDDetailsRequest)(nil)

func (t *SRIDDetailsRequest) Validate() error {
	return ValidateSRIDDetailsRequest(t)
}
