// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilTriggerMonthlyEvaluationRequest is returned when the TriggerMonthlyEvaluationRequest is nil.
	ErrNilTriggerMonthlyEvaluationRequest = errors.New("input TriggerMonthlyEvaluationRequest is nil")

	// ErrTriggerMonthlyEvaluationRequestEvaluationMonthRequiredValidation is returned when the EvaluationMonth is required but not provided.
	ErrTriggerMonthlyEvaluationRequestEvaluationMonthRequiredValidation = govaliderrors.ValidationError{Reason: "field EvaluationMonth is required", Path: "TriggerMonthlyEvaluationRequest.EvaluationMonth", Type: "required"}

	// ErrTriggerMonthlyEvaluationRequestEvaluationDateRequiredValidation is returned when the EvaluationDate is required but not provided.
	ErrTriggerMonthlyEvaluationRequestEvaluationDateRequiredValidation = govaliderrors.ValidationError{Reason: "field EvaluationDate is required", Path: "TriggerMonthlyEvaluationRequest.EvaluationDate", Type: "required"}
)

func ValidateTriggerMonthlyEvaluationRequest(t *TriggerMonthlyEvaluationRequest) error {
	if t == nil {
		return ErrNilTriggerMonthlyEvaluationRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.EvaluationMonth == "" {
		err := ErrTriggerMonthlyEvaluationRequestEvaluationMonthRequiredValidation
		err.Value = t.EvaluationMonth
		errs = append(errs, err)
	}

	if t.EvaluationDate == "" {
		err := ErrTriggerMonthlyEvaluationRequestEvaluationDateRequiredValidation
		err.Value = t.EvaluationDate
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*TriggerMonthlyEvaluationRequest)(nil)

func (t *TriggerMonthlyEvaluationRequest) Validate() error {
	return ValidateTriggerMonthlyEvaluationRequest(t)
}
