// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilReleaseTaskRequest is returned when the ReleaseTaskRequest is nil.
	ErrNilReleaseTaskRequest = errors.New("input ReleaseTaskRequest is nil")

	// ErrReleaseTaskRequestTaskIDRequiredValidation is returned when the TaskID is required but not provided.
	ErrReleaseTaskRequestTaskIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TaskID is required", Path: "ReleaseTaskRequest.TaskID", Type: "required"}

	// ErrReleaseTaskRequestUserIDRequiredValidation is returned when the UserID is required but not provided.
	ErrReleaseTaskRequestUserIDRequiredValidation = govaliderrors.ValidationError{Reason: "field UserID is required", Path: "ReleaseTaskRequest.UserID", Type: "required"}
)

func ValidateReleaseTaskRequest(t *ReleaseTaskRequest) error {
	if t == nil {
		return ErrNilReleaseTaskRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TaskID == "" {
		err := ErrReleaseTaskRequestTaskIDRequiredValidation
		err.Value = t.TaskID
		errs = append(errs, err)
	}

	if t.UserID == "" {
		err := ErrReleaseTaskRequestUserIDRequiredValidation
		err.Value = t.UserID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ReleaseTaskRequest)(nil)

func (t *ReleaseTaskRequest) Validate() error {
	return ValidateReleaseTaskRequest(t)
}
