// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilRevertStatusRequest is returned when the RevertStatusRequest is nil.
	ErrNilRevertStatusRequest = errors.New("input RevertStatusRequest is nil")

	// ErrRevertStatusRequestSurrenderRequestIDRequiredValidation is returned when the SurrenderRequestID is required but not provided.
	ErrRevertStatusRequestSurrenderRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SurrenderRequestID is required", Path: "RevertStatusRequest.SurrenderRequestID", Type: "required"}
)

func ValidateRevertStatusRequest(t *RevertStatusRequest) error {
	if t == nil {
		return ErrNilRevertStatusRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.SurrenderRequestID == "" {
		err := ErrRevertStatusRequestSurrenderRequestIDRequiredValidation
		err.Value = t.SurrenderRequestID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*RevertStatusRequest)(nil)

func (t *RevertStatusRequest) Validate() error {
	return ValidateRevertStatusRequest(t)
}
