// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilInitiateForcedSurrenderRequest is returned when the InitiateForcedSurrenderRequest is nil.
	ErrNilInitiateForcedSurrenderRequest = errors.New("input InitiateForcedSurrenderRequest is nil")

	// ErrInitiateForcedSurrenderRequestPolicyIDRequiredValidation is returned when the PolicyID is required but not provided.
	ErrInitiateForcedSurrenderRequestPolicyIDRequiredValidation = govaliderrors.ValidationError{Reason: "field PolicyID is required", Path: "InitiateForcedSurrenderRequest.PolicyID", Type: "required"}

	// ErrInitiateForcedSurrenderRequestReasonMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 500.
	ErrInitiateForcedSurrenderRequestReasonMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Reason must have a maximum length of 500", Path: "InitiateForcedSurrenderRequest.Reason", Type: "maxlength"}
)

func ValidateInitiateForcedSurrenderRequest(t *InitiateForcedSurrenderRequest) error {
	if t == nil {
		return ErrNilInitiateForcedSurrenderRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.PolicyID == "" {
		err := ErrInitiateForcedSurrenderRequestPolicyIDRequiredValidation
		err.Value = t.PolicyID
		errs = append(errs, err)
	}

	if t.Reason != "" && utf8.RuneCountInString(t.Reason) > 500 {
		err := ErrInitiateForcedSurrenderRequestReasonMaxLengthValidation
		err.Value = t.Reason
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*InitiateForcedSurrenderRequest)(nil)

func (t *InitiateForcedSurrenderRequest) Validate() error {
	return ValidateInitiateForcedSurrenderRequest(t)
}
