// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilReleaseRequestRequest is returned when the ReleaseRequestRequest is nil.
	ErrNilReleaseRequestRequest = errors.New("input ReleaseRequestRequest is nil")

	// ErrReleaseRequestRequestTaskIDRequiredValidation is returned when the TaskID is required but not provided.
	ErrReleaseRequestRequestTaskIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TaskID is required", Path: "ReleaseRequestRequest.TaskID", Type: "required"}
)

func ValidateReleaseRequestRequest(t *ReleaseRequestRequest) error {
	if t == nil {
		return ErrNilReleaseRequestRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TaskID == "" {
		err := ErrReleaseRequestRequestTaskIDRequiredValidation
		err.Value = t.TaskID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ReleaseRequestRequest)(nil)

func (t *ReleaseRequestRequest) Validate() error {
	return ValidateReleaseRequestRequest(t)
}
