// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilSurrenderStatusParams is returned when the SurrenderStatusParams is nil.
	ErrNilSurrenderStatusParams = errors.New("input SurrenderStatusParams is nil")

	// ErrSurrenderStatusParamsSurrenderRequestIDRequiredValidation is returned when the SurrenderRequestID is required but not provided.
	ErrSurrenderStatusParamsSurrenderRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SurrenderRequestID is required", Path: "SurrenderStatusParams.SurrenderRequestID", Type: "required"}
)

func ValidateSurrenderStatusParams(t *SurrenderStatusParams) error {
	if t == nil {
		return ErrNilSurrenderStatusParams
	}

	var errs govaliderrors.ValidationErrors

	if t.SurrenderRequestID == "" {
		err := ErrSurrenderStatusParamsSurrenderRequestIDRequiredValidation
		err.Value = t.SurrenderRequestID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*SurrenderStatusParams)(nil)

func (t *SurrenderStatusParams) Validate() error {
	return ValidateSurrenderStatusParams(t)
}
